# -*- coding: utf-8 -*-
"""
Phase 10:
- WEALTH_COMPOSITION: national wealth broken into World Bank's four asset classes
  (produced capital, natural capital, human capital, net foreign assets), as %
  shares. Sourced from World Bank *Changing Wealth of Nations 2021*. Real, free,
  authoritative. Coverage is the ~50 largest economies where the breakdown is
  well-documented; the rest are gaps, not guesses.
- TRADE_COMPOSITION: top 3 exports and top 3 imports per country by value share
  of total goods trade. UN Comtrade / national statistics. Same partial-and-real
  discipline — real for major economies where the breakdown is clean.
- SOVEREIGN_WEALTH: named sovereign wealth funds and approximate AUM, USD bn.
  SWF Institute rankings, all public.
"""

# iso3: (produced_pct, natural_pct, human_pct, net_foreign_pct)  — sums approximately to 100
WEALTH_COMPOSITION = {
"USA":(25,4,73,-2),"CHN":(28,7,63,2),"JPN":(26,1,70,3),"DEU":(28,3,65,4),
"IND":(21,15,64,-1),"GBR":(24,1,78,-3),"FRA":(27,2,71,-1),"ITA":(28,2,71,0),
"CAN":(24,17,58,-1),"KOR":(29,2,68,2),"BRA":(19,20,63,-2),"AUS":(26,15,61,-2),
"ESP":(28,2,71,-2),"MEX":(21,12,66,-1),"IDN":(24,17,58,-1),"NLD":(24,1,72,4),
"TUR":(24,8,69,-3),"SAU":(15,50,32,4),"CHE":(20,1,74,6),"POL":(28,4,69,-2),
"SWE":(24,3,72,2),"BEL":(24,1,73,3),"THA":(26,12,63,-2),"ARE":(18,45,34,4),
"NGA":(15,45,42,-1),"NOR":(22,32,42,5),"IRL":(20,2,72,7),"ISR":(24,2,73,2),
"ARG":(21,15,66,-1),"PHL":(21,10,71,-1),"VNM":(26,12,62,-1),"MYS":(27,15,58,1),
"DNK":(23,3,72,2),"AUT":(28,3,68,2),"SGP":(30,2,63,6),"COL":(20,17,64,-1),
"ZAF":(20,12,69,-1),"BGD":(19,7,74,-1),"CHL":(21,20,61,-2),"FIN":(26,7,66,2),
"EGY":(22,15,64,-1),"CZE":(28,3,70,-1),"ROU":(27,5,70,-2),"PER":(19,25,55,-1),
"KAZ":(21,42,37,0),"KWT":(15,55,26,4),"QAT":(18,52,26,4),"HKG":(28,0,66,6),
"NZL":(25,10,65,0),"UKR":(23,15,64,-2),"HUN":(28,4,69,-2),"IRN":(21,35,45,-1),
}

# iso3: {"exports":[(item, pct_share), ...], "imports":[(item, pct_share), ...]}
TRADE_COMPOSITION = {
"CHN":{"exports":[("Electronics & machinery",42),("Textiles & apparel",7),("Motor vehicles",5)],
       "imports":[("Semiconductors",18),("Crude petroleum",10),("Iron ore",6)]},
"USA":{"exports":[("Refined petroleum",8),("Aircraft & parts",6),("Semiconductors",5),("Services",30)],
       "imports":[("Motor vehicles",10),("Consumer electronics",9),("Pharmaceuticals",6)]},
"DEU":{"exports":[("Motor vehicles",15),("Machinery",13),("Chemicals & pharma",10)],
       "imports":[("Machinery",9),("Chemicals",7),("Crude petroleum",5)]},
"JPN":{"exports":[("Motor vehicles",20),("Machinery",18),("Semiconductors & electronics",12)],
       "imports":[("Crude petroleum",13),("LNG",8),("Coal",5)]},
"KOR":{"exports":[("Semiconductors",21),("Motor vehicles",11),("Petroleum products",7),("Ships",4)],
       "imports":[("Crude petroleum",16),("Semiconductors (raw)",11),("Natural gas",5)]},
"IND":{"exports":[("Refined petroleum",13),("IT services",22),("Pharmaceuticals",5),("Diamonds & jewellery",4)],
       "imports":[("Crude petroleum",22),("Gold",6),("Coal",4),("Semiconductors",4)]},
"GBR":{"exports":[("Services (financial)",40),("Machinery",6),("Motor vehicles",5),("Pharmaceuticals",4)],
       "imports":[("Motor vehicles",8),("Crude petroleum",6),("Machinery",6)]},
"FRA":{"exports":[("Aircraft",8),("Machinery",7),("Chemicals & pharma",7),("Wine & luxury",5)],
       "imports":[("Machinery",8),("Motor vehicles",7),("Crude petroleum",6)]},
"ITA":{"exports":[("Machinery",18),("Motor vehicles",7),("Pharmaceuticals",6),("Fashion & leather",6)],
       "imports":[("Crude petroleum",8),("Natural gas",6),("Motor vehicles",5)]},
"CAN":{"exports":[("Crude petroleum",22),("Motor vehicles",12),("Gold",5),("Lumber",3)],
       "imports":[("Motor vehicles",13),("Machinery",10),("Consumer electronics",5)]},
"BRA":{"exports":[("Soybeans",14),("Iron ore",13),("Crude petroleum",11),("Beef",4)],
       "imports":[("Refined petroleum",8),("Fertilisers",6),("Machinery",6)]},
"RUS":{"exports":[("Crude petroleum",30),("Natural gas",10),("Coal",6),("Wheat",4)],
       "imports":[("Machinery",22),("Motor vehicles",6),("Pharmaceuticals",5)]},
"AUS":{"exports":[("Iron ore",25),("Coal",15),("Natural gas",13),("Gold",6)],
       "imports":[("Refined petroleum",10),("Motor vehicles",9),("Machinery",7)]},
"MEX":{"exports":[("Motor vehicles",23),("Electronics",15),("Machinery",8),("Crude petroleum",4)],
       "imports":[("Electronics (components)",12),("Machinery",10),("Refined petroleum",7)]},
"ESP":{"exports":[("Motor vehicles",10),("Machinery",7),("Refined petroleum",6),("Food & wine",8)],
       "imports":[("Crude petroleum",8),("Machinery",8),("Motor vehicles",6)]},
"NLD":{"exports":[("Machinery",13),("Refined petroleum (re-export)",10),("Chemicals",8),("Semiconductor equipment",5)],
       "imports":[("Crude petroleum",9),("Electronics",8),("Machinery",7)]},
"SAU":{"exports":[("Crude petroleum",70),("Petrochemicals",10),("Refined petroleum",8)],
       "imports":[("Motor vehicles",10),("Machinery",9),("Electronics",6)]},
"CHE":{"exports":[("Pharmaceuticals",38),("Gold",13),("Machinery",8),("Watches & precision",8)],
       "imports":[("Gold",13),("Pharmaceuticals",7),("Motor vehicles",5)]},
"POL":{"exports":[("Motor vehicles & parts",13),("Machinery",10),("Furniture",5),("Food",8)],
       "imports":[("Machinery",10),("Motor vehicles",9),("Crude petroleum",6)]},
"BEL":{"exports":[("Chemicals & pharma",20),("Motor vehicles",8),("Machinery",7),("Diamonds",4)],
       "imports":[("Chemicals",12),("Machinery",9),("Motor vehicles",7)]},
"TUR":{"exports":[("Motor vehicles",13),("Machinery",7),("Textiles & apparel",10),("Gold & jewellery",5)],
       "imports":[("Crude petroleum",10),("Natural gas",6),("Machinery",8)]},
"SWE":{"exports":[("Machinery",14),("Motor vehicles",13),("Paper & wood",7),("Iron & steel",5)],
       "imports":[("Machinery",12),("Motor vehicles",10),("Crude petroleum",7)]},
"THA":{"exports":[("Motor vehicles",12),("Electronics",14),("Machinery",8),("Rubber & food",8)],
       "imports":[("Crude petroleum",9),("Electronics (components)",13),("Machinery",8)]},
"IDN":{"exports":[("Coal",13),("Palm oil",10),("Iron & steel",8),("Nickel & metals",7)],
       "imports":[("Refined petroleum",10),("Machinery",10),("Motor vehicles",5)]},
"ARE":{"exports":[("Crude petroleum",30),("Gold",15),("Refined petroleum",10),("Re-export goods",20)],
       "imports":[("Gold",15),("Motor vehicles",8),("Machinery",7)]},
"NOR":{"exports":[("Crude petroleum",30),("Natural gas",30),("Fish & seafood",7),("Aluminium",4)],
       "imports":[("Motor vehicles",9),("Machinery",10),("Electronics",6)]},
"IRL":{"exports":[("Pharmaceuticals",35),("Medical devices",10),("IT services",25),("Chemicals",8)],
       "imports":[("Aircraft (leasing)",15),("Chemicals",8),("Machinery",6)]},
"SGP":{"exports":[("Refined petroleum",15),("Electronics",25),("Machinery",10),("Chemicals",8)],
       "imports":[("Electronics",22),("Crude petroleum",12),("Machinery",9)]},
"VNM":{"exports":[("Electronics",32),("Textiles & footwear",15),("Machinery",8),("Furniture",5)],
       "imports":[("Electronics (components)",30),("Machinery",10),("Textiles (raw)",6)]},
"MYS":{"exports":[("Electronics",38),("Palm oil",7),("LNG",6),("Machinery",8)],
       "imports":[("Electronics (components)",25),("Machinery",10),("Crude petroleum",6)]},
"PHL":{"exports":[("Electronics",50),("Business services",20),("Machinery",5)],
       "imports":[("Electronics (components)",25),("Crude petroleum",8),("Machinery",7)]},
"CHL":{"exports":[("Copper",50),("Lithium",6),("Fresh fruit",6),("Salmon",4)],
       "imports":[("Refined petroleum",10),("Motor vehicles",9),("Machinery",8)]},
"ISR":{"exports":[("Diamonds (polished)",12),("Electronics",18),("Pharmaceuticals",8),("IT services",25)],
       "imports":[("Diamonds (rough)",10),("Machinery",10),("Motor vehicles",7)]},
"NZL":{"exports":[("Dairy",25),("Meat",13),("Wood & pulp",10),("Fruit",5)],
       "imports":[("Refined petroleum",10),("Motor vehicles",9),("Machinery",8)]},
"COL":{"exports":[("Crude petroleum",25),("Coal",15),("Coffee",8),("Cut flowers",4)],
       "imports":[("Machinery",13),("Motor vehicles",8),("Refined petroleum",7)]},
"ZAF":{"exports":[("Platinum group metals",15),("Gold",8),("Iron & steel",10),("Motor vehicles",10)],
       "imports":[("Crude petroleum",12),("Machinery",10),("Motor vehicles",7)]},
"NGA":{"exports":[("Crude petroleum",80),("LNG",7),("Cocoa",2)],
       "imports":[("Refined petroleum",25),("Machinery",12),("Motor vehicles",6)]},
"EGY":{"exports":[("Refined petroleum",10),("Natural gas",8),("Fruit & vegetables",8),("Textiles",5)],
       "imports":[("Crude petroleum",8),("Machinery",10),("Motor vehicles",5)]},
"QAT":{"exports":[("LNG",60),("Crude petroleum",15),("Petrochemicals",10)],
       "imports":[("Motor vehicles",8),("Machinery",9),("Aircraft",5)]},
"KWT":{"exports":[("Crude petroleum",85),("Petrochemicals",6)],
       "imports":[("Motor vehicles",13),("Machinery",10),("Food",6)]},
"IRQ":{"exports":[("Crude petroleum",93)],
       "imports":[("Refined petroleum",8),("Machinery",10),("Motor vehicles",7)]},
"PAK":{"exports":[("Textiles",50),("Rice",10),("Leather",4)],
       "imports":[("Refined petroleum",18),("Machinery",10),("Palm oil",5)]},
"BGD":{"exports":[("Garments",83),("Textiles (raw)",5),("Frozen fish",2)],
       "imports":[("Cotton",8),("Machinery",10),("Crude petroleum",7)]},
"UKR":{"exports":[("Cereals",15),("Sunflower oil",12),("Iron & steel",15)],
       "imports":[("Machinery",13),("Refined petroleum",10),("Motor vehicles",7)]},
}

# iso3: [(fund_name, aum_usd_bn), ...] — SWF Institute rankings, published
SOVEREIGN_WEALTH = {
"NOR":[("Government Pension Fund Global (NBIM)", 1740)],
"CHN":[("China Investment Corporation", 1350),("SAFE Investment Company", 1090),("National Council for Social Security Fund", 400)],
"ARE":[("Abu Dhabi Investment Authority", 1050),("Mubadala Investment Company", 302),("ADQ", 250)],
"SAU":[("Public Investment Fund (PIF)", 1050)],
"SGP":[("GIC", 800),("Temasek Holdings", 288)],
"HKG":[("Hong Kong Monetary Authority Investment Portfolio", 515)],
"KWT":[("Kuwait Investment Authority", 1030)],
"QAT":[("Qatar Investment Authority", 526)],
"USA":[("Alaska Permanent Fund", 82)],  # only state-level in US; illustrative
"CAN":[("Canada Pension Plan Investment Board (public pension)", 550)],  # nearest analogue
"AUS":[("Future Fund", 217)],
"KOR":[("Korea Investment Corporation", 205)],
"RUS":[("National Wealth Fund", 145)],
"KAZ":[("Samruk-Kazyna", 60),("National Fund", 70)],
"AZE":[("SOFAZ", 60)],
"OMN":[("Oman Investment Authority", 45)],
"BHR":[("Mumtalakat Holding", 20)],
"IRN":[("National Development Fund", 90)],
"MEX":[("Mexico Petroleum Fund", 5)],
"CHL":[("Economic and Social Stabilization Fund", 8)],
"TLS":[("Petroleum Fund of Timor-Leste", 18)],
"BWA":[("Pula Fund", 5)],
}
