# -*- coding: utf-8 -*-
"""
Corporations layer: top public companies per country.
Fields:
  name, iso3, ticker, sector, revenue_usd_bn, market_cap_usd_bn,
  employees_k (thousands), description, top_products

- revenue: latest fiscal year from annual reports (Tier 2, compiled)
- market_cap: mid-2026 point-in-time (Tier 3, verify — moves daily)
- employees_k: from filings, approximate
All figures in USD billions unless noted.
"""

# (name, iso3, ticker, sector, revenue_usd_bn, mktcap_usd_bn, emp_k, description, products)
CORPS = [
# ---- USA ----
("NVIDIA","USA","NVDA","Semiconductors",130,4800,36,
 "Designs GPUs and AI accelerator chips. Dominates data-centre AI infrastructure.",
 "H100/H200/B200 GPUs, CUDA platform, networking (Mellanox)"),
("Apple","USA","AAPL","Consumer technology",391,4300,164,
 "Designs consumer electronics and services. The iPhone remains the world's highest-margin hardware product.",
 "iPhone, Mac, iPad, Apple Watch, App Store, iCloud, Apple Intelligence"),
("Microsoft","USA","MSFT","Cloud & software",262,2830,228,
 "Enterprise software and cloud computing. Azure is the second-largest cloud platform globally.",
 "Azure, Office 365, Windows, GitHub, Copilot, Xbox"),
("Alphabet","USA","GOOGL","Internet & AI",402,4200,181,
 "Parent of Google. Dominant in search, digital advertising, and cloud; heavy AI investment via DeepMind.",
 "Google Search, YouTube, Google Cloud, Android, Waymo, Gemini AI"),
("Amazon","USA","AMZN","E-commerce & cloud",638,2570,1550,
 "World's largest e-commerce platform and cloud provider via AWS.",
 "AWS, Amazon.com, Prime Video, Alexa, Whole Foods, Logistics"),
("SpaceX","USA","SPCX","Aerospace",21,2100,13,
 "Reusable launch vehicles and satellite internet. The June 2026 IPO was the largest in history.",
 "Falcon 9, Starship, Starlink, Dragon crew capsule"),
("Meta Platforms","USA","META","Social media & AI",164,1400,75,
 "Owns the world's largest social media platforms. Heavy investment in AI and AR/VR.",
 "Facebook, Instagram, WhatsApp, Threads, Meta AI, Quest VR"),
("Berkshire Hathaway","USA","BRK.B","Diversified conglomerate",365,990,396,
 "Warren Buffett's investment holding company. Owns GEICO, BNSF, energy utilities, and major equity stakes.",
 "GEICO insurance, BNSF Railway, Berkshire Energy, Kraft Heinz stake"),
("Tesla","USA","TSLA","Electric vehicles & energy",98,780,125,
 "Electric vehicles, energy storage, and solar. Also develops autonomous driving technology.",
 "Model S/3/X/Y/Cybertruck, Powerwall, Megapack, FSD autopilot"),
("Broadcom","USA","AVGO","Semiconductors",52,1800,37,
 "Custom AI chips for hyperscalers and networking semiconductors. Expanded into software via VMware.",
 "Custom ASICs (XPU), networking chips, VMware, CA Technologies"),
("Exxon Mobil","USA","XOM","Oil & gas",398,480,62,
 "Largest US oil major. Upstream production, refining, and petrochemicals globally.",
 "Crude production, refining, Mobil fuels, petrochemicals, carbon capture"),
("JPMorgan Chase","USA","JPM","Banking & finance",177,780,320,
 "America's largest bank by assets. Investment banking, retail, and asset management.",
 "Consumer banking, J.P. Morgan investment bank, Chase cards, Asset & Wealth Management"),
("Walmart","USA","WMT","Retail",680,810,2100,
 "World's largest retailer by revenue. Operates 10,500 stores in 24 countries.",
 "Walmart supercentres, Sam's Club, Flipkart (India), Walmart+ membership"),
("Visa","USA","V","Payments",36,640,31,
 "World's largest card payments network by transaction volume.",
 "Visa credit/debit network, Visa Direct, B2B payments"),
("UnitedHealth Group","USA","UNH","Healthcare",400,490,440,
 "Largest US health insurer. Also operates Optum, a health services and analytics business.",
 "UnitedHealthcare insurance, Optum health services, pharmacy benefit management"),
("Mastercard","USA","MA","Payments",28,500,34,
 "Global card payments network, second only to Visa by volume.",
 "Mastercard network, Maestro, Priceless Cities, cybersecurity services"),
("Johnson & Johnson","USA","JNJ","Healthcare",88,380,131,
 "Pharmaceutical and medical device giant. Spun off consumer health as Kenvue in 2023.",
 "Oncology drugs, immunology (Stelara), MedTech (DePuy, Ethicon), Janssen vaccines"),
("Procter & Gamble","USA","PG","Consumer goods",84,390,107,
 "World's largest consumer goods company by market cap. 65+ brands.",
 "Tide, Pampers, Gillette, Head & Shoulders, Oral-B, Ariel, Downy"),
("ExxonMobil","USA","XOM","Oil & gas",398,480,62,
 "Largest US oil major. Upstream production, refining, and petrochemicals.",
 "Crude & gas production, Mobil fuels, petrochemicals, Permian Basin"),
("Chevron","USA","CVX","Oil & gas",196,280,45,
 "Major US integrated oil company. Strong position in Permian Basin and LNG.",
 "Upstream E&P, Chevron and Texaco fuels, Tengizchevroil, LNG"),
("Home Depot","USA","HD","Retail — home improvement",157,330,465,
 "World's largest home improvement retailer. ~2,300 stores in North America.",
 "Hardware, lumber, appliances, contractor services, HD Supply"),
("AbbVie","USA","ABBV","Pharmaceuticals",56,330,50,
 "Pharmaceutical company best known for Humira, the world's best-selling drug until 2023.",
 "Humira, Skyrizi, Rinvoq, Botox (aesthetic), Vraylar"),
("Eli Lilly","USA","LLY","Pharmaceuticals",45,780,44,
 "Fast-growing pharmaceutical company, now among the world's most valuable on the strength of GLP-1 drugs.",
 "Mounjaro/Zepbound (GLP-1 obesity/diabetes), Verzenio (cancer), Kisunla (Alzheimer's)"),
("Costco","USA","COST","Retail — warehouse clubs",237,390,316,
 "Membership warehouse club. Known for ultra-low margins on goods and high employee wages.",
 "Costco Wholesale, Kirkland Signature private label, travel services"),
("Salesforce","USA","CRM","Enterprise software",36,240,72,
 "World's largest CRM software company. Pivoting toward AI agents via Agentforce.",
 "Sales Cloud, Service Cloud, Agentforce AI agents, Slack, Tableau, MuleSoft"),
("Netflix","USA","NFLX","Streaming",39,380,14,
 "World's largest subscription streaming service. ~300 million subscribers globally.",
 "Netflix Originals, licensed content, games, live events, ad-supported tier"),
("Oracle","USA","ORCL","Database & cloud",55,480,160,
 "Enterprise database software and cloud infrastructure, growing fast on AI workloads.",
 "Oracle Database, OCI cloud, Fusion ERP, NetSuite, Cerner health IT"),
("Qualcomm","USA","QCOM","Semiconductors",39,180,51,
 "Designs mobile processors (Snapdragon) and holds foundational wireless patents.",
 "Snapdragon mobile SoCs, CDMA/5G patents, automotive chips, IoT"),
("AMD","USA","AMD","Semiconductors",26,240,26,
 "Designs CPUs (Ryzen, EPYC) and is gaining fast in AI GPU market vs NVIDIA.",
 "EPYC server CPUs, Ryzen consumer CPUs, Instinct MI300X AI GPUs"),
("Boeing","USA","BA","Aerospace & defence",66,100,170,
 "Major commercial aircraft and defence manufacturer. Under scrutiny after 737 MAX quality issues.",
 "737 MAX, 787 Dreamliner, 777X, F-15/F-18 fighters, Space Launch System"),
("Lockheed Martin","USA","LMT","Defence",71,120,122,
 "World's largest defence contractor by revenue.",
 "F-35 Lightning II, missile defence, C-130J Hercules, satellite systems"),
# ---- China ----
("Tencent","CHN","0700.HK","Internet & media",92,400,106,
 "China's largest tech conglomerate. Dominant in gaming, messaging, and digital payments.",
 "WeChat/Weixin, QQ, Honor of Kings, Tencent Cloud, WePay"),
("Alibaba","CHN","BABA","E-commerce & cloud",135,230,240,
 "China's largest e-commerce platform and major cloud provider.",
 "Taobao, Tmall, Alibaba Cloud, AliExpress, Alipay (via Ant Group), Lazada"),
("Tencent Holdings","CHN","0700.HK","Internet",92,400,106,
 "Gaming, social media, and payments giant.",
 "WeChat, QQ, gaming, cloud"),
("PetroChina","CHN","PTR","Oil & gas",490,185,435,
 "China's largest oil and gas company. State-owned.",
 "Upstream E&P, pipelines, refining, petrochemicals, natural gas distribution"),
("China Construction Bank","CHN","0939.HK","Banking",245,220,365,
 "China's second-largest bank by assets.",
 "Corporate lending, retail banking, mortgages, investment banking"),
("BYD","CHN","002594","Electric vehicles",105,108,900,
 "World's largest EV manufacturer by units sold. Also makes batteries and buses.",
 "Han, Atto 3, Seal, Blade Battery, commercial EVs, electric buses"),
("CATL","CHN","300750","Battery technology",52,155,103,
 "World's largest EV battery maker. Supplies Tesla, BMW, Volkswagen and others.",
 "LFP and ternary lithium batteries, sodium-ion cells, battery-swap systems"),
("Meituan","CHN","3690.HK","Consumer internet",42,110,120,
 "China's dominant food delivery and local services platform.",
 "Meituan food delivery, hotel booking, bike-sharing, grocery delivery"),
("NetEase","CHN","NTES","Gaming & internet",15,48,35,
 "China's second-largest gaming company. Also operates email and music services.",
 "Fantasy Westward Journey, Blizzard partnership games (formerly), NetEase Music, Youdao"),
("Xiaomi","CHN","1810.HK","Consumer electronics",47,82,36,
 "Consumer electronics and smartphone maker. Rapidly expanding into EVs.",
 "Redmi/POCO smartphones, MIUI/HyperOS, Xiaomi SU7 EV, smart home devices"),
("JD.com","CHN","JD","E-commerce",137,55,580,
 "China's second-largest e-commerce platform, focused on direct retail and logistics.",
 "JD.com marketplace, JD Logistics, JD Health, JD Industrials"),
("China Mobile","CHN","0941.HK","Telecommunications",147,225,460,
 "World's largest mobile operator by subscribers (~1 billion).",
 "Mobile/5G services, broadband, cloud computing, digital content"),
("CNOOC","CHN","0883.HK","Oil & gas",59,68,25,
 "China's largest offshore oil and gas producer.",
 "Offshore E&P, deepwater platforms, LNG import terminals"),
("Baidu","CHN","BIDU","Internet & AI",20,28,40,
 "China's dominant search engine and AI company.",
 "Baidu Search, Ernie Bot AI, Apollo autonomous driving, Baidu Cloud"),
# ---- Japan ----
("Toyota","JPN","7203.T","Automotive",307,310,375,
 "World's largest automaker by volume. Pioneer of hybrid vehicles (Prius).",
 "Corolla, Camry, Land Cruiser, RAV4, Prius, Lexus, Mirai hydrogen, bZ4X EV"),
("Sony","JPN","6758.T","Entertainment & electronics",88,125,113,
 "Diversified conglomerate spanning gaming, music, film, sensors, and electronics.",
 "PlayStation 5, Sony Pictures, Columbia Records, Alpha cameras, image sensors"),
("SoftBank","JPN","9984.T","Venture capital & telecoms",62,80,80,
 "Telecom and technology investment holding company. Vision Fund has backed hundreds of startups.",
 "SoftBank Mobile (Japan), Vision Fund, Arm Holdings stake, T-Mobile stake"),
("Keyence","JPN","6861.T","Industrial automation",10,103,10,
 "Makes sensors, barcode readers, and industrial automation systems. Known for exceptional margins.",
 "Industrial sensors, vision systems, barcode readers, laser markers, PLCs"),
("Mitsubishi UFJ Financial","JPN","8306.T","Banking",68,118,160,
 "Japan's largest bank by assets, one of the largest in the world.",
 "Corporate banking, retail banking, trust, asset management, US Bank stake"),
("Honda","JPN","7267.T","Automotive & engines",141,60,197,
 "Major automaker and world's largest motorcycle and small engine manufacturer.",
 "Civic, CR-V, Accord, motorcycles, jet engines (HondaJet), power equipment"),
("Nintendo","JPN","7974.T","Gaming",15,63,8,
 "Makes gaming hardware and software. Known for IP longevity (Mario, Zelda, Pokémon).",
 "Nintendo Switch, Mario, Zelda, Pokémon, Donkey Kong"),
("Fast Retailing","JPN","9983.T","Retail — apparel",26,72,56,
 "Operates Uniqlo, the world's third-largest apparel retailer by revenue.",
 "Uniqlo, GU, Theory, J Brand"),
# ---- Germany ----
("SAP","DEU","SAP","Enterprise software",37,230,106,
 "Europe's largest software company. Dominant in ERP for large enterprises.",
 "SAP S/4HANA ERP, SAP Business Suite, Business Technology Platform, SuccessFactors"),
("Volkswagen Group","DEU","VOW3.DE","Automotive",322,72,660,
 "World's second-largest automaker by revenue. Owns VW, Audi, Porsche, Lamborghini, SEAT.",
 "Volkswagen, Audi, Porsche, Lamborghini, Bentley, Skoda, MAN, Traton trucks"),
("Siemens","DEU","SIE.DE","Industrial technology",83,140,320,
 "Industrial conglomerate. Dominant in factory automation, rail, and energy infrastructure.",
 "Factory automation, Siemens Energy, Siemens Healthineers, rail systems, smart buildings"),
("Allianz","DEU","ALV.DE","Insurance",174,110,160,
 "Europe's largest insurance company. Also a major asset manager via PIMCO.",
 "Property & casualty, life insurance, PIMCO asset management, travel insurance"),
("BASF","DEU","BAS.DE","Chemicals",68,38,112,
 "World's largest chemical company by sales.",
 "Specialty chemicals, automotive coatings, agricultural solutions, plastics"),
("BMW","DEU","BMW.DE","Automotive",158,63,154,
 "Premium automotive group. Among the world leaders in luxury and EV transition.",
 "BMW, MINI, Rolls-Royce, BMW i-series EVs, ConnectedDrive"),
("Deutsche Telekom","DEU","DTE.DE","Telecommunications",118,116,290,
 "Europe's largest telecom. Controls T-Mobile US, one of the most valuable assets in telecom.",
 "T-Mobile US, Deutsche Telekom Germany, T-Systems IT services"),
# ---- United Kingdom ----
("AstraZeneca","GBR","AZN","Pharmaceuticals",54,280,92,
 "UK's most valuable company. Fast-growing oncology and rare disease portfolio.",
 "Tagrisso, Imfinzi, Lynparza (cancer), Farxiga (diabetes), COVID vaccine"),
("Shell","GBR","SHEL","Oil & gas",316,220,103,
 "One of the world's largest integrated energy companies. Largest LNG trader.",
 "Upstream E&P, LNG, fuel retail, Shell Energy renewables, chemicals"),
("HSBC","GBR","HSBA.L","Banking",65,160,220,
 "World's largest trade-finance bank. Heavily focused on Asia.",
 "Trade finance, retail banking (Asia), wealth management, commercial banking"),
("Unilever","GBR","ULVR.L","Consumer goods",62,130,128,
 "One of the world's largest consumer goods companies. 400+ brands across 190 countries.",
 "Dove, Hellmann's, Knorr, Lipton, Magnum, Rexona, Ben & Jerry's, Domestos"),
("BP","GBR","BP.L","Oil & gas",194,82,90,
 "Integrated oil major pivoting toward lower-carbon energy.",
 "Upstream E&P, BP fuels, Castrol lubricants, offshore wind, electric charging"),
("Diageo","GBR","DGE.L","Beverages",20,62,28,
 "World's largest premium spirits company.",
 "Johnnie Walker, Guinness, Smirnoff, Baileys, Tanqueray, Crown Royal"),
("Rio Tinto","GBR","RIO","Mining",54,110,57,
 "One of the world's largest mining companies. Australia is a major operating base.",
 "Iron ore (Pilbara), copper, aluminium, lithium (Rincon)"),
# ---- France ----
("LVMH","FRA","MC.PA","Luxury goods",90,290,213,
 "World's largest luxury goods group. 75 houses across fashion, spirits, watches, beauty.",
 "Louis Vuitton, Dior, Moët & Chandon, Hennessy, Bulgari, Sephora, TAG Heuer"),
("TotalEnergies","FRA","TTE","Oil & gas",218,155,105,
 "Integrated energy company with a large renewables pipeline alongside oil and gas.",
 "Upstream E&P, Total fuels, LNG, solar (Sunpower), offshore wind"),
("Hermès","FRA","RMS.PA","Luxury goods",15,220,23,
 "Ultra-premium luxury house known for scarcity and craftsmanship.",
 "Birkin/Kelly bags, silk scarves, Hermès home, watches, perfumes"),
("Sanofi","FRA","SAN.PA","Pharmaceuticals",50,140,91,
 "One of Europe's largest pharmaceutical companies.",
 "Dupixent (immunology), Vaccines (Sanofi Pasteur), Lovenox, Plavix"),
("L'Oréal","FRA","OR.PA","Beauty & cosmetics",46,210,88,
 "World's largest beauty company. 36 international brands.",
 "L'Oréal Paris, Lancôme, Garnier, Maybelline, Kérastase, CeraVe, La Roche-Posay"),
# ---- South Korea ----
("Samsung Electronics","KOR","005930.KS","Consumer electronics & semiconductors",230,280,270,
 "World's largest smartphone maker and memory chipmaker. Also makes OLED displays and appliances.",
 "Galaxy smartphones, NAND flash, DRAM, OLED displays, home appliances, foundry (TSMC rival)"),
("SK Hynix","KOR","000660.KS","Semiconductors",36,115,36,
 "World's second-largest memory chipmaker. Major HBM supplier for AI accelerators.",
 "DRAM, NAND flash, HBM3E (for NVIDIA H100), SSD controllers"),
("Hyundai Motor","KOR","005380.KS","Automotive",166,50,120,
 "South Korea's largest automaker. Parent of Kia and Genesis luxury brand.",
 "Hyundai Sonata, Tucson, Ioniq 5/6 EVs, Kia, Genesis, hydrogen fuel cells"),
("LG Electronics","KOR","066570.KS","Consumer electronics",60,15,74,
 "Makes TVs, home appliances, and EV components. World-leading OLED TV maker.",
 "OLED TVs, home appliances, EV powertrains (via LG Magna), monitors"),
("POSCO Holdings","KOR","005490.KS","Steel & materials",71,18,41,
 "One of the world's largest steel producers. Expanding into battery materials.",
 "Steel products, lithium (from brine), nickel refining, cathode materials"),
# ---- Taiwan ----
("TSMC","TWN","TSM","Semiconductors (foundry)",87,1000,78,
 "World's only producer of cutting-edge chips below 3nm. Makes chips for Apple, NVIDIA, AMD.",
 "3nm, 2nm chip fabrication, advanced packaging (CoWoS), TSMC Arizona fabs"),
# ---- India ----
("Reliance Industries","IND","RELIANCE.NS","Conglomerate",110,228,240,
 "India's most valuable company. Oil refining, telecom (Jio), and retail.",
 "Jio telecom, Reliance Retail, refining, petrochemicals, new energy"),
("Tata Consultancy Services","IND","TCS.NS","IT services",30,175,613,
 "India's largest IT services company. Serves clients in 50+ countries.",
 "IT outsourcing, digital transformation, cloud migration, AI/ML services"),
("Infosys","IND","INFY","IT services",18,82,343,
 "India's second-largest IT services company.",
 "IT consulting, BPO, digital services, AI platform (Topaz)"),
("HDFC Bank","IND","HDFCBANK.NS","Banking",28,140,213,
 "India's largest private bank by market cap.",
 "Retail banking, home loans, credit cards, wholesale banking"),
("Wipro","IND","WIPRO.NS","IT services",11,28,234,
 "Indian IT services and consulting company.",
 "IT outsourcing, cloud, cybersecurity, digital engineering"),
# ---- Netherlands ----
("ASML","NLD","ASML","Semiconductor equipment",28,290,43,
 "Sole manufacturer of EUV lithography machines. Without ASML, no advanced chips exist.",
 "EUV lithography, DUV systems, installed base service — a global chokepoint"),
# ---- Switzerland ----
("Nestlé","CHE","NESN.SW","Food & beverages",92,260,270,
 "World's largest food and beverage company.",
 "Nescafé, KitKat, Purina pet food, Maggi, Milo, Häagen-Dazs, Perrier"),
("Roche","CHE","ROG.SW","Pharmaceuticals & diagnostics",67,208,101,
 "Leader in oncology drugs and diagnostics. Also makes up a third of world's cancer tests.",
 "Cancer drugs (Herceptin, Avastin, Tecentriq), PCR diagnostics, Genentech"),
("Novartis","CHE","NOVN.SW","Pharmaceuticals",50,248,78,
 "Major Swiss pharma. Focus on innovative medicines after spinning off generics (Sandoz).",
 "Cosentyx, Entresto, Kesimpta, Zolgensma (gene therapy), radioligand therapy"),
# ---- Canada ----
("Shopify","CAN","SHOP","E-commerce software",9,140,12,
 "Commerce platform powering 4 million+ merchants globally.",
 "Shopify storefront, Payments, Shipping, POS, Shopify Audiences, Shop app"),
("Royal Bank of Canada","CAN","RY","Banking",59,190,100,
 "Canada's largest bank by market cap.",
 "RBC retail & commercial banking, capital markets, wealth management, City National (US)"),
("Brookfield Asset Management","CAN","BAM","Alternative assets",5,90,15,
 "Major global alternative asset manager with strength in real assets.",
 "Private equity, infrastructure, real estate, credit, renewable energy"),
# ---- Australia ----
("BHP Group","AUS","BHP","Mining",55,130,80,
 "World's largest mining company by market cap. Major iron ore, copper, and potash producer.",
 "Iron ore (Pilbara), copper (Escondida), potash (Jansen), nickel, coal"),
# ---- Saudi Arabia ----
("Saudi Aramco","SAU","2222.SR","Oil & gas",440,1700,72,
 "World's largest oil company by production and profit. The Saudi state owns ~98%.",
 "Crude oil production (~12m barrels/day), refining, petrochemicals, Aramco Trading"),
# ---- Brazil ----
("Petrobras","BRA","PETR4.SA","Oil & gas",126,80,45,
 "Brazil's state-controlled oil company. One of the most profitable in Latin America.",
 "Deepwater pre-salt oil, refining, natural gas, fertilisers"),
("Vale","BRA","VALE3.SA","Mining",45,48,70,
 "World's largest iron ore and nickel producer.",
 "Iron ore (Carajás), nickel, copper, cobalt, manganese"),
# ---- Norway ----
("Equinor","NOR","EQNR","Oil & gas",98,72,22,
 "Norway's state energy company. One of the world's largest offshore wind developers.",
 "North Sea oil & gas, Empire Wind/Dogger Bank offshore wind, Hywind floating wind"),
]

# deduplicate by name (ExxonMobil appears twice in the list above)
seen = set()
CORPS_CLEAN = []
for c in CORPS:
    if c[0] not in seen:
        seen.add(c[0])
        CORPS_CLEAN.append(c)
CORPS = CORPS_CLEAN

print(f"Total: {len(CORPS)} corporations")
