# -*- coding: utf-8 -*-
"""
Phase 4: trade flows & supply chain.
- exports/imports: goods + services, USD bn, latest full year
- top_export: dominant export category (broad classification)
- lpi: World Bank Logistics Performance Index, 1-5 (2023 edition, published irregularly)
- partners: principal trading partners
Absence = not compiled. Rendered honestly.
"""

# iso3: (exports_usd_bn, imports_usd_bn, top_export, lpi, "partner1, partner2, partner3")
TRADE = {
"CHN":(3700,2600,"Electronics & machinery",3.7,"United States, Hong Kong, Japan"),
"USA":(3050,3900,"Refined petroleum, aircraft, services",3.8,"Canada, Mexico, China"),
"DEU":(2100,1750,"Motor vehicles & machinery",4.1,"United States, France, Netherlands"),
"GBR":(1100,1050,"Financial & business services",3.7,"United States, Germany, Netherlands"),
"FRA":(1000,1050,"Aircraft, machinery, wine",3.9,"Germany, Italy, Belgium"),
"JPN":(920,900,"Motor vehicles & machinery",3.9,"China, United States, South Korea"),
"NLD":(950,850,"Machinery, refined petroleum (re-export hub)",4.1,"Germany, Belgium, France"),
"SGP":(840,730,"Refined petroleum & electronics",4.3,"China, Malaysia, United States"),
"IND":(800,900,"Refined petroleum, IT services, pharmaceuticals",3.4,"United States, UAE, China"),
"ITA":(780,720,"Machinery, pharmaceuticals, fashion",3.7,"Germany, United States, France"),
"KOR":(770,730,"Semiconductors & motor vehicles",3.8,"China, United States, Vietnam"),
"IRL":(750,530,"Pharmaceuticals & medical devices",3.6,"United States, Germany, Belgium"),
"HKG":(700,680,"Electronics (re-export hub)",4.0,"China, United States, India"),
"CAN":(700,690,"Crude petroleum & motor vehicles",4.0,"United States, China, United Kingdom"),
"CHE":(660,570,"Gold, pharmaceuticals, watches",4.1,"Germany, United States, China"),
"MEX":(630,650,"Motor vehicles & electronics",3.3,"United States, Canada, China"),
"ARE":(600,470,"Crude petroleum & gold",4.0,"India, Saudi Arabia, China"),
"ESP":(600,620,"Motor vehicles, food, tourism",3.9,"France, Germany, Italy"),
"BEL":(600,580,"Chemicals & pharmaceuticals",4.0,"Germany, France, Netherlands"),
"TWN":(580,470,"Semiconductors",3.7,"China, United States, Japan"),
"RUS":(470,320,"Crude petroleum & natural gas",2.6,"China, India, Turkey"),
"POL":(450,440,"Machinery & motor vehicles",3.6,"Germany, Czechia, France"),
"AUS":(410,380,"Iron ore, coal, natural gas",3.7,"China, Japan, South Korea"),
"VNM":(400,380,"Electronics & textiles",3.3,"United States, China, South Korea"),
"BRA":(380,320,"Soybeans, iron ore, crude petroleum",3.2,"China, United States, Argentina"),
"THA":(380,360,"Motor vehicles & electronics",3.5,"United States, China, Japan"),
"TUR":(340,390,"Motor vehicles & machinery",3.4,"Germany, United States, Iraq"),
"SAU":(330,220,"Crude petroleum",3.7,"China, India, Japan"),
"MYS":(330,300,"Electronics & palm oil",3.6,"Singapore, China, United States"),
"AUT":(300,300,"Machinery & motor vehicles",4.0,"Germany, United States, Italy"),
"IDN":(290,260,"Coal, palm oil, nickel",3.0,"China, United States, Japan"),
"SWE":(290,280,"Machinery, motor vehicles, paper",4.0,"Germany, Norway, United States"),
"CZE":(250,235,"Motor vehicles & machinery",3.5,"Germany, Slovakia, Poland"),
"DNK":(250,220,"Pharmaceuticals & machinery",4.1,"Germany, Sweden, United States"),
"NOR":(190,140,"Crude petroleum & natural gas",3.9,"United Kingdom, Germany, Netherlands"),
"HUN":(170,165,"Motor vehicles & electronics",3.4,"Germany, Slovakia, Italy"),
"ISR":(160,140,"Diamonds, electronics, pharmaceuticals",3.4,"United States, China, India"),
"PRT":(140,150,"Machinery, textiles, tourism",3.4,"Spain, France, Germany"),
"PHL":(130,150,"Electronics & business services",3.3,"United States, Japan, China"),
"ROU":(130,145,"Motor vehicles & machinery",3.2,"Germany, Italy, France"),
"QAT":(130,55,"Liquefied natural gas",3.7,"China, India, South Korea"),
"ZAF":(130,125,"Platinum, gold, motor vehicles",3.7,"China, United States, Germany"),
"SVK":(110,105,"Motor vehicles & electronics",3.3,"Germany, Czechia, Poland"),
"GRC":(110,110,"Refined petroleum & tourism",3.2,"Italy, Germany, Cyprus"),
"FIN":(110,110,"Paper, machinery, refined petroleum",4.2,"Germany, Sweden, United States"),
"CHL":(110,95,"Copper",3.3,"China, United States, Japan"),
"ARG":(100,85,"Soybeans, corn, beef",2.9,"Brazil, China, United States"),
"KWT":(85,45,"Crude petroleum",3.2,"China, India, South Korea"),
"PER":(75,65,"Copper & gold",2.9,"China, United States, India"),
"COL":(65,80,"Crude petroleum & coffee",2.9,"United States, China, Panama"),
"NZL":(55,55,"Dairy & meat",3.5,"China, Australia, United States"),
"NGA":(55,60,"Crude petroleum",2.6,"India, Spain, Netherlands"),
"BGD":(55,75,"Garments",2.6,"United States, Germany, United Kingdom"),
"EGY":(50,90,"Refined petroleum, natural gas, fruit",3.0,"Turkey, Italy, United States"),
"KAZ":(80,60,"Crude petroleum & uranium",2.7,"China, Italy, Russia"),
"IRQ":(95,55,"Crude petroleum",2.4,"China, India, South Korea"),
"PAK":(40,60,"Textiles & rice",2.9,"United States, China, United Kingdom"),
"DZA":(60,50,"Crude petroleum & natural gas",2.5,"Italy, France, Spain"),
"UKR":(45,60,"Grain & sunflower oil",2.8,"Poland, Turkey, Romania"),
"MAR":(50,70,"Motor vehicles, phosphates, fertiliser",2.8,"Spain, France, Italy"),
"BGR":(55,60,"Refined petroleum & copper",3.0,"Germany, Romania, Italy"),
"HRV":(40,45,"Tourism, machinery, ships",3.0,"Italy, Germany, Slovenia"),
"SVN":(60,58,"Motor vehicles & pharmaceuticals",3.4,"Germany, Italy, Croatia"),
"LTU":(55,55,"Refined petroleum & furniture",3.4,"Germany, Poland, Latvia"),
"LVA":(28,30,"Timber & food",3.1,"Lithuania, Estonia, Germany"),
"EST":(28,30,"Electronics & timber",3.3,"Finland, Sweden, Latvia"),
"LUX":(160,150,"Financial services & steel",3.7,"Germany, France, Belgium"),
"BLR":(45,45,"Fertiliser & machinery",2.6,"Russia, Ukraine, China"),
"UZB":(25,35,"Gold, natural gas, cotton",2.6,"China, Russia, Kazakhstan"),
"AZE":(30,20,"Crude petroleum & natural gas",2.7,"Italy, Turkey, Israel"),
"OMN":(65,40,"Crude petroleum & LNG",3.2,"China, India, South Korea"),
"BHR":(25,20,"Refined petroleum & aluminium",3.3,"Saudi Arabia, UAE, United States"),
"JOR":(15,25,"Fertiliser & textiles",2.7,"United States, Saudi Arabia, India"),
"LBN":(5,15,"Jewellery & food",2.5,"UAE, Switzerland, Turkey"),
"TUN":(20,25,"Textiles & electrical",2.6,"France, Italy, Germany"),
"LBY":(30,20,"Crude petroleum",2.2,"Italy, Spain, Germany"),
"ETH":(10,20,"Coffee & gold",2.4,"China, United States, Saudi Arabia"),
"KEN":(12,22,"Tea, flowers, coffee",3.0,"Uganda, United States, Netherlands"),
"TZA":(14,16,"Gold & cashews",2.6,"India, UAE, China"),
"UGA":(8,12,"Coffee & gold",2.6,"UAE, Kenya, South Sudan"),
"GHA":(20,18,"Gold, cocoa, crude petroleum",2.6,"Switzerland, India, China"),
"CIV":(18,16,"Cocoa & cashews",2.6,"Netherlands, United States, Mali"),
"SEN":(8,12,"Gold, refined petroleum, fish",2.7,"Mali, Switzerland, India"),
"CMR":(7,9,"Crude petroleum & cocoa",2.5,"China, Netherlands, Italy"),
"AGO":(40,25,"Crude petroleum",2.3,"China, India, UAE"),
"ZMB":(12,10,"Copper",2.6,"Switzerland, China, DR Congo"),
"COD":(25,20,"Copper & cobalt",2.2,"China, UAE, Zambia"),
"BWA":(7,8,"Diamonds",2.7,"UAE, India, Belgium"),
"NAM":(6,8,"Diamonds & uranium",2.7,"China, South Africa, Botswana"),
"MOZ":(8,10,"Aluminium & coal",2.4,"India, South Africa, China"),
"ZWE":(7,9,"Gold & tobacco",2.4,"UAE, South Africa, China"),
"MUS":(5,7,"Textiles & sugar",3.0,"France, United States, South Africa"),
"MNG":(15,12,"Copper & coal",2.5,"China, Switzerland, Singapore"),
"LKA":(16,20,"Textiles & tea",2.8,"United States, United Kingdom, India"),
"NPL":(2,12,"Textiles & carpets",2.4,"India, United States, Germany"),
"MMR":(18,17,"Natural gas & garments",2.4,"China, Thailand, Japan"),
"KHM":(25,28,"Garments & footwear",2.7,"United States, Vietnam, Japan"),
"LAO":(8,8,"Electricity & copper",2.4,"Thailand, China, Vietnam"),
"BRN":(10,7,"Crude petroleum & LNG",2.7,"Japan, Singapore, Australia"),
"PNG":(12,6,"LNG, gold, copper",2.4,"China, Australia, Japan"),
"FJI":(2,3,"Tourism, sugar, fish",2.6,"United States, Australia, New Zealand"),
"URY":(15,13,"Beef, soybeans, cellulose",3.0,"China, Brazil, United States"),
"PRY":(15,14,"Soybeans & beef",2.6,"Brazil, Argentina, Chile"),
"BOL":(12,11,"Natural gas, zinc, gold",2.5,"Brazil, Argentina, India"),
"ECU":(35,30,"Crude petroleum, bananas, shrimp",2.6,"United States, China, Panama"),
"VEN":(15,10,"Crude petroleum",2.2,"China, India, Spain"),
"CRI":(25,22,"Medical devices & bananas",3.0,"United States, Netherlands, Guatemala"),
"PAN":(30,28,"Re-export & canal services",3.2,"United States, China, Ecuador"),
"GTM":(18,25,"Coffee, sugar, bananas",2.6,"United States, El Salvador, Honduras"),
"DOM":(25,28,"Medical devices, gold, cigars",2.6,"United States, Switzerland, Canada"),
"JAM":(5,8,"Alumina & bauxite",2.7,"United States, Netherlands, Canada"),
"TTO":(12,8,"LNG & petrochemicals",2.8,"United States, Guyana, Argentina"),
"GUY":(18,8,"Crude petroleum & gold",2.5,"Panama, United States, Netherlands"),
"ISL":(15,13,"Fish & aluminium",3.2,"Netherlands, United Kingdom, Spain"),
"CYP":(30,28,"Shipping & tourism services",3.0,"Greece, United Kingdom, Israel"),
"MLT":(25,23,"Electronics & gaming services",3.0,"Germany, France, Italy"),
"SRB":(35,38,"Motor vehicles & machinery",2.9,"Germany, Italy, Bosnia"),
"ALB":(6,9,"Textiles & minerals",2.7,"Italy, Spain, Germany"),
"MKD":(9,11,"Catalysts & motor parts",2.7,"Germany, Serbia, Bulgaria"),
"BIH":(10,13,"Metals & furniture",2.7,"Germany, Croatia, Serbia"),
"GEO":(8,13,"Copper & motor vehicle re-export",2.8,"China, Bulgaria, Armenia"),
"ARM":(9,11,"Gold, copper, brandy",2.6,"Russia, UAE, China"),
"MDA":(5,10,"Sunflower & wine",2.6,"Romania, Ukraine, Italy"),
"KGZ":(4,10,"Gold",2.5,"Russia, Kazakhstan, Turkey"),
"TJK":(3,6,"Aluminium & cotton",2.4,"Kazakhstan, Turkey, Switzerland"),
"TKM":(12,5,"Natural gas",2.4,"China, Turkey, Russia"),
"AFG":(2,7,"Fruit & carpets",1.9,"Pakistan, India, UAE"),
"IRN":(80,60,"Crude petroleum & petrochemicals",2.5,"China, UAE, Turkey"),
"YEM":(2,8,"Crude petroleum & fish",2.0,"China, Thailand, UAE"),
"SDN":(5,8,"Gold & livestock",2.1,"UAE, Saudi Arabia, Egypt"),
}
