# -*- coding: utf-8 -*-
"""
Phase 7: bank CEOs. Tier 3 (live, verify) — CEOs change, sometimes abruptly.
Keyed EXACTLY as bank names appear in data.BANKS (validated against that list —
a bank not present here either lacks a confirmable current CEO or is not itself
in the 248-bank dataset; neither case is guessed).
"""

CEO = {
"JPMorgan Chase":"Jamie Dimon",
"Bank of America":"Brian Moynihan",
"Citigroup":"Jane Fraser",
"Wells Fargo":"Charles Scharf",
"Goldman Sachs":"David Solomon",
"Morgan Stanley":"Ted Pick",
"Industrial and Commercial Bank of China":"Liu Jun",
"China Construction Bank":"Zhang Yi",
"Agricultural Bank of China":"Xie Guangqi",
"Bank of China":"Lin Jingzhen",
"HSBC Holdings":"Georges Elhedery",
"BNP Paribas":"Jean-Laurent Bonnafe",
"Mitsubishi UFJ Financial Group":"Junichi Hanzawa",
"Sumitomo Mitsui Financial Group":"Toru Nakashima",
"Mizuho Financial Group":"Masahiro Kihara",
"Deutsche Bank":"Christian Sewing",
"Barclays":"C. S. Venkatakrishnan",
"UBS Group":"Sergio Ermotti",
"Banco Santander":"Hector Grisi",
"Royal Bank of Canada":"Dave McKay",
"Toronto-Dominion Bank":"Raymond Chun",
"Standard Chartered":"Bill Winters",
"Credit Agricole":"Philippe Brassac",
"Societe Generale":"Slawomir Krupa",
"ING Group":"Steven van Rijswijk",
"UniCredit":"Andrea Orcel",
"Intesa Sanpaolo":"Carlo Messina",
"Lloyds Banking Group":"Charlie Nunn",
"Nordea Bank":"Frank Vang-Jensen",
"DBS Group":"Tan Su Shan",
"OCBC Bank":"Helen Wong",
"United Overseas Bank":"Wee Ee Cheong",
"State Bank of India":"C. S. Setty",
"HDFC Bank":"Sashidhar Jagdishan",
"ICICI Bank":"Sandeep Bakhshi",
"Itau Unibanco":"Milton Maluhy Filho",
"Banco do Brasil":"Tarciana Medeiros",
"Commonwealth Bank of Australia":"Matt Comyn",
"Westpac Banking Corp":"Anthony Miller",
"National Australia Bank":"Andrew Irvine",
"ANZ Group":"Nuno Matos",
"Qatar National Bank":"Abdulla Mubarak Al-Khalifa",
"First Abu Dhabi Bank":"Hana Al Rostamani",
"Emirates NBD":"Shayne Nelson",
"Saudi National Bank":"Said Al Ghamdi",
"Standard Bank Group":"Sim Tshabalala",
"Absa Group":"Kenny Fihla",
"KB Financial Group":"Yang Jong-hee",
"Shinhan Financial Group":"Jin Ok-dong",
"Grupo Financiero Banorte":"Marcos Ramirez",
"PKO Bank Polski":"Szymon Midera",
"Erste Group Bank":"Peter Bosek",
"KBC Group":"Johan Thijs",
"Danske Bank":"Carsten Egeriis",
"SEB":"Johan Torgeby",
"Swedbank":"Jens Henriksson",
"DNB Bank":"Kjerstin Braathen",
"Raiffeisen Bank International":"Johann Strobl",
"Maybank":"Khairussaleh Ramli",
"Vietcombank":"Nguyen Thanh Tung",
"Bank Mandiri":"Darmawan Junaidi",
"Bank Central Asia":"Jahja Setiaatmadja",
"CTBC Financial":"Daniel Wu",
}
