# -*- coding: utf-8 -*-
"""
Phase 6: political layer — leaders, government type, bloc memberships.
LEADERS are Tier 3 (live, verify) — they change, sometimes suddenly, and there is
no authoritative feed. Each carries an "as of" date. Verified against 2026 sources
(G7 summit roster, current heads-of-state lists) July 2026.
BLOCS and GOV_TYPE are factual/stable.

Deliberately NOT included: informal "alliances" — contested, unsourceable, editorial.
Only formal treaty/economic bloc membership, which is a matter of record.
"""

# iso3: (head_of_state_or_gov, title, "as of" note)
# For parliamentary systems the effective leader (PM/Chancellor) is given.
LEADER = {
"USA":("Donald Trump","President","2025"),
"CHN":("Xi Jinping","President / Party General Secretary","2013"),
"JPN":("Sanae Takaichi","Prime Minister","2025"),
"DEU":("Friedrich Merz","Chancellor","2025"),
"IND":("Narendra Modi","Prime Minister","2014"),
"GBR":("Keir Starmer","Prime Minister","2024"),
"FRA":("Emmanuel Macron","President","2017"),
"ITA":("Giorgia Meloni","Prime Minister","2022"),
"CAN":("Mark Carney","Prime Minister","2025"),
"BRA":("Luiz Inacio Lula da Silva","President","2023"),
"RUS":("Vladimir Putin","President","2012"),
"KOR":("Lee Jae Myung","President","2025"),
"MEX":("Claudia Sheinbaum","President","2024"),
"ESP":("Pedro Sanchez","Prime Minister","2018"),
"AUS":("Anthony Albanese","Prime Minister","2022"),
"IDN":("Prabowo Subianto","President","2024"),
"TUR":("Recep Tayyip Erdogan","President","2014"),
"NLD":("Dick Schoof","Prime Minister","2024"),
"SAU":("Mohammed bin Salman","Crown Prince & PM","2022"),
"CHE":("Federal Council (rotating)","Federal Council","collective"),
"POL":("Donald Tusk","Prime Minister","2023"),
"BEL":("Bart De Wever","Prime Minister","2025"),
"ARG":("Javier Milei","President","2023"),
"SWE":("Ulf Kristersson","Prime Minister","2022"),
"IRL":("Micheal Martin","Taoiseach","2025"),
"ARE":("Mohamed bin Zayed Al Nahyan","President","2022"),
"SGP":("Lawrence Wong","Prime Minister","2024"),
"AUT":("Christian Stocker","Chancellor","2025"),
"ISR":("Benjamin Netanyahu","Prime Minister","2022"),
"THA":("Anutin Charnvirakul","Prime Minister","2025"),
"NOR":("Jonas Gahr Store","Prime Minister","2021"),
"PHL":("Ferdinand Marcos Jr.","President","2022"),
"VNM":("Luong Cuong","President","2024"),
"MYS":("Anwar Ibrahim","Prime Minister","2022"),
"BGD":("Muhammad Yunus","Chief Adviser (interim)","2024"),
"DNK":("Mette Frederiksen","Prime Minister","2019"),
"IRN":("Masoud Pezeshkian","President","2024"),
"EGY":("Abdel Fattah el-Sisi","President","2014"),
"PAK":("Shehbaz Sharif","Prime Minister","2024"),
"ZAF":("Cyril Ramaphosa","President","2018"),
"NGA":("Bola Tinubu","President","2023"),
"UKR":("Volodymyr Zelensky","President","2019"),
"COL":("Gustavo Petro","President","2022"),
"CHL":("Gabriel Boric","President","2022"),
"KEN":("William Ruto","President","2022"),
"SYR":("Ahmed al-Sharaa","President","2025"),
"PER":("Jose Jeri","President","2025"),
"VEN":("Nicolas Maduro","President","2013"),
"ETH":("Abiy Ahmed","Prime Minister","2018"),
"QAT":("Tamim bin Hamad Al Thani","Emir","2013"),
"KWT":("Mishal Al-Ahmad Al-Jaber Al-Sabah","Emir","2023"),
"HUN":("Peter Magyar","Prime Minister","2026"),
"GRC":("Kyriakos Mitsotakis","Prime Minister","2019"),
"PRT":("Luis Montenegro","Prime Minister","2024"),
"CZE":("Andrej Babis","Prime Minister","2025"),
"NZL":("Christopher Luxon","Prime Minister","2023"),
"IRQ":("Mohammed Shia al-Sudani","Prime Minister","2022"),
"MAR":("Aziz Akhannouch","Prime Minister","2021"),
"DZA":("Abdelmadjid Tebboune","President","2019"),
"CUB":("Miguel Diaz-Canel","President","2019"),
"PRK":("Kim Jong Un","Supreme Leader","2011"),
}

# Government type (CIA World Factbook classification, stable)
GOV_TYPE = {
"USA":"Federal presidential republic","CHN":"One-party socialist republic",
"JPN":"Parliamentary constitutional monarchy","DEU":"Federal parliamentary republic",
"IND":"Federal parliamentary republic","GBR":"Parliamentary constitutional monarchy",
"FRA":"Semi-presidential republic","ITA":"Parliamentary republic",
"CAN":"Federal parliamentary constitutional monarchy","BRA":"Federal presidential republic",
"RUS":"Federal semi-presidential republic","KOR":"Presidential republic",
"MEX":"Federal presidential republic","ESP":"Parliamentary constitutional monarchy",
"AUS":"Federal parliamentary constitutional monarchy","IDN":"Presidential republic",
"TUR":"Presidential republic","NLD":"Parliamentary constitutional monarchy",
"SAU":"Absolute monarchy","CHE":"Federal directorial republic","POL":"Parliamentary republic",
"BEL":"Federal parliamentary constitutional monarchy","ARG":"Federal presidential republic",
"SWE":"Parliamentary constitutional monarchy","IRL":"Parliamentary republic",
"ARE":"Federal absolute monarchy","SGP":"Parliamentary republic","AUT":"Federal parliamentary republic",
"ISR":"Parliamentary republic","THA":"Parliamentary constitutional monarchy",
"NOR":"Parliamentary constitutional monarchy","PHL":"Presidential republic",
"VNM":"One-party socialist republic","MYS":"Federal parliamentary constitutional monarchy",
"BGD":"Parliamentary republic","DNK":"Parliamentary constitutional monarchy",
"IRN":"Islamic republic (theocratic)","EGY":"Presidential republic",
"PAK":"Federal parliamentary republic","ZAF":"Parliamentary republic",
"NGA":"Federal presidential republic","UKR":"Semi-presidential republic",
"COL":"Presidential republic","CHL":"Presidential republic","KEN":"Presidential republic",
"SYR":"Transitional government","PER":"Presidential republic","VEN":"Federal presidential republic",
"ETH":"Federal parliamentary republic","QAT":"Absolute monarchy","KWT":"Constitutional monarchy (emirate)",
"HUN":"Parliamentary republic","GRC":"Parliamentary republic","PRT":"Semi-presidential republic",
"CZE":"Parliamentary republic","NZL":"Parliamentary constitutional monarchy",
"IRQ":"Federal parliamentary republic","MAR":"Parliamentary constitutional monarchy",
"DZA":"Presidential republic","CUB":"One-party socialist republic","PRK":"One-party state",
}

# Formal bloc / treaty-organisation membership. Factual, defined.
# Codes: G7, G20, EU, NATO, BRICS, ASEAN, OPEC, OPEC+, USMCA, AU, MERCOSUR,
#        GCC, OECD, CIS, EAEU, Commonwealth
BLOCS = {
"USA":["G7","G20","NATO","USMCA","OECD"],
"CHN":["G20","BRICS"],
"JPN":["G7","G20","OECD"],
"DEU":["G7","G20","EU","NATO","OECD"],
"IND":["G20","BRICS","Commonwealth"],
"GBR":["G7","G20","NATO","OECD","Commonwealth"],
"FRA":["G7","G20","EU","NATO","OECD"],
"ITA":["G7","G20","EU","NATO","OECD"],
"CAN":["G7","G20","NATO","USMCA","OECD","Commonwealth"],
"BRA":["G20","BRICS","MERCOSUR"],
"RUS":["G20","BRICS","EAEU","CIS"],
"KOR":["G20","OECD"],
"MEX":["G20","USMCA","OECD"],
"ESP":["G20","EU","NATO","OECD"],
"AUS":["G20","OECD","Commonwealth"],
"IDN":["G20","ASEAN","BRICS"],
"TUR":["G20","NATO","OECD"],
"NLD":["EU","NATO","OECD"],
"SAU":["G20","OPEC","OPEC+","GCC","BRICS"],
"CHE":["OECD"],
"POL":["G20-guest","EU","NATO","OECD"],
"BEL":["EU","NATO","OECD"],
"ARG":["G20","MERCOSUR"],
"SWE":["EU","NATO","OECD"],
"IRL":["EU","OECD"],
"ARE":["OPEC","OPEC+","GCC","BRICS"],
"SGP":["ASEAN"],
"AUT":["EU","OECD"],
"ISR":["OECD"],
"THA":["ASEAN"],
"NOR":["NATO","OECD"],
"PHL":["ASEAN"],
"VNM":["ASEAN"],
"MYS":["ASEAN"],
"BGD":["Commonwealth"],
"DNK":["EU","NATO","OECD"],
"IRN":["BRICS","OPEC"],
"EGY":["BRICS","AU"],
"PAK":["Commonwealth"],
"ZAF":["G20","BRICS","AU","Commonwealth"],
"NGA":["AU","OPEC","Commonwealth"],
"UKR":["CIS-former"],
"COL":["OECD"],
"CHL":["OECD","MERCOSUR-assoc"],
"KEN":["AU","Commonwealth"],
"SYR":["AU-observer"],
"PER":["OECD-accession"],
"VEN":["OPEC","MERCOSUR-suspended"],
"ETH":["BRICS","AU"],
"QAT":["GCC","OPEC-former"],
"KWT":["OPEC","OPEC+","GCC"],
"HUN":["EU","NATO","OECD"],
"GRC":["EU","NATO","OECD"],
"PRT":["EU","NATO","OECD"],
"CZE":["EU","NATO","OECD"],
"NZL":["OECD","Commonwealth"],
"IRQ":["OPEC","AU-none"],
"MAR":["AU"],
"DZA":["OPEC","AU","BRICS-partner"],
"CUB":[],
"PRK":[],
# EU/NATO/etc members without individual leader entries still get blocs
"FIN":["EU","NATO","OECD"],"SVK":["EU","NATO","OECD"],"SVN":["EU","NATO","OECD"],
"LTU":["EU","NATO","OECD"],"LVA":["EU","NATO","OECD"],"EST":["EU","NATO","OECD"],
"LUX":["EU","NATO","OECD"],"HRV":["EU","NATO","OECD"],"BGR":["EU","NATO"],
"ROU":["EU","NATO"],"CYP":["EU"],"MLT":["EU"],
"OMN":["GCC","OPEC+"],"BHR":["GCC"],"ISL":["NATO","OECD"],
"COD":["AU"],"AGO":["AU","OPEC-former"],"GHA":["AU","Commonwealth"],
"TZA":["AU","Commonwealth"],"UGA":["AU","Commonwealth"],"CIV":["AU"],
"SEN":["AU"],"CMR":["AU","Commonwealth"],"ZMB":["AU","Commonwealth"],
"ZWE":["AU","Commonwealth-former"],"BWA":["AU","Commonwealth"],"NAM":["AU","Commonwealth"],
"MOZ":["AU","Commonwealth"],"URY":["MERCOSUR","OECD-accession"],"PRY":["MERCOSUR"],
"BOL":["MERCOSUR","OPEC-none"],"ECU":["OPEC-former"],"LBY":["OPEC","AU"],
}

# For parliamentary/dual-executive systems: (ceremonial head of state, their title)
# shown ALONGSIDE the head of government already in LEADER. Verified mid-2026.
HEAD_OF_STATE = {
"IND":("Droupadi Murmu","President"),
"GBR":("King Charles III","Monarch"),
"CAN":("King Charles III (rep. by Governor General)","Monarch"),
"AUS":("King Charles III (rep. by Governor General)","Monarch"),
"NZL":("King Charles III (rep. by Governor General)","Monarch"),
"JPN":("Emperor Naruhito","Emperor"),
"DEU":("Frank-Walter Steinmeier","President"),
"ITA":("Sergio Mattarella","President"),
"ISR":("Isaac Herzog","President"),
"IRL":("Michael D. Higgins","President"),
"SGP":("Tharman Shanmugaratnam","President"),
"ZAF":("Cyril Ramaphosa","President (also head of govt)"),
"NLD":("King Willem-Alexander","Monarch"),
"BEL":("King Philippe","Monarch"),
"ESP":("King Felipe VI","Monarch"),
"SWE":("King Carl XVI Gustaf","Monarch"),
"NOR":("King Harald V","Monarch"),
"DNK":("King Frederik X","Monarch"),
"THA":("King Vajiralongkorn","Monarch"),
"MYS":("Sultan Ibrahim","King (Yang di-Pertuan Agong)"),
"PAK":("Asif Ali Zardari","President"),
"BGD":("Mohammed Shahabuddin","President"),
"GRC":("Konstantinos Tasoulas","President"),
"PRT":("Marcelo Rebelo de Sousa","President"),
"CZE":("Petr Pavel","President"),
"HUN":("Tamas Sulyok","President"),
}
