-- =====================================================================
-- WORLD FINANCE ATLAS — Phase 1 schema + seed
-- Run in Supabase SQL editor. Idempotent: safe to re-run.
-- =====================================================================

drop table if exists bank cascade;
drop table if exists country cascade;
drop table if exists currency cascade;
drop table if exists indicator cascade;

-- ---------------------------------------------------------------------
create table currency (
  code        text primary key,
  name        text not null
);

create table country (
  iso3            text primary key,
  name            text not null,
  slug            text not null unique,
  region          text not null,
  capital         text,
  currency_code   text references currency(code),
  gdp_usd_bn      numeric not null,
  population_mn   numeric not null,
  land_km2        numeric not null,
  debt_pct_gdp    numeric,
  -- generated columns: computed by Postgres, never stored stale
  gdp_per_capita  numeric generated always as (
                    case when population_mn > 0
                    then round(gdp_usd_bn * 1000 / population_mn, 0) end) stored,
  pop_density     numeric generated always as (
                    case when land_km2 > 0
                    then round(population_mn * 1000000 / land_km2, 1) end) stored,
  gdp_per_km2     numeric generated always as (
                    case when land_km2 > 0
                    then round(gdp_usd_bn * 1000000000 / land_km2, 0) end) stored,
  debt_usd_bn     numeric generated always as (
                    case when debt_pct_gdp is not null
                    then round(gdp_usd_bn * debt_pct_gdp / 100, 1) end) stored
);

create index country_region_idx  on country(region);
create index country_gdp_idx     on country(gdp_usd_bn desc);
create index country_debt_idx    on country(debt_pct_gdp desc nulls last);
create index country_slug_idx    on country(slug);

create table bank (
  id            bigserial primary key,
  name          text not null,
  iso3          text not null references country(iso3) on delete cascade,
  assets_usd_bn numeric not null,
  hq_city       text
);
create index bank_iso3_idx   on bank(iso3);
create index bank_assets_idx on bank(assets_usd_bn desc);

-- Indicator definitions. This table is the product: perimeter and caveat
-- render next to the number in the UI, never buried in a methodology page.
create table indicator (
  code        text primary key,
  name        text not null,
  unit        text not null,
  definition  text not null,
  perimeter   text,
  valuation   text,
  caveat      text,
  source      text not null,
  vintage     text not null
);


-- ---- currency ----
insert into currency (code, name) values
  ('AED', 'UAE Dirham'),
  ('AFN', 'Afghan Afghani'),
  ('ALL', 'Albanian Lek'),
  ('AMD', 'Armenian Dram'),
  ('AOA', 'Angolan Kwanza'),
  ('ARS', 'Argentine Peso'),
  ('AUD', 'Australian Dollar'),
  ('AZN', 'Azerbaijani Manat'),
  ('BAM', 'Convertible Mark'),
  ('BBD', 'Barbadian Dollar'),
  ('BDT', 'Bangladeshi Taka'),
  ('BGN', 'Bulgarian Lev'),
  ('BHD', 'Bahraini Dinar'),
  ('BIF', 'Burundian Franc'),
  ('BND', 'Brunei Dollar'),
  ('BOB', 'Bolivian Boliviano'),
  ('BRL', 'Brazilian Real'),
  ('BSD', 'Bahamian Dollar'),
  ('BTN', 'Bhutanese Ngultrum'),
  ('BWP', 'Botswanan Pula'),
  ('BYN', 'Belarusian Ruble'),
  ('BZD', 'Belize Dollar'),
  ('CAD', 'Canadian Dollar'),
  ('CDF', 'Congolese Franc'),
  ('CHF', 'Swiss Franc'),
  ('CLP', 'Chilean Peso'),
  ('CNY', 'Renminbi'),
  ('COP', 'Colombian Peso'),
  ('CRC', 'Costa Rican Colon'),
  ('CUP', 'Cuban Peso'),
  ('CVE', 'Cape Verdean Escudo'),
  ('CZK', 'Czech Koruna'),
  ('DJF', 'Djiboutian Franc'),
  ('DKK', 'Danish Krone'),
  ('DOP', 'Dominican Peso'),
  ('DZD', 'Algerian Dinar'),
  ('EGP', 'Egyptian Pound'),
  ('ERN', 'Eritrean Nakfa'),
  ('ETB', 'Ethiopian Birr'),
  ('EUR', 'Euro'),
  ('FJD', 'Fijian Dollar'),
  ('GBP', 'Pound Sterling'),
  ('GEL', 'Georgian Lari'),
  ('GHS', 'Ghanaian Cedi'),
  ('GMD', 'Gambian Dalasi'),
  ('GNF', 'Guinean Franc'),
  ('GTQ', 'Guatemalan Quetzal'),
  ('GYD', 'Guyanese Dollar'),
  ('HKD', 'Hong Kong Dollar'),
  ('HNL', 'Honduran Lempira'),
  ('HTG', 'Haitian Gourde'),
  ('HUF', 'Hungarian Forint'),
  ('IDR', 'Indonesian Rupiah'),
  ('ILS', 'Israeli Shekel'),
  ('INR', 'Indian Rupee'),
  ('IQD', 'Iraqi Dinar'),
  ('IRR', 'Iranian Rial'),
  ('ISK', 'Icelandic Krona'),
  ('JMD', 'Jamaican Dollar'),
  ('JOD', 'Jordanian Dinar'),
  ('JPY', 'Japanese Yen'),
  ('KES', 'Kenyan Shilling'),
  ('KGS', 'Kyrgyzstani Som'),
  ('KHR', 'Cambodian Riel'),
  ('KMF', 'Comorian Franc'),
  ('KPW', 'North Korean Won'),
  ('KRW', 'South Korean Won'),
  ('KWD', 'Kuwaiti Dinar'),
  ('KZT', 'Kazakhstani Tenge'),
  ('LAK', 'Lao Kip'),
  ('LBP', 'Lebanese Pound'),
  ('LKR', 'Sri Lankan Rupee'),
  ('LRD', 'Liberian Dollar'),
  ('LSL', 'Lesotho Loti'),
  ('LYD', 'Libyan Dinar'),
  ('MAD', 'Moroccan Dirham'),
  ('MDL', 'Moldovan Leu'),
  ('MGA', 'Malagasy Ariary'),
  ('MKD', 'Macedonian Denar'),
  ('MMK', 'Myanmar Kyat'),
  ('MNT', 'Mongolian Tugrik'),
  ('MOP', 'Macanese Pataca'),
  ('MRU', 'Mauritanian Ouguiya'),
  ('MUR', 'Mauritian Rupee'),
  ('MVR', 'Maldivian Rufiyaa'),
  ('MWK', 'Malawian Kwacha'),
  ('MXN', 'Mexican Peso'),
  ('MYR', 'Malaysian Ringgit'),
  ('MZN', 'Mozambican Metical'),
  ('NAD', 'Namibian Dollar'),
  ('NGN', 'Nigerian Naira'),
  ('NIO', 'Nicaraguan Cordoba'),
  ('NOK', 'Norwegian Krone'),
  ('NPR', 'Nepalese Rupee'),
  ('NZD', 'New Zealand Dollar'),
  ('OMR', 'Omani Rial'),
  ('PEN', 'Peruvian Sol'),
  ('PGK', 'Papua New Guinean Kina'),
  ('PHP', 'Philippine Peso'),
  ('PKR', 'Pakistani Rupee'),
  ('PLN', 'Polish Zloty'),
  ('PYG', 'Paraguayan Guarani'),
  ('QAR', 'Qatari Riyal'),
  ('RON', 'Romanian Leu'),
  ('RSD', 'Serbian Dinar'),
  ('RUB', 'Russian Ruble'),
  ('RWF', 'Rwandan Franc'),
  ('SAR', 'Saudi Riyal'),
  ('SBD', 'Solomon Islands Dollar'),
  ('SCR', 'Seychellois Rupee'),
  ('SDG', 'Sudanese Pound'),
  ('SEK', 'Swedish Krona'),
  ('SGD', 'Singapore Dollar'),
  ('SLE', 'Sierra Leonean Leone'),
  ('SOS', 'Somali Shilling'),
  ('SRD', 'Surinamese Dollar'),
  ('SSP', 'South Sudanese Pound'),
  ('STN', 'Sao Tome Dobra'),
  ('SYP', 'Syrian Pound'),
  ('SZL', 'Swazi Lilangeni'),
  ('THB', 'Thai Baht'),
  ('TJS', 'Tajikistani Somoni'),
  ('TMT', 'Turkmenistani Manat'),
  ('TND', 'Tunisian Dinar'),
  ('TOP', 'Tongan Paanga'),
  ('TRY', 'Turkish Lira'),
  ('TTD', 'Trinidad & Tobago Dollar'),
  ('TWD', 'New Taiwan Dollar'),
  ('TZS', 'Tanzanian Shilling'),
  ('UAH', 'Ukrainian Hryvnia'),
  ('UGX', 'Ugandan Shilling'),
  ('USD', 'US Dollar'),
  ('UYU', 'Uruguayan Peso'),
  ('UZS', 'Uzbekistani Som'),
  ('VES', 'Venezuelan Bolivar'),
  ('VND', 'Vietnamese Dong'),
  ('VUV', 'Vanuatu Vatu'),
  ('WST', 'Samoan Tala'),
  ('XAF', 'Central African CFA Franc'),
  ('XOF', 'West African CFA Franc'),
  ('YER', 'Yemeni Rial'),
  ('ZAR', 'South African Rand'),
  ('ZMW', 'Zambian Kwacha'),
  ('ZWG', 'Zimbabwe Gold')
on conflict (code) do nothing;


-- ---- country ----
insert into country (iso3, name, slug, region, capital, currency_code, gdp_usd_bn, population_mn, land_km2, debt_pct_gdp) values
  ('USA', 'United States', 'united-states', 'North America', 'Washington, D.C.', 'USD', 30507, 342.0, 9147420, 125.8),
  ('CHN', 'China', 'china', 'Asia-Pacific', 'Beijing', 'CNY', 19535, 1416.1, 9388211, 96.3),
  ('DEU', 'Germany', 'germany', 'Europe', 'Berlin', 'EUR', 4744, 84.1, 349390, 64.7),
  ('IND', 'India', 'india', 'Asia-Pacific', 'New Delhi', 'INR', 4187, 1463.9, 2973190, 83.0),
  ('JPN', 'Japan', 'japan', 'Asia-Pacific', 'Tokyo', 'JPY', 4186, 123.1, 364555, 232.7),
  ('GBR', 'United Kingdom', 'united-kingdom', 'Europe', 'London', 'GBP', 3839, 69.6, 241930, 105.9),
  ('FRA', 'France', 'france', 'Europe', 'Paris', 'EUR', 3211, 66.6, 547557, 116.3),
  ('ITA', 'Italy', 'italy', 'Europe', 'Rome', 'EUR', 2422, 59.1, 294140, 136.9),
  ('BRA', 'Brazil', 'brazil', 'Latin America', 'Brasilia', 'BRL', 2307, 212.8, 8358140, 92.0),
  ('CAN', 'Canada', 'canada', 'North America', 'Ottawa', 'CAD', 2225, 40.6, 9093510, 105.6),
  ('RUS', 'Russia', 'russia', 'Europe', 'Moscow', 'RUB', 2076, 143.9, 16376870, 21.4),
  ('KOR', 'South Korea', 'south-korea', 'Asia-Pacific', 'Seoul', 'KRW', 1947, 51.7, 97230, 56.5),
  ('MEX', 'Mexico', 'mexico', 'Latin America', 'Mexico City', 'MXN', 1852, 131.9, 1943950, 58.6),
  ('ESP', 'Spain', 'spain', 'Europe', 'Madrid', 'EUR', 1799, 47.9, 498980, 101.3),
  ('AUS', 'Australia', 'australia', 'Asia-Pacific', 'Canberra', 'AUD', 1771, 26.9, 7633565, 50.1),
  ('IDN', 'Indonesia', 'indonesia', 'Asia-Pacific', 'Jakarta', 'IDR', 1492, 285.7, 1811570, 40.1),
  ('TUR', 'Turkey', 'turkey', 'Europe', 'Ankara', 'TRY', 1437, 87.7, 769630, 26.4),
  ('NLD', 'Netherlands', 'netherlands', 'Europe', 'Amsterdam', 'EUR', 1272, 18.3, 33690, 43.1),
  ('SAU', 'Saudi Arabia', 'saudi-arabia', 'Middle East', 'Riyadh', 'SAR', 1137, 34.6, 2149690, 32.4),
  ('CHE', 'Switzerland', 'switzerland', 'Europe', 'Bern', 'CHF', 999, 9.1, 39516, 37.7),
  ('POL', 'Poland', 'poland', 'Europe', 'Warsaw', 'PLN', 915, 38.5, 306230, 58.3),
  ('TWN', 'Taiwan', 'taiwan', 'Asia-Pacific', 'Taipei', 'TWD', 814, 23.4, 32260, 27.5),
  ('BEL', 'Belgium', 'belgium', 'Europe', 'Brussels', 'EUR', 690, 11.8, 30280, 105.9),
  ('ARG', 'Argentina', 'argentina', 'Latin America', 'Buenos Aires', 'ARS', 683, 45.9, 2736690, 64.5),
  ('SWE', 'Sweden', 'sweden', 'Europe', 'Stockholm', 'SEK', 620, 10.6, 410340, 34.2),
  ('IRL', 'Ireland', 'ireland', 'Europe', 'Dublin', 'EUR', 598, 5.3, 68890, 40.8),
  ('ARE', 'United Arab Emirates', 'united-arab-emirates', 'Middle East', 'Abu Dhabi', 'AED', 569, 11.0, 83600, 29.4),
  ('SGP', 'Singapore', 'singapore', 'Asia-Pacific', 'Singapore', 'SGD', 562, 6.1, 709, 174.9),
  ('AUT', 'Austria', 'austria', 'Europe', 'Vienna', 'EUR', 552, 9.1, 82409, 79.2),
  ('ISR', 'Israel', 'israel', 'Middle East', 'Jerusalem', 'ILS', 551, 9.9, 21640, 70.1),
  ('THA', 'Thailand', 'thailand', 'Asia-Pacific', 'Bangkok', 'THB', 546, 71.6, 510890, 63.9),
  ('NOR', 'Norway', 'norway', 'Europe', 'Oslo', 'NOK', 530, 5.6, 365268, 43.7),
  ('PHL', 'Philippines', 'philippines', 'Asia-Pacific', 'Manila', 'PHP', 508, 116.8, 298170, 58.3),
  ('VNM', 'Vietnam', 'vietnam', 'Asia-Pacific', 'Hanoi', 'VND', 506, 101.6, 310070, 34.9),
  ('MYS', 'Malaysia', 'malaysia', 'Asia-Pacific', 'Kuala Lumpur', 'MYR', 489, 35.8, 328550, 66.8),
  ('BGD', 'Bangladesh', 'bangladesh', 'Asia-Pacific', 'Dhaka', 'BDT', 482, 175.7, 130170, 40.4),
  ('DNK', 'Denmark', 'denmark', 'Europe', 'Copenhagen', 'DKK', 436, 6.0, 42430, 29.3),
  ('IRN', 'Iran', 'iran', 'Middle East', 'Tehran', 'IRR', 436, 92.4, 1628550, 33.6),
  ('HKG', 'Hong Kong SAR', 'hong-kong-sar', 'Asia-Pacific', 'Hong Kong', 'HKD', 422, 7.4, 1073, 11.9),
  ('PAK', 'Pakistan', 'pakistan', 'Asia-Pacific', 'Islamabad', 'PKR', 412, 255.2, 770880, 73.4),
  ('ZAF', 'South Africa', 'south-africa', 'Africa', 'Pretoria', 'ZAR', 410, 64.7, 1213090, 76.5),
  ('ROU', 'Romania', 'romania', 'Europe', 'Bucharest', 'RON', 406, 18.9, 230170, 56.1),
  ('EGY', 'Egypt', 'egypt', 'Africa', 'Cairo', 'EGP', 393, 118.4, 995450, 88.1),
  ('COL', 'Colombia', 'colombia', 'Latin America', 'Bogota', 'COP', 480, 53.4, 1109500, 58.2),
  ('CZE', 'Czechia', 'czechia', 'Europe', 'Prague', 'CZK', 364, 10.7, 77240, 45.2),
  ('CHL', 'Chile', 'chile', 'Latin America', 'Santiago', 'CLP', 344, 20.0, 743532, 42.6),
  ('PRT', 'Portugal', 'portugal', 'Europe', 'Lisbon', 'EUR', 324, 10.4, 91590, 91.5),
  ('FIN', 'Finland', 'finland', 'Europe', 'Helsinki', 'EUR', 309, 5.6, 303890, 84.3),
  ('PER', 'Peru', 'peru', 'Latin America', 'Lima', 'PEN', 305, 34.6, 1280000, 34.1),
  ('KAZ', 'Kazakhstan', 'kazakhstan', 'Asia-Pacific', 'Astana', 'KZT', 300, 20.8, 2699700, 25.6),
  ('GRC', 'Greece', 'greece', 'Europe', 'Athens', 'EUR', 280, 10.0, 128900, 142.2),
  ('IRQ', 'Iraq', 'iraq', 'Middle East', 'Baghdad', 'IQD', 274, 47.0, 434320, 49.2),
  ('DZA', 'Algeria', 'algeria', 'Africa', 'Algiers', 'DZD', 269, 47.4, 2381740, 49.6),
  ('NZL', 'New Zealand', 'new-zealand', 'Asia-Pacific', 'Wellington', 'NZD', 259, 5.3, 262443, 46.3),
  ('HUN', 'Hungary', 'hungary', 'Europe', 'Budapest', 'HUF', 243, 9.6, 90530, 73.4),
  ('QAT', 'Qatar', 'qatar', 'Middle East', 'Doha', 'QAR', 223, 3.1, 11610, 42.5),
  ('UKR', 'Ukraine', 'ukraine', 'Europe', 'Kyiv', 'UAH', 205, 37.9, 579320, 102.4),
  ('NGA', 'Nigeria', 'nigeria', 'Africa', 'Abuja', 'NGN', 188, 237.5, 910770, 52.9),
  ('MAR', 'Morocco', 'morocco', 'Africa', 'Rabat', 'MAD', 165, 38.4, 446300, 68.9),
  ('KWT', 'Kuwait', 'kuwait', 'Middle East', 'Kuwait City', 'KWD', 162, 5.0, 17820, 7.9),
  ('SVK', 'Slovakia', 'slovakia', 'Europe', 'Bratislava', 'EUR', 153, 5.5, 48088, 60.2),
  ('ETH', 'Ethiopia', 'ethiopia', 'Africa', 'Addis Ababa', 'ETB', 145, 135.5, 1000000, 35.4),
  ('ECU', 'Ecuador', 'ecuador', 'Latin America', 'Quito', 'USD', 132, 18.4, 248360, 55.8),
  ('KEN', 'Kenya', 'kenya', 'Africa', 'Nairobi', 'KES', 132, 57.5, 569140, 70.1),
  ('DOM', 'Dominican Republic', 'dominican-republic', 'Latin America', 'Santo Domingo', 'DOP', 127, 11.5, 48320, 60.4),
  ('PRI', 'Puerto Rico', 'puerto-rico', 'Latin America', 'San Juan', 'USD', 125, 3.2, 8870, NULL),
  ('GTM', 'Guatemala', 'guatemala', 'Latin America', 'Guatemala City', 'GTQ', 122, 18.7, 107160, 27.6),
  ('AGO', 'Angola', 'angola', 'Africa', 'Luanda', 'AOA', 121, 38.9, 1246700, 63.8),
  ('BGR', 'Bulgaria', 'bulgaria', 'Europe', 'Sofia', 'BGN', 117, 6.4, 108560, 25.1),
  ('OMN', 'Oman', 'oman', 'Middle East', 'Muscat', 'OMR', 115, 5.6, 309500, 35.4),
  ('UZB', 'Uzbekistan', 'uzbekistan', 'Asia-Pacific', 'Tashkent', 'UZS', 113, 37.5, 425400, 35.2),
  ('VEN', 'Venezuela', 'venezuela', 'Latin America', 'Caracas', 'VES', 106, 28.4, 882050, 155.0),
  ('CRI', 'Costa Rica', 'costa-rica', 'Latin America', 'San Jose', 'CRC', 102, 5.1, 51060, 62.5),
  ('LUX', 'Luxembourg', 'luxembourg', 'Europe', 'Luxembourg', 'EUR', 96, 0.7, 2590, 26.4),
  ('HRV', 'Croatia', 'croatia', 'Europe', 'Zagreb', 'EUR', 97, 3.8, 55960, 57.6),
  ('CIV', 'Ivory Coast', 'ivory-coast', 'Africa', 'Yamoussoukro', 'XOF', 95, 32.7, 318000, 58.1),
  ('PAN', 'Panama', 'panama', 'Latin America', 'Panama City', 'USD', 92, 4.6, 74340, 63.5),
  ('SRB', 'Serbia', 'serbia', 'Europe', 'Belgrade', 'RSD', 92, 6.6, 87460, 47.5),
  ('TZA', 'Tanzania', 'tanzania', 'Africa', 'Dodoma', 'TZS', 90, 70.5, 885800, 47.3),
  ('LTU', 'Lithuania', 'lithuania', 'Europe', 'Vilnius', 'EUR', 90, 2.8, 62680, 40.1),
  ('GHA', 'Ghana', 'ghana', 'Africa', 'Accra', 'GHS', 88, 35.1, 227540, 72.5),
  ('URY', 'Uruguay', 'uruguay', 'Latin America', 'Montevideo', 'UYU', 86, 3.4, 175020, 64.1),
  ('LKA', 'Sri Lanka', 'sri-lanka', 'Asia-Pacific', 'Colombo', 'LKR', 83, 23.3, 62710, 103.7),
  ('TKM', 'Turkmenistan', 'turkmenistan', 'Asia-Pacific', 'Ashgabat', 'TMT', 83, 7.6, 469930, 5.5),
  ('COD', 'Democratic Republic of the Congo', 'democratic-republic-of-the-congo', 'Africa', 'Kinshasa', 'CDF', 79, 112.8, 2267050, 20.6),
  ('AZE', 'Azerbaijan', 'azerbaijan', 'Asia-Pacific', 'Baku', 'AZN', 78, 10.4, 82658, 20.3),
  ('BLR', 'Belarus', 'belarus', 'Europe', 'Minsk', 'BYN', 78, 9.1, 202980, 42.7),
  ('SVN', 'Slovenia', 'slovenia', 'Europe', 'Ljubljana', 'EUR', 76, 2.1, 20140, 66.4),
  ('UGA', 'Uganda', 'uganda', 'Africa', 'Kampala', 'UGX', 66, 51.4, 199810, 52.4),
  ('MMR', 'Myanmar', 'myanmar', 'Asia-Pacific', 'Naypyidaw', 'MMK', 65, 54.9, 653290, 60.1),
  ('CUB', 'Cuba', 'cuba', 'Latin America', 'Havana', 'CUP', 64, 10.9, 103800, NULL),
  ('MAC', 'Macao SAR', 'macao-sar', 'Asia-Pacific', 'Macao', 'MOP', 57, 0.7, 33, 0.0),
  ('CMR', 'Cameroon', 'cameroon', 'Africa', 'Yaounde', 'XAF', 56, 30.1, 472710, 43.8),
  ('TUN', 'Tunisia', 'tunisia', 'Africa', 'Tunis', 'TND', 56, 12.4, 155360, 82.5),
  ('JOR', 'Jordan', 'jordan', 'Middle East', 'Amman', 'JOD', 55, 11.6, 88780, 91.5),
  ('BOL', 'Bolivia', 'bolivia', 'Latin America', 'Sucre', 'BOB', 52, 12.5, 1083300, 95.1),
  ('KHM', 'Cambodia', 'cambodia', 'Asia-Pacific', 'Phnom Penh', 'KHR', 50, 17.8, 176520, 27.4),
  ('LVA', 'Latvia', 'latvia', 'Europe', 'Riga', 'EUR', 49, 1.9, 62200, 47.9),
  ('BHR', 'Bahrain', 'bahrain', 'Middle East', 'Manama', 'BHD', 48, 1.6, 760, 130.1),
  ('LBY', 'Libya', 'libya', 'Africa', 'Tripoli', 'LYD', 47, 7.5, 1759540, 55.4),
  ('PRY', 'Paraguay', 'paraguay', 'Latin America', 'Asuncion', 'PYG', 47, 6.9, 397300, 42.1),
  ('NPL', 'Nepal', 'nepal', 'Asia-Pacific', 'Kathmandu', 'NPR', 45, 29.7, 143350, 47.8),
  ('EST', 'Estonia', 'estonia', 'Europe', 'Tallinn', 'EUR', 44, 1.4, 42750, 25.8),
  ('SLV', 'El Salvador', 'el-salvador', 'Latin America', 'San Salvador', 'USD', 39, 6.4, 20720, 86.4),
  ('ZWE', 'Zimbabwe', 'zimbabwe', 'Africa', 'Harare', 'ZWG', 38, 16.9, 386850, 45.9),
  ('HND', 'Honduras', 'honduras', 'Latin America', 'Tegucigalpa', 'HNL', 38, 10.9, 111890, 46.2),
  ('SEN', 'Senegal', 'senegal', 'Africa', 'Dakar', 'XOF', 36, 18.9, 192530, 111.4),
  ('CYP', 'Cyprus', 'cyprus', 'Europe', 'Nicosia', 'EUR', 36, 1.4, 9240, 60.9),
  ('ISL', 'Iceland', 'iceland', 'Europe', 'Reykjavik', 'ISK', 36, 0.4, 100250, 60.1),
  ('PNG', 'Papua New Guinea', 'papua-new-guinea', 'Asia-Pacific', 'Port Moresby', 'PGK', 34, 10.9, 452860, 50.8),
  ('GEO', 'Georgia', 'georgia', 'Asia-Pacific', 'Tbilisi', 'GEL', 34, 3.8, 69490, 37.2),
  ('ZMB', 'Zambia', 'zambia', 'Africa', 'Lusaka', 'ZMW', 30, 21.6, 743390, 72.4),
  ('SDN', 'Sudan', 'sudan', 'Africa', 'Khartoum', 'SDG', 29, 51.7, 1765048, 252.0),
  ('PRK', 'North Korea', 'north-korea', 'Asia-Pacific', 'Pyongyang', 'KPW', 29, 26.6, 120410, NULL),
  ('BIH', 'Bosnia and Herzegovina', 'bosnia-and-herzegovina', 'Europe', 'Sarajevo', 'BAM', 29, 3.2, 51000, 26.8),
  ('TTO', 'Trinidad and Tobago', 'trinidad-and-tobago', 'Latin America', 'Port of Spain', 'TTD', 29, 1.5, 5130, 58.4),
  ('ALB', 'Albania', 'albania', 'Europe', 'Tirana', 'ALL', 28, 2.8, 27400, 55.9),
  ('ARM', 'Armenia', 'armenia', 'Asia-Pacific', 'Yerevan', 'AMD', 27, 3.0, 28470, 49.7),
  ('LBN', 'Lebanon', 'lebanon', 'Middle East', 'Beirut', 'LBP', 26, 5.8, 10230, 145.0),
  ('GIN', 'Guinea', 'guinea', 'Africa', 'Conakry', 'GNF', 25, 15.2, 245720, 33.1),
  ('GUY', 'Guyana', 'guyana', 'Latin America', 'Georgetown', 'GYD', 25, 0.8, 196850, 24.8),
  ('MNG', 'Mongolia', 'mongolia', 'Asia-Pacific', 'Ulaanbaatar', 'MNT', 24, 3.5, 1553560, 66.2),
  ('MLT', 'Malta', 'malta', 'Europe', 'Valletta', 'EUR', 23, 0.6, 320, 49.7),
  ('MOZ', 'Mozambique', 'mozambique', 'Africa', 'Maputo', 'MZN', 23, 35.1, 786380, 90.5),
  ('MLI', 'Mali', 'mali', 'Africa', 'Bamako', 'XOF', 22, 25.4, 1220190, 52.1),
  ('BFA', 'Burkina Faso', 'burkina-faso', 'Africa', 'Ouagadougou', 'XOF', 22, 24.1, 273600, 58.5),
  ('BWA', 'Botswana', 'botswana', 'Africa', 'Gaborone', 'BWP', 21, 2.5, 566730, 26.9),
  ('GAB', 'Gabon', 'gabon', 'Africa', 'Libreville', 'XAF', 21, 2.6, 257670, 73.2),
  ('BEN', 'Benin', 'benin', 'Africa', 'Porto-Novo', 'XOF', 21, 14.7, 112760, 53.5),
  ('JAM', 'Jamaica', 'jamaica', 'Latin America', 'Kingston', 'JMD', 21, 2.8, 10830, 64.1),
  ('NER', 'Niger', 'niger', 'Africa', 'Niamey', 'XOF', 19, 27.9, 1266700, 49.5),
  ('NIC', 'Nicaragua', 'nicaragua', 'Latin America', 'Managua', 'NIO', 19, 7.0, 120340, 42.9),
  ('MDA', 'Moldova', 'moldova', 'Europe', 'Chisinau', 'MDL', 19, 3.0, 32900, 39.2),
  ('MDG', 'Madagascar', 'madagascar', 'Africa', 'Antananarivo', 'MGA', 18, 32.0, 581800, 54.2),
  ('MKD', 'North Macedonia', 'north-macedonia', 'Europe', 'Skopje', 'MKD', 17, 1.8, 25220, 57.3),
  ('KGZ', 'Kyrgyzstan', 'kyrgyzstan', 'Asia-Pacific', 'Bishkek', 'KGS', 17, 7.3, 191800, 42.1),
  ('YEM', 'Yemen', 'yemen', 'Middle East', 'Sanaa', 'YER', 17, 41.8, 527970, 79.5),
  ('AFG', 'Afghanistan', 'afghanistan', 'Asia-Pacific', 'Kabul', 'AFN', 17, 43.8, 652230, NULL),
  ('BRN', 'Brunei', 'brunei', 'Asia-Pacific', 'Bandar Seri Begawan', 'BND', 16, 0.5, 5270, 2.3),
  ('LAO', 'Laos', 'laos', 'Asia-Pacific', 'Vientiane', 'LAK', 16, 7.9, 230800, 115.0),
  ('RWA', 'Rwanda', 'rwanda', 'Africa', 'Kigali', 'RWF', 16, 14.6, 24670, 79.6),
  ('MUS', 'Mauritius', 'mauritius', 'Africa', 'Port Louis', 'MUR', 16, 1.3, 2030, 79.8),
  ('COG', 'Congo', 'congo', 'Africa', 'Brazzaville', 'XAF', 16, 6.4, 341500, 96.4),
  ('BHS', 'Bahamas', 'bahamas', 'Latin America', 'Nassau', 'BSD', 15, 0.4, 10010, 79.2),
  ('TJK', 'Tajikistan', 'tajikistan', 'Asia-Pacific', 'Dushanbe', 'TJS', 14, 10.8, 138790, 32.1),
  ('PSE', 'Palestine', 'palestine', 'Middle East', 'Ramallah', 'ILS', 14, 5.6, 6020, NULL),
  ('TCD', 'Chad', 'chad', 'Africa', 'N''Djamena', 'XAF', 14, 20.3, 1259200, 49.5),
  ('HTI', 'Haiti', 'haiti', 'Latin America', 'Port-au-Prince', 'HTG', 13, 11.9, 27560, 23.5),
  ('NAM', 'Namibia', 'namibia', 'Africa', 'Windhoek', 'NAD', 13, 3.1, 823290, 66.3),
  ('SOM', 'Somalia', 'somalia', 'Africa', 'Mogadishu', 'SOS', 13, 19.7, 627340, 5.9),
  ('MWI', 'Malawi', 'malawi', 'Africa', 'Lilongwe', 'MWK', 12, 22.0, 94280, 88.2),
  ('SYR', 'Syria', 'syria', 'Middle East', 'Damascus', 'SYP', 12, 25.6, 183630, NULL),
  ('MRT', 'Mauritania', 'mauritania', 'Africa', 'Nouakchott', 'MRU', 12, 5.3, 1030700, 46.3),
  ('XKX', 'Kosovo', 'kosovo', 'Europe', 'Pristina', 'EUR', 12, 1.6, 10887, 17.7),
  ('GNQ', 'Equatorial Guinea', 'equatorial-guinea', 'Africa', 'Malabo', 'XAF', 12, 1.9, 28050, 42.5),
  ('TGO', 'Togo', 'togo', 'Africa', 'Lome', 'XOF', 10, 9.7, 54390, 68.4),
  ('MCO', 'Monaco', 'monaco', 'Europe', 'Monaco', 'EUR', 10, 0.0, 2, NULL),
  ('LIE', 'Liechtenstein', 'liechtenstein', 'Europe', 'Vaduz', 'CHF', 8, 0.0, 160, NULL),
  ('MNE', 'Montenegro', 'montenegro', 'Europe', 'Podgorica', 'EUR', 8, 0.6, 13450, 61.5),
  ('SLE', 'Sierra Leone', 'sierra-leone', 'Africa', 'Freetown', 'SLE', 7, 8.9, 72180, 44.9),
  ('BRB', 'Barbados', 'barbados', 'Latin America', 'Bridgetown', 'BBD', 7, 0.3, 430, 103.2),
  ('MDV', 'Maldives', 'maldives', 'Asia-Pacific', 'Male', 'MVR', 7, 0.5, 300, 124.2),
  ('FJI', 'Fiji', 'fiji', 'Asia-Pacific', 'Suva', 'FJD', 6, 0.9, 18270, 78.3),
  ('LBR', 'Liberia', 'liberia', 'Africa', 'Monrovia', 'LRD', 5, 5.7, 96320, 54.6),
  ('SSD', 'South Sudan', 'south-sudan', 'Africa', 'Juba', 'SSP', 5, 12.0, 610952, 58.1),
  ('SWZ', 'Eswatini', 'eswatini', 'Africa', 'Mbabane', 'SZL', 5, 1.2, 17200, 45.1),
  ('SUR', 'Suriname', 'suriname', 'Latin America', 'Paramaribo', 'SRD', 4, 0.6, 156000, 89.5),
  ('DJI', 'Djibouti', 'djibouti', 'Africa', 'Djibouti', 'DJF', 4, 1.2, 23180, 32.4),
  ('AND', 'Andorra', 'andorra', 'Europe', 'Andorra la Vella', 'EUR', 4, 0.1, 470, 34.5),
  ('BTN', 'Bhutan', 'bhutan', 'Asia-Pacific', 'Thimphu', 'BTN', 3, 0.8, 38117, 120.7),
  ('BDI', 'Burundi', 'burundi', 'Africa', 'Gitega', 'BIF', 3, 14.4, 25680, 72.5),
  ('CAF', 'Central African Republic', 'central-african-republic', 'Africa', 'Bangui', 'XAF', 3, 5.7, 622980, 52.7),
  ('ERI', 'Eritrea', 'eritrea', 'Africa', 'Asmara', 'ERN', 3, 3.7, 101000, 158.0),
  ('GMB', 'Gambia', 'gambia', 'Africa', 'Banjul', 'GMD', 3, 2.8, 10120, 70.5),
  ('CPV', 'Cape Verde', 'cape-verde', 'Africa', 'Praia', 'CVE', 3, 0.5, 4030, 110.5),
  ('BLZ', 'Belize', 'belize', 'Latin America', 'Belmopan', 'BZD', 3, 0.4, 22810, 63.2),
  ('LSO', 'Lesotho', 'lesotho', 'Africa', 'Maseru', 'LSL', 2, 2.3, 30360, 60.4),
  ('TLS', 'Timor-Leste', 'timor-leste', 'Asia-Pacific', 'Dili', 'USD', 2, 1.4, 14870, 17.5),
  ('GNB', 'Guinea-Bissau', 'guinea-bissau', 'Africa', 'Bissau', 'XOF', 2, 2.2, 28120, 77.1),
  ('COM', 'Comoros', 'comoros', 'Africa', 'Moroni', 'KMF', 2, 0.9, 1861, 35.4),
  ('SLB', 'Solomon Islands', 'solomon-islands', 'Asia-Pacific', 'Honiara', 'SBD', 2, 0.8, 27990, 17.2),
  ('SYC', 'Seychelles', 'seychelles', 'Africa', 'Victoria', 'SCR', 2, 0.1, 460, 60.2),
  ('SMR', 'San Marino', 'san-marino', 'Europe', 'San Marino', 'EUR', 2, 0.0, 60, NULL),
  ('STP', 'Sao Tome and Principe', 'sao-tome-and-principe', 'Africa', 'Sao Tome', 'STN', 1, 0.2, 960, 49.5),
  ('VUT', 'Vanuatu', 'vanuatu', 'Asia-Pacific', 'Port Vila', 'VUV', 1, 0.3, 12190, 41.2),
  ('WSM', 'Samoa', 'samoa', 'Asia-Pacific', 'Apia', 'WST', 1, 0.2, 2830, 42.6),
  ('TON', 'Tonga', 'tonga', 'Asia-Pacific', 'Nuku''alofa', 'TOP', 1, 0.1, 720, 40.5)
on conflict (iso3) do nothing;


-- ---- bank ----
insert into bank (name, iso3, assets_usd_bn, hq_city) values
  ('Industrial and Commercial Bank of China', 'CHN', 7646, 'Beijing'),
  ('Agricultural Bank of China', 'CHN', 6580, 'Beijing'),
  ('China Construction Bank', 'CHN', 6300, 'Beijing'),
  ('Bank of China', 'CHN', 5600, 'Beijing'),
  ('JPMorgan Chase', 'USA', 4360, 'New York'),
  ('Bank of America', 'USA', 3350, 'Charlotte'),
  ('HSBC Holdings', 'GBR', 3100, 'London'),
  ('BNP Paribas', 'FRA', 2950, 'Paris'),
  ('Mitsubishi UFJ Financial Group', 'JPN', 2900, 'Tokyo'),
  ('Credit Agricole', 'FRA', 2740, 'Montrouge'),
  ('Citigroup', 'USA', 2600, 'New York'),
  ('Wells Fargo', 'USA', 1950, 'San Francisco'),
  ('Banco Santander', 'ESP', 1930, 'Madrid'),
  ('Sumitomo Mitsui Financial Group', 'JPN', 2050, 'Tokyo'),
  ('Mizuho Financial Group', 'JPN', 1980, 'Tokyo'),
  ('UBS Group', 'CHE', 1720, 'Zurich'),
  ('Barclays', 'GBR', 1700, 'London'),
  ('Bank of Communications', 'CHN', 1690, 'Shanghai'),
  ('Postal Savings Bank of China', 'CHN', 2400, 'Beijing'),
  ('Societe Generale', 'FRA', 1660, 'Paris'),
  ('Groupe BPCE', 'FRA', 1610, 'Paris'),
  ('Royal Bank of Canada', 'CAN', 1600, 'Toronto'),
  ('Deutsche Bank', 'DEU', 1560, 'Frankfurt'),
  ('China Merchants Bank', 'CHN', 1550, 'Shenzhen'),
  ('Toronto-Dominion Bank', 'CAN', 1500, 'Toronto'),
  ('Goldman Sachs', 'USA', 1680, 'New York'),
  ('Morgan Stanley', 'USA', 1300, 'New York'),
  ('Industrial Bank Co', 'CHN', 1500, 'Fuzhou'),
  ('Shanghai Pudong Development Bank', 'CHN', 1250, 'Shanghai'),
  ('China CITIC Bank', 'CHN', 1300, 'Beijing'),
  ('ING Group', 'NLD', 1080, 'Amsterdam'),
  ('Intesa Sanpaolo', 'ITA', 1050, 'Turin'),
  ('Lloyds Banking Group', 'GBR', 1030, 'London'),
  ('UniCredit', 'ITA', 840, 'Milan'),
  ('Commonwealth Bank of Australia', 'AUS', 900, 'Sydney'),
  ('Bank of Nova Scotia', 'CAN', 1000, 'Toronto'),
  ('Bank of Montreal', 'CAN', 1010, 'Montreal'),
  ('BBVA', 'ESP', 840, 'Madrid'),
  ('Standard Chartered', 'GBR', 860, 'London'),
  ('Nordea Bank', 'FIN', 650, 'Helsinki'),
  ('ANZ Group', 'AUS', 750, 'Melbourne'),
  ('Westpac Banking Corp', 'AUS', 760, 'Sydney'),
  ('National Australia Bank', 'AUS', 740, 'Melbourne'),
  ('Rabobank', 'NLD', 670, 'Utrecht'),
  ('Canadian Imperial Bank of Commerce', 'CAN', 730, 'Toronto'),
  ('DBS Group', 'SGP', 620, 'Singapore'),
  ('State Bank of India', 'IND', 790, 'Mumbai'),
  ('HDFC Bank', 'IND', 480, 'Mumbai'),
  ('Sberbank', 'RUS', 680, 'Moscow'),
  ('KB Financial Group', 'KOR', 560, 'Seoul'),
  ('Shinhan Financial Group', 'KOR', 540, 'Seoul'),
  ('Itau Unibanco', 'BRA', 480, 'Sao Paulo'),
  ('Banco do Brasil', 'BRA', 470, 'Brasilia'),
  ('Caixa Economica Federal', 'BRA', 450, 'Brasilia'),
  ('Nomura Holdings', 'JPN', 420, 'Tokyo'),
  ('Danske Bank', 'DNK', 410, 'Copenhagen'),
  ('OCBC Bank', 'SGP', 440, 'Singapore'),
  ('United Overseas Bank', 'SGP', 380, 'Singapore'),
  ('Qatar National Bank', 'QAT', 350, 'Doha'),
  ('First Abu Dhabi Bank', 'ARE', 330, 'Abu Dhabi'),
  ('ICICI Bank', 'IND', 300, 'Mumbai'),
  ('Bank Central Asia', 'IDN', 100, 'Jakarta'),
  ('Absa Group', 'ZAF', 120, 'Johannesburg'),
  ('Standard Bank Group', 'ZAF', 180, 'Johannesburg'),
  ('Akbank', 'TUR', 90, 'Istanbul'),
  ('Bancolombia', 'COL', 90, 'Medellin'),
  ('Banco de Chile', 'CHL', 70, 'Santiago'),
  ('BDO Unibank', 'PHL', 90, 'Manila'),
  ('Maybank', 'MYS', 250, 'Kuala Lumpur'),
  ('Kasikornbank', 'THA', 130, 'Bangkok'),
  ('Vietcombank', 'VNM', 80, 'Hanoi'),
  ('National Bank of Egypt', 'EGY', 120, 'Cairo'),
  ('Attijariwafa Bank', 'MAR', 70, 'Casablanca'),
  ('Saudi National Bank', 'SAU', 280, 'Riyadh'),
  ('Bank Leumi', 'ISR', 200, 'Tel Aviv'),
  ('Raiffeisen Bank International', 'AUT', 220, 'Vienna'),
  ('PKO Bank Polski', 'POL', 130, 'Warsaw'),
  ('Erste Group Bank', 'AUT', 370, 'Vienna'),
  ('SEB', 'SWE', 380, 'Stockholm'),
  ('Swedbank', 'SWE', 300, 'Stockholm'),
  ('DNB Bank', 'NOR', 340, 'Oslo'),
  ('Bank of Ireland', 'IRL', 170, 'Dublin'),
  ('Banco de Credito del Peru', 'PER', 60, 'Lima'),
  ('Kuwait Finance House', 'KWT', 120, 'Kuwait City'),
  ('Emirates NBD', 'ARE', 250, 'Dubai'),
  ('CTBC Financial', 'TWN', 270, 'Taipei'),
  ('Cathay Financial', 'TWN', 330, 'Taipei'),
  ('Kookmin Bank', 'KOR', 420, 'Seoul'),
  ('Banco Nacion', 'ARG', 50, 'Buenos Aires'),
  ('Grupo Financiero Banorte', 'MEX', 110, 'Monterrey'),
  ('BBVA Mexico', 'MEX', 150, 'Mexico City'),
  ('Bank Mandiri', 'IDN', 120, 'Jakarta'),
  ('Krung Thai Bank', 'THA', 110, 'Bangkok'),
  ('Ecobank', 'TGO', 30, 'Lome'),
  ('Equity Group', 'KEN', 13, 'Nairobi'),
  ('Zenith Bank', 'NGA', 20, 'Lagos'),
  ('Access Bank', 'NGA', 25, 'Lagos'),
  ('Nedbank', 'ZAF', 90, 'Johannesburg'),
  ('Habib Bank', 'PAK', 20, 'Karachi'),
  ('BRAC Bank', 'BGD', 5, 'Dhaka'),
  ('Commercial Bank of Ceylon', 'LKA', 6, 'Colombo'),
  ('Bank of Georgia', 'GEO', 9, 'Tbilisi'),
  ('OTP Bank', 'HUN', 120, 'Budapest'),
  ('Komercni Banka', 'CZE', 70, 'Prague'),
  ('Banca Transilvania', 'ROU', 50, 'Cluj-Napoca'),
  ('NLB Group', 'SVN', 30, 'Ljubljana'),
  ('Halyk Bank', 'KAZ', 40, 'Almaty'),
  ('Kaspi Bank', 'KAZ', 20, 'Almaty'),
  ('Ameriabank', 'ARM', 3, 'Yerevan'),
  ('Bank of Cyprus', 'CYP', 30, 'Nicosia'),
  ('Landsbankinn', 'ISL', 13, 'Reykjavik'),
  ('Bank of Valletta', 'MLT', 16, 'Valletta'),
  ('Luminor Bank', 'EST', 18, 'Tallinn'),
  ('Citadele Banka', 'LVA', 6, 'Riga'),
  ('Siauliu Bankas', 'LTU', 5, 'Vilnius'),
  ('Zagrebacka Banka', 'HRV', 25, 'Zagreb'),
  ('NLB Banka', 'SRB', 8, 'Belgrade'),
  ('Raiffeisen Bank Kosovo', 'XKX', 2, 'Pristina'),
  ('Banca Intesa Beograd', 'BIH', 4, 'Sarajevo'),
  ('Banco Popular Dominicano', 'DOM', 15, 'Santo Domingo'),
  ('Banco General', 'PAN', 20, 'Panama City'),
  ('Banco Nacional de Costa Rica', 'CRI', 12, 'San Jose'),
  ('Banco Industrial', 'GTM', 18, 'Guatemala City'),
  ('Banco Agricola', 'SLV', 6, 'San Salvador'),
  ('Banco Atlantida', 'HND', 7, 'Tegucigalpa'),
  ('Banco de la Republica Oriental', 'URY', 20, 'Montevideo'),
  ('Banco Nacional de Bolivia', 'BOL', 5, 'La Paz'),
  ('Banco Continental', 'PRY', 6, 'Asuncion'),
  ('Republic Bank', 'TTO', 10, 'Port of Spain'),
  ('National Commercial Bank Jamaica', 'JAM', 6, 'Kingston'),
  ('Bank of Guyana', 'GUY', 2, 'Georgetown'),
  ('Bank of Kigali', 'RWA', 2, 'Kigali'),
  ('CRDB Bank', 'TZA', 5, 'Dodoma'),
  ('Stanbic Bank Uganda', 'UGA', 3, 'Kampala'),
  ('Bank of Africa', 'MLI', 2, 'Bamako'),
  ('BGFIBank', 'GAB', 7, 'Libreville'),
  ('Afriland First Bank', 'CMR', 3, 'Yaounde'),
  ('Banque Misr', 'EGY', 70, 'Cairo'),
  ('Arab Bank', 'JOR', 70, 'Amman'),
  ('Bank Melli Iran', 'IRN', 90, 'Tehran'),
  ('Bank Muscat', 'OMN', 35, 'Muscat'),
  ('Ahli United Bank', 'BHR', 40, 'Manama'),
  ('Rafidain Bank', 'IRQ', 40, 'Baghdad'),
  ('Bank of Mauritius', 'MUS', 8, 'Port Louis'),
  ('Trust Merchant Bank', 'COD', 2, 'Kinshasa'),
  ('Bank of Abyssinia', 'ETH', 4, 'Addis Ababa'),
  ('Banco de Fomento Angola', 'AGO', 8, 'Luanda'),
  ('Banco Comercial e de Investimentos', 'MOZ', 3, 'Maputo'),
  ('Zanaco', 'ZMB', 2, 'Lusaka'),
  ('CBZ Bank', 'ZWE', 2, 'Harare'),
  ('First National Bank Namibia', 'NAM', 4, 'Windhoek'),
  ('First Capital Bank', 'MWI', 1, 'Lilongwe'),
  ('Bank Windhoek', 'BWA', 3, 'Gaborone'),
  ('Nepal Investment Bank', 'NPL', 3, 'Kathmandu'),
  ('Bank of Bhutan', 'BTN', 1, 'Thimphu'),
  ('Bank of Maldives', 'MDV', 2, 'Male'),
  ('ACLEDA Bank', 'KHM', 9, 'Phnom Penh'),
  ('Banque pour le Commerce Exterieur Lao', 'LAO', 3, 'Vientiane'),
  ('Myanma Economic Bank', 'MMR', 5, 'Naypyidaw'),
  ('Bank South Pacific', 'PNG', 7, 'Port Moresby'),
  ('Bank of the South Pacific Fiji', 'FJI', 2, 'Suva'),
  ('Khan Bank', 'MNG', 5, 'Ulaanbaatar'),
  ('Bank of Baku', 'AZE', 3, 'Baku'),
  ('Kompanion Bank', 'KGZ', 1, 'Bishkek'),
  ('Orienbank', 'TJK', 1, 'Dushanbe'),
  ('Uzpromstroybank', 'UZB', 5, 'Tashkent'),
  ('Turkmenbashi Bank', 'TKM', 2, 'Ashgabat'),
  ('Belarusbank', 'BLR', 15, 'Minsk'),
  ('Privatbank', 'UKR', 25, 'Kyiv'),
  ('Moldova Agroindbank', 'MDA', 2, 'Chisinau'),
  ('Komercijalna Banka Skopje', 'MKD', 2, 'Skopje'),
  ('Banka Kombetare Tregtare', 'ALB', 4, 'Tirana'),
  ('Crnogorska Komercijalna Banka', 'MNE', 1, 'Podgorica'),
  ('Bank of Valletta Andorra', 'AND', 1, 'Andorra la Vella'),
  ('Compagnie Monegasque de Banque', 'MCO', 8, 'Monaco'),
  ('LGT Bank', 'LIE', 90, 'Vaduz'),
  ('Banca di San Marino', 'SMR', 2, 'San Marino'),
  ('Bank of Sierra Leone', 'SLE', 1, 'Freetown'),
  ('Liberia Bank for Development', 'LBR', 1, 'Monrovia'),
  ('Ecobank Gambia', 'GMB', 1, 'Banjul'),
  ('Banco Interatlantico', 'CPV', 1, 'Praia'),
  ('BCI Guinea-Bissau', 'GNB', 1, 'Bissau'),
  ('Banque Centrale des Comores', 'COM', 1, 'Moroni'),
  ('Bank of Seychelles', 'SYC', 1, 'Victoria'),
  ('BISTP', 'STP', 1, 'Sao Tome'),
  ('National Bank of Vanuatu', 'VUT', 1, 'Port Vila'),
  ('Samoa Commercial Bank', 'WSM', 1, 'Apia'),
  ('Bank of Tonga', 'TON', 1, 'Nuku''alofa'),
  ('Solomon Islands National Bank', 'SLB', 1, 'Honiara'),
  ('Timor Post Bank', 'TLS', 1, 'Dili'),
  ('Standard Bank Eswatini', 'SWZ', 1, 'Mbabane'),
  ('Lesotho Post Bank', 'LSO', 1, 'Maseru'),
  ('Bank of Djibouti', 'DJI', 1, 'Djibouti'),
  ('Banque Mauritanienne', 'MRT', 2, 'Nouakchott'),
  ('Banque Sahelo-Saharienne', 'TCD', 1, 'N''Djamena'),
  ('Banque Commerciale du Niger', 'NER', 2, 'Niamey'),
  ('Coris Bank', 'BFA', 3, 'Ouagadougou'),
  ('Bank of Africa Benin', 'BEN', 2, 'Porto-Novo'),
  ('Societe Generale Cote d''Ivoire', 'CIV', 6, 'Abidjan'),
  ('Banque Atlantique Senegal', 'SEN', 4, 'Dakar'),
  ('GCB Bank', 'GHA', 5, 'Accra'),
  ('Central Bank of Somalia', 'SOM', 1, 'Mogadishu'),
  ('Bank of Khartoum', 'SDN', 3, 'Khartoum'),
  ('Bank of South Sudan', 'SSD', 1, 'Juba'),
  ('Banque Populaire CAR', 'CAF', 1, 'Bangui'),
  ('Housing and Commerce Bank Eritrea', 'ERI', 1, 'Asmara'),
  ('Interbank Burundi', 'BDI', 1, 'Gitega'),
  ('BGFIBank Congo', 'COG', 3, 'Brazzaville'),
  ('Banco Nacional de Guinea Ecuatorial', 'GNQ', 2, 'Malabo'),
  ('Bank of Libya', 'LBY', 20, 'Tripoli'),
  ('Banque de Tunisie', 'TUN', 6, 'Tunis'),
  ('Banque Centrale Populaire', 'DZA', 30, 'Algiers'),
  ('Byblos Bank', 'LBN', 15, 'Beirut'),
  ('Commercial Bank of Syria', 'SYR', 3, 'Damascus'),
  ('Yemen Kuwait Bank', 'YEM', 1, 'Sanaa'),
  ('Da Afghanistan Bank', 'AFG', 2, 'Kabul'),
  ('Bank of Palestine', 'PSE', 6, 'Ramallah'),
  ('Banco Popular de Puerto Rico', 'PRI', 50, 'San Juan'),
  ('Banco Metropolitano', 'CUB', 5, 'Havana'),
  ('Foreign Trade Bank of DPRK', 'PRK', 2, 'Pyongyang'),
  ('Bank of Baku Guinea', 'GIN', 1, 'Conakry'),
  ('Banque Nationale de Haiti', 'HTI', 2, 'Port-au-Prince'),
  ('Belize Bank', 'BLZ', 1, 'Belmopan'),
  ('Republic Bank Suriname', 'SUR', 1, 'Paramaribo'),
  ('Bank of Nassau', 'BHS', 3, 'Nassau'),
  ('Barbados National Bank', 'BRB', 2, 'Bridgetown'),
  ('Banco de Venezuela', 'VEN', 10, 'Caracas'),
  ('Banco Pichincha', 'ECU', 12, 'Quito'),
  ('Banco de Occidente', 'NIC', 2, 'Managua'),
  ('Banco Macro', 'ARG', 15, 'Buenos Aires'),
  ('Bank of Iceland', 'ISL', 10, 'Reykjavik'),
  ('Bank of Cyprus Holdings', 'CYP', 25, 'Nicosia'),
  ('Bank Hapoalim', 'ISR', 190, 'Tel Aviv'),
  ('Macau Chinese Bank', 'MAC', 10, 'Macao'),
  ('Bank of East Asia', 'HKG', 90, 'Hong Kong'),
  ('Baiduri Bank', 'BRN', 4, 'Bandar Seri Begawan'),
  ('KBC Group', 'BEL', 380, 'Brussels'),
  ('Belfius Bank', 'BEL', 210, 'Brussels'),
  ('UniCredit Bulbank', 'BGR', 15, 'Sofia'),
  ('National Bank of Greece', 'GRC', 90, 'Athens'),
  ('Alpha Bank', 'GRC', 80, 'Athens'),
  ('Banque Internationale a Luxembourg', 'LUX', 30, 'Luxembourg'),
  ('Bank of Africa Madagascar', 'MDG', 2, 'Antananarivo'),
  ('ANZ Bank New Zealand', 'NZL', 130, 'Auckland'),
  ('Bank of New Zealand', 'NZL', 90, 'Wellington'),
  ('Caixa Geral de Depositos', 'PRT', 110, 'Lisbon'),
  ('Banco Comercial Portugues', 'PRT', 100, 'Lisbon'),
  ('Slovenska Sporitelna', 'SVK', 25, 'Bratislava');


-- ---- indicator ----
insert into indicator (code, name, unit, definition, perimeter, valuation, caveat, source, vintage) values
  ('GDP_NOM', 'Nominal GDP', 'usd_bn', 'Gross domestic product at current market prices, converted to US dollars at market exchange rates. Not adjusted for purchasing power.', 'whole_economy', 'market', 'Moves with the US dollar. A 10% dollar appreciation mechanically shrinks every other economy''s figure without any change in real output.', 'IMF World Economic Outlook', '2025 estimate'),
  ('POP', 'Population', 'persons_mn', 'Total resident population, mid-year estimate.', NULL, NULL, NULL, 'UN World Population Prospects', '2025 estimate'),
  ('LAND', 'Land area', 'km2', 'Total land area. Excludes inland water bodies where reported separately by the source.', NULL, NULL, 'Definitions of coastline, territorial claims and inland water differ between sources; disputed territories are attributed per UN convention.', 'UN Statistics Division / CIA World Factbook', '2024'),
  ('DEBT_GG', 'General government gross debt', 'pct_gdp', 'Gross debt of the general government sector as a share of GDP. Gross means government-held financial assets are NOT netted off.', 'general_govt', 'nominal', 'The single most misread figure in public finance. Gross, not net: Japan''s net position is materially less severe than this ratio implies. Perimeter varies by country - the IMF itself notes its Fiscal Monitor tables cover a narrower perimeter of general government for China than its Article IV estimates. Published figures for Japan range from roughly 200% to 250% depending on perimeter and valuation, and both cite the IMF. Debt in a currency the government issues is a fundamentally different instrument from debt it must earn or borrow to service; this ratio does not distinguish them.', 'IMF World Economic Outlook / Fiscal Monitor', '2025-26 estimate'),
  ('DEBT_USD', 'Government debt, absolute', 'usd_bn', 'General government gross debt expressed in US dollars. Derived as nominal GDP multiplied by the debt-to-GDP ratio.', 'general_govt', 'nominal', 'A derived figure, not separately sourced. Inherits every caveat of both inputs.', 'Derived from IMF WEO', '2025-26 estimate'),
  ('BANK_ASSETS', 'Bank total assets', 'usd_bn', 'Total assets of the institution for its most recent reporting period: cash, loans, investments, property and equipment.', 'institution', NULL, 'Assets, not market capitalisation - the two rank very differently. ICBC leads on assets while JPMorgan leads on market value. Coverage here is the largest institutions per country and is not exhaustive; smaller markets are represented by one or two banks only.', 'S&P Global Market Intelligence', '2026 ranking, 2025 year-end assets'),
  ('GDP_PC', 'GDP per capita', 'usd', 'Nominal GDP divided by population. Computed in-database, not separately sourced.', 'whole_economy', NULL, 'Inflated for Ireland and Luxembourg by multinational profit booking; GNI per capita is the better living-standards measure for both.', 'Derived', '2025 estimate'),
  ('POP_DENSITY', 'Population density', 'persons_km2', 'Population divided by land area. Computed in-database.', NULL, NULL, 'National averages conceal extreme internal variation - most of Canada, Australia and Russia is effectively unpopulated.', 'Derived', '2025 estimate')
on conflict (code) do nothing;


-- ---- aggregate view ----
create or replace view region_summary as
select
  region,
  count(*)                                   as countries,
  sum(gdp_usd_bn)                            as gdp_usd_bn,
  sum(population_mn)                         as population_mn,
  sum(land_km2)                              as land_km2,
  sum(debt_usd_bn)                           as debt_usd_bn,
  round(sum(gdp_usd_bn)*1000/sum(population_mn), 0)          as gdp_per_capita,
  round(sum(debt_usd_bn)/sum(gdp_usd_bn)*100, 1)             as debt_pct_gdp
from country
group by region;

create or replace view world_totals as
select
  count(*)                as countries,
  sum(gdp_usd_bn)         as gdp_usd_bn,
  sum(population_mn)      as population_mn,
  sum(land_km2)           as land_km2,
  sum(debt_usd_bn)        as debt_usd_bn,
  round(sum(debt_usd_bn)/sum(gdp_usd_bn)*100, 1) as debt_pct_gdp
from country;

-- ---- public read access ----
alter table country  enable row level security;
alter table bank     enable row level security;
alter table currency enable row level security;
alter table indicator enable row level security;

create policy "public read country"   on country   for select using (true);
create policy "public read bank"      on bank      for select using (true);
create policy "public read currency"  on currency  for select using (true);
create policy "public read indicator" on indicator for select using (true);
