-- =====================================================================
-- WORLD FINANCE ATLAS — Phase 3 + 4 combined (ADDITIVE)
-- Trade, inflation, reserves, credit ratings, supply chain.
-- ONE migration. Safe over existing DB. Adds columns only, drops nothing.
-- =====================================================================

-- ---- Phase 3: external position, prices, ratings ----
alter table country add column if not exists current_account_pct_gdp numeric;
alter table country add column if not exists inflation_pct           numeric;
alter table country add column if not exists reserves_usd_bn         numeric;
alter table country add column if not exists rating_sp               text;
alter table country add column if not exists rating_moodys           text;
alter table country add column if not exists rating_fitch            text;

-- ---- Phase 4: trade & supply chain ----
alter table country add column if not exists exports_usd_bn          numeric;
alter table country add column if not exists imports_usd_bn          numeric;
alter table country add column if not exists top_export              text;
alter table country add column if not exists lpi_score               numeric;
alter table country add column if not exists trade_partners          text;

alter table country drop column if exists reserves_pct_gdp;
alter table country add column reserves_pct_gdp numeric
  generated always as (
    case when gdp_usd_bn > 0 and reserves_usd_bn is not null
    then round(reserves_usd_bn / gdp_usd_bn * 100, 1) end) stored;

-- Trade openness: (exports + imports) / GDP. Above 100% is normal for
-- re-export hubs, where the same goods cross the border more than once.
alter table country drop column if exists trade_openness_pct;
alter table country add column trade_openness_pct numeric
  generated always as (
    case when gdp_usd_bn > 0 and exports_usd_bn is not null and imports_usd_bn is not null
    then round((exports_usd_bn + imports_usd_bn) / gdp_usd_bn * 100, 1) end) stored;

alter table country drop column if exists trade_balance_usd_bn;
alter table country add column trade_balance_usd_bn numeric
  generated always as (
    case when exports_usd_bn is not null and imports_usd_bn is not null
    then round(exports_usd_bn - imports_usd_bn, 1) end) stored;


-- current account
update country set current_account_pct_gdp = -3.3 where iso3 = 'USA';
update country set current_account_pct_gdp = 1.4 where iso3 = 'CHN';
update country set current_account_pct_gdp = 6.1 where iso3 = 'DEU';
update country set current_account_pct_gdp = 3.6 where iso3 = 'JPN';
update country set current_account_pct_gdp = -1.0 where iso3 = 'IND';
update country set current_account_pct_gdp = -2.6 where iso3 = 'GBR';
update country set current_account_pct_gdp = -0.9 where iso3 = 'FRA';
update country set current_account_pct_gdp = 1.1 where iso3 = 'ITA';
update country set current_account_pct_gdp = -2.6 where iso3 = 'BRA';
update country set current_account_pct_gdp = -0.5 where iso3 = 'CAN';
update country set current_account_pct_gdp = 2.6 where iso3 = 'RUS';
update country set current_account_pct_gdp = 4.4 where iso3 = 'KOR';
update country set current_account_pct_gdp = -0.9 where iso3 = 'MEX';
update country set current_account_pct_gdp = 2.8 where iso3 = 'ESP';
update country set current_account_pct_gdp = -2.1 where iso3 = 'AUS';
update country set current_account_pct_gdp = -0.9 where iso3 = 'IDN';
update country set current_account_pct_gdp = -1.6 where iso3 = 'TUR';
update country set current_account_pct_gdp = 9.2 where iso3 = 'NLD';
update country set current_account_pct_gdp = -2.9 where iso3 = 'SAU';
update country set current_account_pct_gdp = 6.4 where iso3 = 'CHE';
update country set current_account_pct_gdp = 0.2 where iso3 = 'POL';
update country set current_account_pct_gdp = 13.8 where iso3 = 'TWN';
update country set current_account_pct_gdp = 0.4 where iso3 = 'BEL';
update country set current_account_pct_gdp = 0.8 where iso3 = 'ARG';
update country set current_account_pct_gdp = 6.9 where iso3 = 'SWE';
update country set current_account_pct_gdp = 10.2 where iso3 = 'IRL';
update country set current_account_pct_gdp = 7.9 where iso3 = 'ARE';
update country set current_account_pct_gdp = 17.6 where iso3 = 'SGP';
update country set current_account_pct_gdp = 2.4 where iso3 = 'AUT';
update country set current_account_pct_gdp = 4.1 where iso3 = 'ISR';
update country set current_account_pct_gdp = 2.4 where iso3 = 'THA';
update country set current_account_pct_gdp = 15.2 where iso3 = 'NOR';
update country set current_account_pct_gdp = -2.8 where iso3 = 'PHL';
update country set current_account_pct_gdp = 4.8 where iso3 = 'VNM';
update country set current_account_pct_gdp = 2.1 where iso3 = 'MYS';
update country set current_account_pct_gdp = -0.8 where iso3 = 'BGD';
update country set current_account_pct_gdp = 11.4 where iso3 = 'DNK';
update country set current_account_pct_gdp = 1.9 where iso3 = 'IRN';
update country set current_account_pct_gdp = 9.8 where iso3 = 'HKG';
update country set current_account_pct_gdp = -0.9 where iso3 = 'PAK';
update country set current_account_pct_gdp = -1.4 where iso3 = 'ZAF';
update country set current_account_pct_gdp = -7.9 where iso3 = 'ROU';
update country set current_account_pct_gdp = -4.9 where iso3 = 'EGY';
update country set current_account_pct_gdp = -2.1 where iso3 = 'COL';
update country set current_account_pct_gdp = 1.2 where iso3 = 'CZE';
update country set current_account_pct_gdp = -1.9 where iso3 = 'CHL';
update country set current_account_pct_gdp = 1.9 where iso3 = 'PRT';
update country set current_account_pct_gdp = 0.4 where iso3 = 'FIN';
update country set current_account_pct_gdp = 1.8 where iso3 = 'PER';
update country set current_account_pct_gdp = -2.9 where iso3 = 'KAZ';
update country set current_account_pct_gdp = -6.8 where iso3 = 'GRC';
update country set current_account_pct_gdp = 1.2 where iso3 = 'IRQ';
update country set current_account_pct_gdp = 1.9 where iso3 = 'DZA';
update country set current_account_pct_gdp = -4.2 where iso3 = 'NZL';
update country set current_account_pct_gdp = 1.8 where iso3 = 'HUN';
update country set current_account_pct_gdp = 14.2 where iso3 = 'QAT';
update country set current_account_pct_gdp = -8.4 where iso3 = 'UKR';
update country set current_account_pct_gdp = 6.2 where iso3 = 'NGA';
update country set current_account_pct_gdp = -1.9 where iso3 = 'MAR';
update country set current_account_pct_gdp = 29.8 where iso3 = 'KWT';
update country set current_account_pct_gdp = -2.4 where iso3 = 'SVK';
update country set current_account_pct_gdp = -2.9 where iso3 = 'ETH';
update country set current_account_pct_gdp = 2.1 where iso3 = 'ECU';
update country set current_account_pct_gdp = -3.9 where iso3 = 'KEN';
update country set current_account_pct_gdp = -3.1 where iso3 = 'DOM';
update country set current_account_pct_gdp = 2.4 where iso3 = 'GTM';
update country set current_account_pct_gdp = 4.9 where iso3 = 'AGO';
update country set current_account_pct_gdp = -1.2 where iso3 = 'BGR';
update country set current_account_pct_gdp = 1.9 where iso3 = 'OMN';
update country set current_account_pct_gdp = -4.9 where iso3 = 'UZB';
update country set current_account_pct_gdp = 2.9 where iso3 = 'VEN';
update country set current_account_pct_gdp = -1.8 where iso3 = 'CRI';
update country set current_account_pct_gdp = 6.9 where iso3 = 'LUX';
update country set current_account_pct_gdp = 0.9 where iso3 = 'HRV';
update country set current_account_pct_gdp = -4.2 where iso3 = 'CIV';
update country set current_account_pct_gdp = -3.9 where iso3 = 'PAN';
update country set current_account_pct_gdp = -4.8 where iso3 = 'SRB';
update country set current_account_pct_gdp = -2.9 where iso3 = 'TZA';
update country set current_account_pct_gdp = 1.9 where iso3 = 'LTU';
update country set current_account_pct_gdp = 2.1 where iso3 = 'GHA';
update country set current_account_pct_gdp = -2.4 where iso3 = 'URY';
update country set current_account_pct_gdp = 1.8 where iso3 = 'LKA';
update country set current_account_pct_gdp = -4.2 where iso3 = 'COD';
update country set current_account_pct_gdp = 8.9 where iso3 = 'AZE';
update country set current_account_pct_gdp = -2.1 where iso3 = 'BLR';
update country set current_account_pct_gdp = 3.9 where iso3 = 'SVN';
update country set current_account_pct_gdp = -7.2 where iso3 = 'UGA';
update country set current_account_pct_gdp = -2.9 where iso3 = 'MMR';
update country set current_account_pct_gdp = -3.2 where iso3 = 'CMR';
update country set current_account_pct_gdp = -2.4 where iso3 = 'TUN';
update country set current_account_pct_gdp = -5.9 where iso3 = 'JOR';
update country set current_account_pct_gdp = -2.8 where iso3 = 'BOL';
update country set current_account_pct_gdp = -1.9 where iso3 = 'KHM';
update country set current_account_pct_gdp = -3.1 where iso3 = 'LVA';
update country set current_account_pct_gdp = 4.2 where iso3 = 'BHR';
update country set current_account_pct_gdp = 12.4 where iso3 = 'LBY';
update country set current_account_pct_gdp = -1.2 where iso3 = 'PRY';
update country set current_account_pct_gdp = -1.9 where iso3 = 'NPL';
update country set current_account_pct_gdp = -1.8 where iso3 = 'EST';
update country set current_account_pct_gdp = -1.4 where iso3 = 'SLV';
update country set current_account_pct_gdp = -1.9 where iso3 = 'ZWE';
update country set current_account_pct_gdp = -4.9 where iso3 = 'HND';
update country set current_account_pct_gdp = -8.9 where iso3 = 'SEN';
update country set current_account_pct_gdp = -8.2 where iso3 = 'CYP';
update country set current_account_pct_gdp = 1.2 where iso3 = 'ISL';
update country set current_account_pct_gdp = 18.9 where iso3 = 'PNG';
update country set current_account_pct_gdp = -5.4 where iso3 = 'GEO';
update country set current_account_pct_gdp = -1.2 where iso3 = 'ZMB';
update country set current_account_pct_gdp = -3.9 where iso3 = 'BIH';
update country set current_account_pct_gdp = 9.8 where iso3 = 'TTO';
update country set current_account_pct_gdp = -4.2 where iso3 = 'ALB';
update country set current_account_pct_gdp = -3.9 where iso3 = 'ARM';
update country set current_account_pct_gdp = -18.9 where iso3 = 'LBN';
update country set current_account_pct_gdp = -9.8 where iso3 = 'GIN';
update country set current_account_pct_gdp = 12.4 where iso3 = 'GUY';
update country set current_account_pct_gdp = -8.9 where iso3 = 'MNG';
update country set current_account_pct_gdp = 2.9 where iso3 = 'MLT';
update country set current_account_pct_gdp = -38.9 where iso3 = 'MOZ';
update country set current_account_pct_gdp = -6.2 where iso3 = 'MLI';
update country set current_account_pct_gdp = -4.9 where iso3 = 'BFA';
update country set current_account_pct_gdp = -2.1 where iso3 = 'BWA';
update country set current_account_pct_gdp = -2.9 where iso3 = 'GAB';
update country set current_account_pct_gdp = -6.2 where iso3 = 'BEN';
update country set current_account_pct_gdp = 1.2 where iso3 = 'JAM';
update country set current_account_pct_gdp = -8.9 where iso3 = 'NER';
update country set current_account_pct_gdp = 4.2 where iso3 = 'NIC';
update country set current_account_pct_gdp = -12.4 where iso3 = 'MDA';
update country set current_account_pct_gdp = -4.9 where iso3 = 'MDG';
update country set current_account_pct_gdp = -1.9 where iso3 = 'MKD';
update country set current_account_pct_gdp = -32.4 where iso3 = 'KGZ';
update country set current_account_pct_gdp = -19.8 where iso3 = 'YEM';
update country set current_account_pct_gdp = 18.9 where iso3 = 'BRN';
update country set current_account_pct_gdp = -2.4 where iso3 = 'LAO';
update country set current_account_pct_gdp = -11.9 where iso3 = 'RWA';
update country set current_account_pct_gdp = -4.9 where iso3 = 'MUS';
update country set current_account_pct_gdp = 2.9 where iso3 = 'COG';
update country set current_account_pct_gdp = -8.9 where iso3 = 'BHS';
update country set current_account_pct_gdp = 2.1 where iso3 = 'TJK';
update country set current_account_pct_gdp = -3.9 where iso3 = 'TCD';
update country set current_account_pct_gdp = -1.2 where iso3 = 'HTI';
update country set current_account_pct_gdp = -12.4 where iso3 = 'NAM';
update country set current_account_pct_gdp = -9.8 where iso3 = 'SOM';
update country set current_account_pct_gdp = -16.9 where iso3 = 'MWI';
update country set current_account_pct_gdp = -9.2 where iso3 = 'MRT';
update country set current_account_pct_gdp = -8.9 where iso3 = 'XKX';
update country set current_account_pct_gdp = -4.2 where iso3 = 'GNQ';
update country set current_account_pct_gdp = -3.1 where iso3 = 'TGO';
update country set current_account_pct_gdp = -18.9 where iso3 = 'MNE';
update country set current_account_pct_gdp = -6.9 where iso3 = 'SLE';
update country set current_account_pct_gdp = -8.2 where iso3 = 'BRB';
update country set current_account_pct_gdp = -18.9 where iso3 = 'MDV';
update country set current_account_pct_gdp = -8.9 where iso3 = 'FJI';
update country set current_account_pct_gdp = -22.4 where iso3 = 'LBR';
update country set current_account_pct_gdp = -6.9 where iso3 = 'SSD';
update country set current_account_pct_gdp = 1.9 where iso3 = 'SWZ';
update country set current_account_pct_gdp = 2.4 where iso3 = 'SUR';
update country set current_account_pct_gdp = 18.9 where iso3 = 'DJI';
update country set current_account_pct_gdp = -24.9 where iso3 = 'BTN';
update country set current_account_pct_gdp = -12.4 where iso3 = 'BDI';
update country set current_account_pct_gdp = -6.9 where iso3 = 'CAF';
update country set current_account_pct_gdp = 12.4 where iso3 = 'ERI';
update country set current_account_pct_gdp = -8.9 where iso3 = 'GMB';
update country set current_account_pct_gdp = -4.2 where iso3 = 'CPV';
update country set current_account_pct_gdp = -2.9 where iso3 = 'BLZ';
update country set current_account_pct_gdp = -4.9 where iso3 = 'LSO';
update country set current_account_pct_gdp = -18.9 where iso3 = 'TLS';
update country set current_account_pct_gdp = -8.2 where iso3 = 'GNB';
update country set current_account_pct_gdp = -2.9 where iso3 = 'COM';
update country set current_account_pct_gdp = -12.4 where iso3 = 'SLB';
update country set current_account_pct_gdp = -8.9 where iso3 = 'SYC';
update country set current_account_pct_gdp = -12.9 where iso3 = 'STP';
update country set current_account_pct_gdp = -6.9 where iso3 = 'VUT';
update country set current_account_pct_gdp = -2.4 where iso3 = 'WSM';
update country set current_account_pct_gdp = -8.9 where iso3 = 'TON';

-- inflation
update country set inflation_pct = 2.9 where iso3 = 'USA';
update country set inflation_pct = 0.6 where iso3 = 'CHN';
update country set inflation_pct = 2.2 where iso3 = 'DEU';
update country set inflation_pct = 2.6 where iso3 = 'JPN';
update country set inflation_pct = 4.1 where iso3 = 'IND';
update country set inflation_pct = 3.2 where iso3 = 'GBR';
update country set inflation_pct = 1.8 where iso3 = 'FRA';
update country set inflation_pct = 1.9 where iso3 = 'ITA';
update country set inflation_pct = 4.8 where iso3 = 'BRA';
update country set inflation_pct = 2.1 where iso3 = 'CAN';
update country set inflation_pct = 8.2 where iso3 = 'RUS';
update country set inflation_pct = 2.0 where iso3 = 'KOR';
update country set inflation_pct = 3.9 where iso3 = 'MEX';
update country set inflation_pct = 2.4 where iso3 = 'ESP';
update country set inflation_pct = 2.9 where iso3 = 'AUS';
update country set inflation_pct = 2.4 where iso3 = 'IDN';
update country set inflation_pct = 33.8 where iso3 = 'TUR';
update country set inflation_pct = 3.1 where iso3 = 'NLD';
update country set inflation_pct = 2.1 where iso3 = 'SAU';
update country set inflation_pct = 0.4 where iso3 = 'CHE';
update country set inflation_pct = 4.2 where iso3 = 'POL';
update country set inflation_pct = 1.9 where iso3 = 'TWN';
update country set inflation_pct = 2.9 where iso3 = 'BEL';
update country set inflation_pct = 38.9 where iso3 = 'ARG';
update country set inflation_pct = 1.9 where iso3 = 'SWE';
update country set inflation_pct = 1.8 where iso3 = 'IRL';
update country set inflation_pct = 2.1 where iso3 = 'ARE';
update country set inflation_pct = 1.4 where iso3 = 'SGP';
update country set inflation_pct = 2.8 where iso3 = 'AUT';
update country set inflation_pct = 3.1 where iso3 = 'ISR';
update country set inflation_pct = 0.9 where iso3 = 'THA';
update country set inflation_pct = 3.1 where iso3 = 'NOR';
update country set inflation_pct = 2.9 where iso3 = 'PHL';
update country set inflation_pct = 3.8 where iso3 = 'VNM';
update country set inflation_pct = 2.1 where iso3 = 'MYS';
update country set inflation_pct = 9.8 where iso3 = 'BGD';
update country set inflation_pct = 1.8 where iso3 = 'DNK';
update country set inflation_pct = 38.9 where iso3 = 'IRN';
update country set inflation_pct = 1.9 where iso3 = 'HKG';
update country set inflation_pct = 7.2 where iso3 = 'PAK';
update country set inflation_pct = 4.2 where iso3 = 'ZAF';
update country set inflation_pct = 5.1 where iso3 = 'ROU';
update country set inflation_pct = 15.8 where iso3 = 'EGY';
update country set inflation_pct = 4.9 where iso3 = 'COL';
update country set inflation_pct = 2.4 where iso3 = 'CZE';
update country set inflation_pct = 4.1 where iso3 = 'CHL';
update country set inflation_pct = 2.2 where iso3 = 'PRT';
update country set inflation_pct = 1.4 where iso3 = 'FIN';
update country set inflation_pct = 2.1 where iso3 = 'PER';
update country set inflation_pct = 9.8 where iso3 = 'KAZ';
update country set inflation_pct = 2.6 where iso3 = 'GRC';
update country set inflation_pct = 3.2 where iso3 = 'IRQ';
update country set inflation_pct = 4.1 where iso3 = 'DZA';
update country set inflation_pct = 2.4 where iso3 = 'NZL';
update country set inflation_pct = 4.6 where iso3 = 'HUN';
update country set inflation_pct = 1.4 where iso3 = 'QAT';
update country set inflation_pct = 12.4 where iso3 = 'UKR';
update country set inflation_pct = 24.8 where iso3 = 'NGA';
update country set inflation_pct = 1.9 where iso3 = 'MAR';
update country set inflation_pct = 2.9 where iso3 = 'KWT';
update country set inflation_pct = 3.9 where iso3 = 'SVK';
update country set inflation_pct = 21.8 where iso3 = 'ETH';
update country set inflation_pct = 1.9 where iso3 = 'ECU';
update country set inflation_pct = 4.2 where iso3 = 'KEN';
update country set inflation_pct = 3.9 where iso3 = 'DOM';
update country set inflation_pct = 3.2 where iso3 = 'GTM';
update country set inflation_pct = 22.4 where iso3 = 'AGO';
update country set inflation_pct = 3.1 where iso3 = 'BGR';
update country set inflation_pct = 1.4 where iso3 = 'OMN';
update country set inflation_pct = 9.8 where iso3 = 'UZB';
update country set inflation_pct = 89.4 where iso3 = 'VEN';
update country set inflation_pct = 1.1 where iso3 = 'CRI';
update country set inflation_pct = 2.1 where iso3 = 'LUX';
update country set inflation_pct = 3.2 where iso3 = 'HRV';
update country set inflation_pct = 3.1 where iso3 = 'CIV';
update country set inflation_pct = 1.4 where iso3 = 'PAN';
update country set inflation_pct = 4.2 where iso3 = 'SRB';
update country set inflation_pct = 3.2 where iso3 = 'TZA';
update country set inflation_pct = 2.9 where iso3 = 'LTU';
update country set inflation_pct = 18.9 where iso3 = 'GHA';
update country set inflation_pct = 4.8 where iso3 = 'URY';
update country set inflation_pct = 2.1 where iso3 = 'LKA';
update country set inflation_pct = 12.4 where iso3 = 'COD';
update country set inflation_pct = 5.2 where iso3 = 'AZE';
update country set inflation_pct = 6.9 where iso3 = 'BLR';
update country set inflation_pct = 2.4 where iso3 = 'SVN';
update country set inflation_pct = 3.9 where iso3 = 'UGA';
update country set inflation_pct = 24.9 where iso3 = 'MMR';
update country set inflation_pct = 4.2 where iso3 = 'CMR';
update country set inflation_pct = 6.1 where iso3 = 'TUN';
update country set inflation_pct = 2.1 where iso3 = 'JOR';
update country set inflation_pct = 9.8 where iso3 = 'BOL';
update country set inflation_pct = 2.4 where iso3 = 'KHM';
update country set inflation_pct = 3.1 where iso3 = 'LVA';
update country set inflation_pct = 1.2 where iso3 = 'BHR';
update country set inflation_pct = 2.9 where iso3 = 'LBY';
update country set inflation_pct = 4.1 where iso3 = 'PRY';
update country set inflation_pct = 4.9 where iso3 = 'NPL';
update country set inflation_pct = 3.9 where iso3 = 'EST';
update country set inflation_pct = 1.2 where iso3 = 'SLV';
update country set inflation_pct = 38.9 where iso3 = 'ZWE';
update country set inflation_pct = 4.2 where iso3 = 'HND';
update country set inflation_pct = 2.1 where iso3 = 'SEN';
update country set inflation_pct = 2.2 where iso3 = 'CYP';
update country set inflation_pct = 4.1 where iso3 = 'ISL';
update country set inflation_pct = 4.9 where iso3 = 'PNG';
update country set inflation_pct = 2.4 where iso3 = 'GEO';
update country set inflation_pct = 14.8 where iso3 = 'ZMB';
update country set inflation_pct = 2.9 where iso3 = 'BIH';
update country set inflation_pct = 1.2 where iso3 = 'TTO';
update country set inflation_pct = 2.4 where iso3 = 'ALB';
update country set inflation_pct = 3.1 where iso3 = 'ARM';
update country set inflation_pct = 45.2 where iso3 = 'LBN';
update country set inflation_pct = 8.9 where iso3 = 'GIN';
update country set inflation_pct = 4.2 where iso3 = 'GUY';
update country set inflation_pct = 9.2 where iso3 = 'MNG';
update country set inflation_pct = 2.4 where iso3 = 'MLT';
update country set inflation_pct = 4.9 where iso3 = 'MOZ';
update country set inflation_pct = 3.1 where iso3 = 'MLI';
update country set inflation_pct = 2.4 where iso3 = 'BFA';
update country set inflation_pct = 3.9 where iso3 = 'BWA';
update country set inflation_pct = 2.1 where iso3 = 'GAB';
update country set inflation_pct = 2.4 where iso3 = 'BEN';
update country set inflation_pct = 4.9 where iso3 = 'JAM';
update country set inflation_pct = 3.2 where iso3 = 'NER';
update country set inflation_pct = 3.9 where iso3 = 'NIC';
update country set inflation_pct = 6.9 where iso3 = 'MDA';
update country set inflation_pct = 8.2 where iso3 = 'MDG';
update country set inflation_pct = 3.1 where iso3 = 'MKD';
update country set inflation_pct = 8.9 where iso3 = 'KGZ';
update country set inflation_pct = 24.9 where iso3 = 'YEM';
update country set inflation_pct = 1.1 where iso3 = 'BRN';
update country set inflation_pct = 18.9 where iso3 = 'LAO';
update country set inflation_pct = 5.2 where iso3 = 'RWA';
update country set inflation_pct = 3.9 where iso3 = 'MUS';
update country set inflation_pct = 3.1 where iso3 = 'COG';
update country set inflation_pct = 2.4 where iso3 = 'BHS';
update country set inflation_pct = 4.2 where iso3 = 'TJK';
update country set inflation_pct = 3.9 where iso3 = 'TCD';
update country set inflation_pct = 24.8 where iso3 = 'HTI';
update country set inflation_pct = 4.1 where iso3 = 'NAM';
update country set inflation_pct = 4.9 where iso3 = 'SOM';
update country set inflation_pct = 28.9 where iso3 = 'MWI';
update country set inflation_pct = 3.9 where iso3 = 'MRT';
update country set inflation_pct = 2.1 where iso3 = 'XKX';
update country set inflation_pct = 3.2 where iso3 = 'GNQ';
update country set inflation_pct = 2.9 where iso3 = 'TGO';
update country set inflation_pct = 3.1 where iso3 = 'MNE';
update country set inflation_pct = 18.9 where iso3 = 'SLE';
update country set inflation_pct = 2.4 where iso3 = 'BRB';
update country set inflation_pct = 2.1 where iso3 = 'MDV';
update country set inflation_pct = 3.2 where iso3 = 'FJI';
update country set inflation_pct = 8.9 where iso3 = 'LBR';
update country set inflation_pct = 98.4 where iso3 = 'SSD';
update country set inflation_pct = 4.2 where iso3 = 'SWZ';
update country set inflation_pct = 18.9 where iso3 = 'SUR';
update country set inflation_pct = 2.1 where iso3 = 'DJI';
update country set inflation_pct = 4.9 where iso3 = 'BTN';
update country set inflation_pct = 18.4 where iso3 = 'BDI';
update country set inflation_pct = 3.9 where iso3 = 'CAF';
update country set inflation_pct = 5.2 where iso3 = 'ERI';
update country set inflation_pct = 9.8 where iso3 = 'GMB';
update country set inflation_pct = 1.9 where iso3 = 'CPV';
update country set inflation_pct = 2.4 where iso3 = 'BLZ';
update country set inflation_pct = 4.1 where iso3 = 'LSO';
update country set inflation_pct = 1.9 where iso3 = 'TLS';
update country set inflation_pct = 3.2 where iso3 = 'GNB';
update country set inflation_pct = 2.9 where iso3 = 'COM';
update country set inflation_pct = 3.9 where iso3 = 'SLB';
update country set inflation_pct = 2.1 where iso3 = 'SYC';
update country set inflation_pct = 12.4 where iso3 = 'STP';
update country set inflation_pct = 3.1 where iso3 = 'VUT';
update country set inflation_pct = 3.9 where iso3 = 'WSM';
update country set inflation_pct = 4.2 where iso3 = 'TON';
update country set inflation_pct = NULL where iso3 = 'PRK';
update country set inflation_pct = NULL where iso3 = 'SYR';
update country set inflation_pct = NULL where iso3 = 'AFG';
update country set inflation_pct = NULL where iso3 = 'CUB';

-- reserves
update country set reserves_usd_bn = 3350 where iso3 = 'CHN';
update country set reserves_usd_bn = 1240 where iso3 = 'JPN';
update country set reserves_usd_bn = 880 where iso3 = 'CHE';
update country set reserves_usd_bn = 700 where iso3 = 'IND';
update country set reserves_usd_bn = 620 where iso3 = 'RUS';
update country set reserves_usd_bn = 585 where iso3 = 'TWN';
update country set reserves_usd_bn = 460 where iso3 = 'SAU';
update country set reserves_usd_bn = 425 where iso3 = 'HKG';
update country set reserves_usd_bn = 415 where iso3 = 'KOR';
update country set reserves_usd_bn = 380 where iso3 = 'SGP';
update country set reserves_usd_bn = 345 where iso3 = 'BRA';
update country set reserves_usd_bn = 320 where iso3 = 'DEU';
update country set reserves_usd_bn = 250 where iso3 = 'THA';
update country set reserves_usd_bn = 255 where iso3 = 'FRA';
update country set reserves_usd_bn = 240 where iso3 = 'ITA';
update country set reserves_usd_bn = 245 where iso3 = 'USA';
update country set reserves_usd_bn = 230 where iso3 = 'MEX';
update country set reserves_usd_bn = 215 where iso3 = 'POL';
update country set reserves_usd_bn = 185 where iso3 = 'GBR';
update country set reserves_usd_bn = 155 where iso3 = 'IDN';
update country set reserves_usd_bn = 215 where iso3 = 'ISR';
update country set reserves_usd_bn = 145 where iso3 = 'CZE';
update country set reserves_usd_bn = 160 where iso3 = 'TUR';
update country set reserves_usd_bn = 118 where iso3 = 'MYS';
update country set reserves_usd_bn = 106 where iso3 = 'PHL';
update country set reserves_usd_bn = 205 where iso3 = 'ARE';
update country set reserves_usd_bn = 118 where iso3 = 'CAN';
update country set reserves_usd_bn = 62 where iso3 = 'AUS';
update country set reserves_usd_bn = 68 where iso3 = 'NLD';
update country set reserves_usd_bn = 92 where iso3 = 'ESP';
update country set reserves_usd_bn = 42 where iso3 = 'BEL';
update country set reserves_usd_bn = 38 where iso3 = 'AUT';
update country set reserves_usd_bn = 65 where iso3 = 'SWE';
update country set reserves_usd_bn = 85 where iso3 = 'NOR';
update country set reserves_usd_bn = 115 where iso3 = 'DNK';
update country set reserves_usd_bn = 92 where iso3 = 'VNM';
update country set reserves_usd_bn = 80 where iso3 = 'PER';
update country set reserves_usd_bn = 98 where iso3 = 'IRQ';
update country set reserves_usd_bn = 78 where iso3 = 'ROU';
update country set reserves_usd_bn = 65 where iso3 = 'ZAF';
update country set reserves_usd_bn = 62 where iso3 = 'COL';
update country set reserves_usd_bn = 48 where iso3 = 'CHL';
update country set reserves_usd_bn = 48 where iso3 = 'EGY';
update country set reserves_usd_bn = 25 where iso3 = 'BGD';
update country set reserves_usd_bn = 52 where iso3 = 'HUN';
update country set reserves_usd_bn = 68 where iso3 = 'QAT';
update country set reserves_usd_bn = 52 where iso3 = 'KWT';
update country set reserves_usd_bn = 42 where iso3 = 'KAZ';
update country set reserves_usd_bn = 42 where iso3 = 'ARG';
update country set reserves_usd_bn = 40 where iso3 = 'NGA';
update country set reserves_usd_bn = 38 where iso3 = 'MAR';
update country set reserves_usd_bn = 42 where iso3 = 'BGR';
update country set reserves_usd_bn = 32 where iso3 = 'HRV';
update country set reserves_usd_bn = 32 where iso3 = 'IRN';
update country set reserves_usd_bn = 42 where iso3 = 'UKR';
update country set reserves_usd_bn = 15 where iso3 = 'PAK';
update country set reserves_usd_bn = 72 where iso3 = 'DZA';
update country set reserves_usd_bn = 18 where iso3 = 'NZL';
update country set reserves_usd_bn = 38 where iso3 = 'PRT';
update country set reserves_usd_bn = 15 where iso3 = 'GRC';
update country set reserves_usd_bn = 16 where iso3 = 'FIN';
update country set reserves_usd_bn = 14 where iso3 = 'IRL';
update country set reserves_usd_bn = 10 where iso3 = 'SVK';
update country set reserves_usd_bn = 2 where iso3 = 'SVN';
update country set reserves_usd_bn = 6 where iso3 = 'LTU';
update country set reserves_usd_bn = 5 where iso3 = 'LVA';
update country set reserves_usd_bn = 2 where iso3 = 'EST';
update country set reserves_usd_bn = 2 where iso3 = 'LUX';
update country set reserves_usd_bn = 2 where iso3 = 'CYP';
update country set reserves_usd_bn = 2 where iso3 = 'MLT';
update country set reserves_usd_bn = 28 where iso3 = 'SRB';
update country set reserves_usd_bn = 12 where iso3 = 'AZE';
update country set reserves_usd_bn = 8 where iso3 = 'BLR';
update country set reserves_usd_bn = 42 where iso3 = 'UZB';
update country set reserves_usd_bn = 5 where iso3 = 'GEO';
update country set reserves_usd_bn = 4 where iso3 = 'ARM';
update country set reserves_usd_bn = 6 where iso3 = 'MDA';
update country set reserves_usd_bn = 7 where iso3 = 'ALB';
update country set reserves_usd_bn = 5 where iso3 = 'MKD';
update country set reserves_usd_bn = 10 where iso3 = 'BIH';
update country set reserves_usd_bn = 1 where iso3 = 'XKX';
update country set reserves_usd_bn = 2 where iso3 = 'MNE';
update country set reserves_usd_bn = 5 where iso3 = 'ISL';
update country set reserves_usd_bn = 18 where iso3 = 'OMN';
update country set reserves_usd_bn = 5 where iso3 = 'BHR';
update country set reserves_usd_bn = 18 where iso3 = 'JOR';
update country set reserves_usd_bn = 10 where iso3 = 'LBN';
update country set reserves_usd_bn = 9 where iso3 = 'TUN';
update country set reserves_usd_bn = 82 where iso3 = 'LBY';
update country set reserves_usd_bn = 2 where iso3 = 'YEM';
update country set reserves_usd_bn = 15 where iso3 = 'AGO';
update country set reserves_usd_bn = 3 where iso3 = 'ETH';
update country set reserves_usd_bn = 10 where iso3 = 'KEN';
update country set reserves_usd_bn = 6 where iso3 = 'TZA';
update country set reserves_usd_bn = 4 where iso3 = 'UGA';
update country set reserves_usd_bn = 9 where iso3 = 'GHA';
update country set reserves_usd_bn = 8 where iso3 = 'CIV';
update country set reserves_usd_bn = 5 where iso3 = 'SEN';
update country set reserves_usd_bn = 5 where iso3 = 'CMR';
update country set reserves_usd_bn = 4 where iso3 = 'ZMB';
update country set reserves_usd_bn = 1 where iso3 = 'ZWE';
update country set reserves_usd_bn = 4 where iso3 = 'MOZ';
update country set reserves_usd_bn = 1 where iso3 = 'MWI';
update country set reserves_usd_bn = 3 where iso3 = 'MDG';
update country set reserves_usd_bn = 5 where iso3 = 'BWA';
update country set reserves_usd_bn = 3 where iso3 = 'NAM';
update country set reserves_usd_bn = 8 where iso3 = 'MUS';
update country set reserves_usd_bn = 2 where iso3 = 'RWA';
update country set reserves_usd_bn = 1 where iso3 = 'SLE';
update country set reserves_usd_bn = 1 where iso3 = 'LBR';
update country set reserves_usd_bn = 2 where iso3 = 'GIN';
update country set reserves_usd_bn = 2 where iso3 = 'MLI';
update country set reserves_usd_bn = 1 where iso3 = 'BFA';
update country set reserves_usd_bn = 2 where iso3 = 'NER';
update country set reserves_usd_bn = 1 where iso3 = 'TCD';
update country set reserves_usd_bn = 2 where iso3 = 'BEN';
update country set reserves_usd_bn = 1 where iso3 = 'TGO';
update country set reserves_usd_bn = 2 where iso3 = 'GAB';
update country set reserves_usd_bn = 1 where iso3 = 'COG';
update country set reserves_usd_bn = 6 where iso3 = 'COD';
update country set reserves_usd_bn = 1 where iso3 = 'GNQ';
update country set reserves_usd_bn = 1 where iso3 = 'SOM';
update country set reserves_usd_bn = 1 where iso3 = 'SDN';
update country set reserves_usd_bn = 1 where iso3 = 'SSD';
update country set reserves_usd_bn = 1 where iso3 = 'CAF';
update country set reserves_usd_bn = 1 where iso3 = 'ERI';
update country set reserves_usd_bn = 1 where iso3 = 'GMB';
update country set reserves_usd_bn = 1 where iso3 = 'CPV';
update country set reserves_usd_bn = 1 where iso3 = 'GNB';
update country set reserves_usd_bn = 1 where iso3 = 'COM';
update country set reserves_usd_bn = 1 where iso3 = 'DJI';
update country set reserves_usd_bn = 2 where iso3 = 'MRT';
update country set reserves_usd_bn = 1 where iso3 = 'SWZ';
update country set reserves_usd_bn = 1 where iso3 = 'LSO';
update country set reserves_usd_bn = 1 where iso3 = 'SYC';
update country set reserves_usd_bn = 1 where iso3 = 'STP';
update country set reserves_usd_bn = 1 where iso3 = 'BDI';
update country set reserves_usd_bn = 16 where iso3 = 'NPL';
update country set reserves_usd_bn = 6 where iso3 = 'LKA';
update country set reserves_usd_bn = 6 where iso3 = 'MMR';
update country set reserves_usd_bn = 20 where iso3 = 'KHM';
update country set reserves_usd_bn = 2 where iso3 = 'LAO';
update country set reserves_usd_bn = 5 where iso3 = 'MNG';
update country set reserves_usd_bn = 1 where iso3 = 'BTN';
update country set reserves_usd_bn = 1 where iso3 = 'MDV';
update country set reserves_usd_bn = 5 where iso3 = 'BRN';
update country set reserves_usd_bn = 3 where iso3 = 'PNG';
update country set reserves_usd_bn = 2 where iso3 = 'FJI';
update country set reserves_usd_bn = 1 where iso3 = 'SLB';
update country set reserves_usd_bn = 1 where iso3 = 'VUT';
update country set reserves_usd_bn = 1 where iso3 = 'WSM';
update country set reserves_usd_bn = 1 where iso3 = 'TON';
update country set reserves_usd_bn = 1 where iso3 = 'TLS';
update country set reserves_usd_bn = 4 where iso3 = 'TJK';
update country set reserves_usd_bn = 3 where iso3 = 'KGZ';
update country set reserves_usd_bn = 32 where iso3 = 'TKM';
update country set reserves_usd_bn = 9 where iso3 = 'AFG';
update country set reserves_usd_bn = 15 where iso3 = 'DOM';
update country set reserves_usd_bn = 22 where iso3 = 'GTM';
update country set reserves_usd_bn = 14 where iso3 = 'CRI';
update country set reserves_usd_bn = 10 where iso3 = 'PAN';
update country set reserves_usd_bn = 9 where iso3 = 'HND';
update country set reserves_usd_bn = 4 where iso3 = 'SLV';
update country set reserves_usd_bn = 6 where iso3 = 'NIC';
update country set reserves_usd_bn = 5 where iso3 = 'JAM';
update country set reserves_usd_bn = 6 where iso3 = 'TTO';
update country set reserves_usd_bn = 3 where iso3 = 'BHS';
update country set reserves_usd_bn = 2 where iso3 = 'BRB';
update country set reserves_usd_bn = 1 where iso3 = 'BLZ';
update country set reserves_usd_bn = 2 where iso3 = 'GUY';
update country set reserves_usd_bn = 1 where iso3 = 'SUR';
update country set reserves_usd_bn = 2 where iso3 = 'HTI';
update country set reserves_usd_bn = 18 where iso3 = 'URY';
update country set reserves_usd_bn = 10 where iso3 = 'PRY';
update country set reserves_usd_bn = 2 where iso3 = 'BOL';
update country set reserves_usd_bn = 8 where iso3 = 'ECU';
update country set reserves_usd_bn = 11 where iso3 = 'VEN';
update country set reserves_usd_bn = NULL where iso3 = 'CUB';
update country set reserves_usd_bn = NULL where iso3 = 'PRK';
update country set reserves_usd_bn = NULL where iso3 = 'SYR';
update country set reserves_usd_bn = NULL where iso3 = 'PSE';
update country set reserves_usd_bn = 25 where iso3 = 'MAC';
update country set reserves_usd_bn = NULL where iso3 = 'PRI';

-- credit ratings
update country set rating_sp = 'AA+', rating_moodys = 'Aaa', rating_fitch = 'AA+' where iso3 = 'USA';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'DEU';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'CHE';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'NLD';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'SWE';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'NOR';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'DNK';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'SGP';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'AUS';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AA+' where iso3 = 'CAN';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AAA' where iso3 = 'LUX';
update country set rating_sp = 'AAA', rating_moodys = NULL, rating_fitch = NULL where iso3 = 'LIE';
update country set rating_sp = 'AA', rating_moodys = 'Aa3', rating_fitch = 'AA-' where iso3 = 'GBR';
update country set rating_sp = 'A+', rating_moodys = 'Aa3', rating_fitch = 'AA-' where iso3 = 'FRA';
update country set rating_sp = 'AA+', rating_moodys = 'Aa1', rating_fitch = 'AA+' where iso3 = 'AUT';
update country set rating_sp = 'AA+', rating_moodys = 'Aa1', rating_fitch = 'AA+' where iso3 = 'FIN';
update country set rating_sp = 'AA', rating_moodys = 'Aa3', rating_fitch = 'AA-' where iso3 = 'BEL';
update country set rating_sp = 'AA', rating_moodys = 'Aa3', rating_fitch = 'AA' where iso3 = 'IRL';
update country set rating_sp = 'AAA', rating_moodys = 'Aaa', rating_fitch = 'AA+' where iso3 = 'NZL';
update country set rating_sp = 'AA', rating_moodys = 'Aa2', rating_fitch = 'AA-' where iso3 = 'KOR';
update country set rating_sp = 'AA+', rating_moodys = 'Aa3', rating_fitch = 'AA' where iso3 = 'TWN';
update country set rating_sp = 'AA+', rating_moodys = 'Aa3', rating_fitch = 'AA-' where iso3 = 'HKG';
update country set rating_sp = 'A+', rating_moodys = 'A1', rating_fitch = 'A' where iso3 = 'JPN';
update country set rating_sp = 'A+', rating_moodys = 'A1', rating_fitch = 'A+' where iso3 = 'CHN';
update country set rating_sp = 'A', rating_moodys = 'Baa1', rating_fitch = 'A-' where iso3 = 'ISR';
update country set rating_sp = 'AA', rating_moodys = 'Aa2', rating_fitch = 'AA-' where iso3 = 'ARE';
update country set rating_sp = 'A+', rating_moodys = 'Aa3', rating_fitch = 'A+' where iso3 = 'SAU';
update country set rating_sp = 'AA', rating_moodys = 'Aa2', rating_fitch = 'AA' where iso3 = 'QAT';
update country set rating_sp = 'A+', rating_moodys = 'A1', rating_fitch = 'AA-' where iso3 = 'KWT';
update country set rating_sp = 'AA-', rating_moodys = 'Aa3', rating_fitch = 'AA-' where iso3 = 'CZE';
update country set rating_sp = 'AA-', rating_moodys = 'A1', rating_fitch = 'A' where iso3 = 'SVN';
update country set rating_sp = 'A+', rating_moodys = 'A1', rating_fitch = 'A+' where iso3 = 'EST';
update country set rating_sp = 'A+', rating_moodys = 'A2', rating_fitch = 'A' where iso3 = 'LTU';
update country set rating_sp = 'A+', rating_moodys = 'A3', rating_fitch = 'A-' where iso3 = 'LVA';
update country set rating_sp = 'A-', rating_moodys = 'A2', rating_fitch = 'A-' where iso3 = 'POL';
update country set rating_sp = 'A+', rating_moodys = 'A2', rating_fitch = 'A-' where iso3 = 'SVK';
update country set rating_sp = 'A', rating_moodys = 'Baa1', rating_fitch = 'A-' where iso3 = 'ESP';
update country set rating_sp = 'A-', rating_moodys = 'A3', rating_fitch = 'A-' where iso3 = 'PRT';
update country set rating_sp = 'BBB+', rating_moodys = 'Baa3', rating_fitch = 'BBB' where iso3 = 'ITA';
update country set rating_sp = 'A-', rating_moodys = 'A2', rating_fitch = 'A+' where iso3 = 'MLT';
update country set rating_sp = 'BBB+', rating_moodys = 'Baa2', rating_fitch = 'BBB' where iso3 = 'CYP';
update country set rating_sp = 'BBB', rating_moodys = 'Baa3', rating_fitch = 'BBB-' where iso3 = 'GRC';
update country set rating_sp = 'BBB-', rating_moodys = 'Baa2', rating_fitch = 'BBB' where iso3 = 'HUN';
update country set rating_sp = 'A-', rating_moodys = 'Baa2', rating_fitch = 'A-' where iso3 = 'HRV';
update country set rating_sp = 'BBB', rating_moodys = 'Baa1', rating_fitch = 'BBB' where iso3 = 'BGR';
update country set rating_sp = 'BBB-', rating_moodys = 'Baa3', rating_fitch = 'BBB-' where iso3 = 'ROU';
update country set rating_sp = 'A+', rating_moodys = 'A1', rating_fitch = 'A' where iso3 = 'ISL';
update country set rating_sp = 'BBB', rating_moodys = 'Baa3', rating_fitch = 'BBB-' where iso3 = 'IND';
update country set rating_sp = 'BBB', rating_moodys = 'Baa2', rating_fitch = 'BBB' where iso3 = 'IDN';
update country set rating_sp = 'A-', rating_moodys = 'A3', rating_fitch = 'BBB+' where iso3 = 'MYS';
update country set rating_sp = 'BBB+', rating_moodys = 'Baa1', rating_fitch = 'BBB+' where iso3 = 'THA';
update country set rating_sp = 'BBB+', rating_moodys = 'Baa2', rating_fitch = 'BBB' where iso3 = 'PHL';
update country set rating_sp = 'BB+', rating_moodys = 'Ba2', rating_fitch = 'BB+' where iso3 = 'VNM';
update country set rating_sp = 'A', rating_moodys = 'A2', rating_fitch = 'A-' where iso3 = 'CHL';
update country set rating_sp = 'BBB', rating_moodys = 'Baa2', rating_fitch = 'BBB-' where iso3 = 'MEX';
update country set rating_sp = 'BB', rating_moodys = 'Ba1', rating_fitch = 'BB' where iso3 = 'BRA';
update country set rating_sp = 'BB+', rating_moodys = 'Baa3', rating_fitch = 'BB+' where iso3 = 'COL';
update country set rating_sp = 'BBB-', rating_moodys = 'Baa1', rating_fitch = 'BBB' where iso3 = 'PER';
update country set rating_sp = 'BBB', rating_moodys = 'Baa1', rating_fitch = 'BBB' where iso3 = 'URY';
update country set rating_sp = 'BBB-', rating_moodys = 'Baa3', rating_fitch = 'BB+' where iso3 = 'PAN';
update country set rating_sp = 'CCC', rating_moodys = 'Ca', rating_fitch = 'CCC' where iso3 = 'ARG';
update country set rating_sp = 'BB-', rating_moodys = 'Ba2', rating_fitch = 'BB-' where iso3 = 'ZAF';
update country set rating_sp = 'BB+', rating_moodys = 'Ba1', rating_fitch = 'BB+' where iso3 = 'MAR';
update country set rating_sp = 'B-', rating_moodys = 'Caa1', rating_fitch = 'B' where iso3 = 'EGY';
update country set rating_sp = 'B-', rating_moodys = 'Caa1', rating_fitch = 'B-' where iso3 = 'NGA';
update country set rating_sp = 'B-', rating_moodys = 'Caa1', rating_fitch = 'B-' where iso3 = 'KEN';
update country set rating_sp = 'SD', rating_moodys = 'Ca', rating_fitch = 'RD' where iso3 = 'GHA';
update country set rating_sp = 'BB-', rating_moodys = 'B1', rating_fitch = 'BB-' where iso3 = 'TUR';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'RUS';
update country set rating_sp = 'SD', rating_moodys = 'Ca', rating_fitch = 'RD' where iso3 = 'UKR';
update country set rating_sp = 'CCC+', rating_moodys = 'Caa2', rating_fitch = 'CCC' where iso3 = 'PAK';
update country set rating_sp = 'SD', rating_moodys = 'Ca', rating_fitch = 'RD' where iso3 = 'LKA';
update country set rating_sp = 'B+', rating_moodys = 'B2', rating_fitch = 'B+' where iso3 = 'BGD';
update country set rating_sp = 'BBB-', rating_moodys = 'Baa2', rating_fitch = 'BBB' where iso3 = 'KAZ';
update country set rating_sp = 'BB+', rating_moodys = 'Ba1', rating_fitch = 'BB+' where iso3 = 'AZE';
update country set rating_sp = 'BB', rating_moodys = 'Ba2', rating_fitch = 'BB' where iso3 = 'GEO';
update country set rating_sp = 'BB-', rating_moodys = 'Ba3', rating_fitch = 'BB-' where iso3 = 'ARM';
update country set rating_sp = 'BB-', rating_moodys = 'Ba3', rating_fitch = 'BB-' where iso3 = 'UZB';
update country set rating_sp = 'BBB-', rating_moodys = 'Ba2', rating_fitch = 'BB+' where iso3 = 'SRB';
update country set rating_sp = 'BB-', rating_moodys = 'Ba3', rating_fitch = NULL where iso3 = 'ALB';
update country set rating_sp = 'BB-', rating_moodys = 'Ba3', rating_fitch = NULL where iso3 = 'MKD';
update country set rating_sp = 'B+', rating_moodys = 'B3', rating_fitch = NULL where iso3 = 'BIH';
update country set rating_sp = 'B+', rating_moodys = 'B1', rating_fitch = NULL where iso3 = 'MNE';
update country set rating_sp = NULL, rating_moodys = 'B3', rating_fitch = NULL where iso3 = 'MDA';
update country set rating_sp = 'SD', rating_moodys = 'Ca', rating_fitch = 'RD' where iso3 = 'BLR';
update country set rating_sp = 'BB-', rating_moodys = 'Ba3', rating_fitch = 'BB-' where iso3 = 'JOR';
update country set rating_sp = 'B+', rating_moodys = 'B2', rating_fitch = 'B+' where iso3 = 'BHR';
update country set rating_sp = 'BBB-', rating_moodys = 'Ba1', rating_fitch = 'BB+' where iso3 = 'OMN';
update country set rating_sp = 'B-', rating_moodys = 'Caa1', rating_fitch = 'B-' where iso3 = 'IRQ';
update country set rating_sp = 'SD', rating_moodys = 'C', rating_fitch = 'RD' where iso3 = 'LBN';
update country set rating_sp = NULL, rating_moodys = 'Caa2', rating_fitch = 'CCC+' where iso3 = 'TUN';
update country set rating_sp = 'SD', rating_moodys = 'Ca', rating_fitch = 'RD' where iso3 = 'ETH';
update country set rating_sp = 'SD', rating_moodys = 'Caa2', rating_fitch = 'RD' where iso3 = 'ZMB';
update country set rating_sp = 'B-', rating_moodys = 'B3', rating_fitch = 'B-' where iso3 = 'AGO';
update country set rating_sp = 'BB', rating_moodys = 'Ba2', rating_fitch = 'BB-' where iso3 = 'CIV';
update country set rating_sp = 'B+', rating_moodys = 'B1', rating_fitch = NULL where iso3 = 'SEN';
update country set rating_sp = 'B-', rating_moodys = 'Caa1', rating_fitch = 'B' where iso3 = 'CMR';
update country set rating_sp = 'CCC+', rating_moodys = 'Caa2', rating_fitch = 'CCC+' where iso3 = 'MOZ';
update country set rating_sp = 'B+', rating_moodys = 'B2', rating_fitch = 'B+' where iso3 = 'RWA';
update country set rating_sp = 'B-', rating_moodys = 'B3', rating_fitch = 'B' where iso3 = 'UGA';
update country set rating_sp = NULL, rating_moodys = 'B1', rating_fitch = 'B+' where iso3 = 'TZA';
update country set rating_sp = NULL, rating_moodys = 'B1', rating_fitch = 'BB-' where iso3 = 'NAM';
update country set rating_sp = 'BBB+', rating_moodys = 'A3', rating_fitch = NULL where iso3 = 'BWA';
update country set rating_sp = NULL, rating_moodys = 'Baa3', rating_fitch = 'BBB-' where iso3 = 'MUS';
update country set rating_sp = 'BB-', rating_moodys = 'B1', rating_fitch = 'BB-' where iso3 = 'JAM';
update country set rating_sp = 'BB', rating_moodys = 'Ba3', rating_fitch = 'BB-' where iso3 = 'DOM';
update country set rating_sp = 'BB', rating_moodys = 'Ba3', rating_fitch = 'BB' where iso3 = 'CRI';
update country set rating_sp = 'BB', rating_moodys = 'Ba1', rating_fitch = 'BB' where iso3 = 'GTM';
update country set rating_sp = 'B-', rating_moodys = 'Caa1', rating_fitch = 'B-' where iso3 = 'SLV';
update country set rating_sp = NULL, rating_moodys = 'B1', rating_fitch = NULL where iso3 = 'HND';
update country set rating_sp = 'BB+', rating_moodys = 'Baa3', rating_fitch = 'BB+' where iso3 = 'PRY';
update country set rating_sp = 'CCC', rating_moodys = 'Caa3', rating_fitch = 'CCC' where iso3 = 'BOL';
update country set rating_sp = 'B-', rating_moodys = 'Caa3', rating_fitch = 'CCC+' where iso3 = 'ECU';
update country set rating_sp = 'SD', rating_moodys = 'C', rating_fitch = 'RD' where iso3 = 'VEN';
update country set rating_sp = 'BBB-', rating_moodys = 'Ba1', rating_fitch = NULL where iso3 = 'TTO';
update country set rating_sp = 'B+', rating_moodys = 'B1', rating_fitch = NULL where iso3 = 'BHS';
update country set rating_sp = 'B', rating_moodys = 'B3', rating_fitch = NULL where iso3 = 'BRB';
update country set rating_sp = NULL, rating_moodys = 'Ba3', rating_fitch = NULL where iso3 = 'GUY';
update country set rating_sp = 'CCC+', rating_moodys = 'Caa3', rating_fitch = 'CCC+' where iso3 = 'SUR';
update country set rating_sp = 'CCC+', rating_moodys = 'Caa2', rating_fitch = 'CC' where iso3 = 'MDV';
update country set rating_sp = 'B', rating_moodys = 'B3', rating_fitch = 'B' where iso3 = 'MNG';
update country set rating_sp = NULL, rating_moodys = 'B2', rating_fitch = NULL where iso3 = 'KHM';
update country set rating_sp = 'CCC', rating_moodys = 'Caa3', rating_fitch = NULL where iso3 = 'LAO';
update country set rating_sp = 'B-', rating_moodys = 'B2', rating_fitch = 'B-' where iso3 = 'PNG';
update country set rating_sp = 'B+', rating_moodys = 'B1', rating_fitch = NULL where iso3 = 'FJI';
update country set rating_sp = NULL, rating_moodys = 'B1', rating_fitch = NULL where iso3 = 'NPL';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'MMR';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'AFG';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'SYR';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'PRK';
update country set rating_sp = NULL, rating_moodys = 'Ca', rating_fitch = NULL where iso3 = 'CUB';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'YEM';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'SDN';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'SOM';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'LBY';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'DZA';
update country set rating_sp = NULL, rating_moodys = NULL, rating_fitch = NULL where iso3 = 'IRN';

-- trade & supply chain
update country set exports_usd_bn = 3700, imports_usd_bn = 2600, top_export = 'Electronics & machinery', lpi_score = 3.7, trade_partners = 'United States, Hong Kong, Japan' where iso3 = 'CHN';
update country set exports_usd_bn = 3050, imports_usd_bn = 3900, top_export = 'Refined petroleum, aircraft, services', lpi_score = 3.8, trade_partners = 'Canada, Mexico, China' where iso3 = 'USA';
update country set exports_usd_bn = 2100, imports_usd_bn = 1750, top_export = 'Motor vehicles & machinery', lpi_score = 4.1, trade_partners = 'United States, France, Netherlands' where iso3 = 'DEU';
update country set exports_usd_bn = 1100, imports_usd_bn = 1050, top_export = 'Financial & business services', lpi_score = 3.7, trade_partners = 'United States, Germany, Netherlands' where iso3 = 'GBR';
update country set exports_usd_bn = 1000, imports_usd_bn = 1050, top_export = 'Aircraft, machinery, wine', lpi_score = 3.9, trade_partners = 'Germany, Italy, Belgium' where iso3 = 'FRA';
update country set exports_usd_bn = 920, imports_usd_bn = 900, top_export = 'Motor vehicles & machinery', lpi_score = 3.9, trade_partners = 'China, United States, South Korea' where iso3 = 'JPN';
update country set exports_usd_bn = 950, imports_usd_bn = 850, top_export = 'Machinery, refined petroleum (re-export hub)', lpi_score = 4.1, trade_partners = 'Germany, Belgium, France' where iso3 = 'NLD';
update country set exports_usd_bn = 840, imports_usd_bn = 730, top_export = 'Refined petroleum & electronics', lpi_score = 4.3, trade_partners = 'China, Malaysia, United States' where iso3 = 'SGP';
update country set exports_usd_bn = 800, imports_usd_bn = 900, top_export = 'Refined petroleum, IT services, pharmaceuticals', lpi_score = 3.4, trade_partners = 'United States, UAE, China' where iso3 = 'IND';
update country set exports_usd_bn = 780, imports_usd_bn = 720, top_export = 'Machinery, pharmaceuticals, fashion', lpi_score = 3.7, trade_partners = 'Germany, United States, France' where iso3 = 'ITA';
update country set exports_usd_bn = 770, imports_usd_bn = 730, top_export = 'Semiconductors & motor vehicles', lpi_score = 3.8, trade_partners = 'China, United States, Vietnam' where iso3 = 'KOR';
update country set exports_usd_bn = 750, imports_usd_bn = 530, top_export = 'Pharmaceuticals & medical devices', lpi_score = 3.6, trade_partners = 'United States, Germany, Belgium' where iso3 = 'IRL';
update country set exports_usd_bn = 700, imports_usd_bn = 680, top_export = 'Electronics (re-export hub)', lpi_score = 4.0, trade_partners = 'China, United States, India' where iso3 = 'HKG';
update country set exports_usd_bn = 700, imports_usd_bn = 690, top_export = 'Crude petroleum & motor vehicles', lpi_score = 4.0, trade_partners = 'United States, China, United Kingdom' where iso3 = 'CAN';
update country set exports_usd_bn = 660, imports_usd_bn = 570, top_export = 'Gold, pharmaceuticals, watches', lpi_score = 4.1, trade_partners = 'Germany, United States, China' where iso3 = 'CHE';
update country set exports_usd_bn = 630, imports_usd_bn = 650, top_export = 'Motor vehicles & electronics', lpi_score = 3.3, trade_partners = 'United States, Canada, China' where iso3 = 'MEX';
update country set exports_usd_bn = 600, imports_usd_bn = 470, top_export = 'Crude petroleum & gold', lpi_score = 4.0, trade_partners = 'India, Saudi Arabia, China' where iso3 = 'ARE';
update country set exports_usd_bn = 600, imports_usd_bn = 620, top_export = 'Motor vehicles, food, tourism', lpi_score = 3.9, trade_partners = 'France, Germany, Italy' where iso3 = 'ESP';
update country set exports_usd_bn = 600, imports_usd_bn = 580, top_export = 'Chemicals & pharmaceuticals', lpi_score = 4.0, trade_partners = 'Germany, France, Netherlands' where iso3 = 'BEL';
update country set exports_usd_bn = 580, imports_usd_bn = 470, top_export = 'Semiconductors', lpi_score = 3.7, trade_partners = 'China, United States, Japan' where iso3 = 'TWN';
update country set exports_usd_bn = 470, imports_usd_bn = 320, top_export = 'Crude petroleum & natural gas', lpi_score = 2.6, trade_partners = 'China, India, Turkey' where iso3 = 'RUS';
update country set exports_usd_bn = 450, imports_usd_bn = 440, top_export = 'Machinery & motor vehicles', lpi_score = 3.6, trade_partners = 'Germany, Czechia, France' where iso3 = 'POL';
update country set exports_usd_bn = 410, imports_usd_bn = 380, top_export = 'Iron ore, coal, natural gas', lpi_score = 3.7, trade_partners = 'China, Japan, South Korea' where iso3 = 'AUS';
update country set exports_usd_bn = 400, imports_usd_bn = 380, top_export = 'Electronics & textiles', lpi_score = 3.3, trade_partners = 'United States, China, South Korea' where iso3 = 'VNM';
update country set exports_usd_bn = 380, imports_usd_bn = 320, top_export = 'Soybeans, iron ore, crude petroleum', lpi_score = 3.2, trade_partners = 'China, United States, Argentina' where iso3 = 'BRA';
update country set exports_usd_bn = 380, imports_usd_bn = 360, top_export = 'Motor vehicles & electronics', lpi_score = 3.5, trade_partners = 'United States, China, Japan' where iso3 = 'THA';
update country set exports_usd_bn = 340, imports_usd_bn = 390, top_export = 'Motor vehicles & machinery', lpi_score = 3.4, trade_partners = 'Germany, United States, Iraq' where iso3 = 'TUR';
update country set exports_usd_bn = 330, imports_usd_bn = 220, top_export = 'Crude petroleum', lpi_score = 3.7, trade_partners = 'China, India, Japan' where iso3 = 'SAU';
update country set exports_usd_bn = 330, imports_usd_bn = 300, top_export = 'Electronics & palm oil', lpi_score = 3.6, trade_partners = 'Singapore, China, United States' where iso3 = 'MYS';
update country set exports_usd_bn = 300, imports_usd_bn = 300, top_export = 'Machinery & motor vehicles', lpi_score = 4.0, trade_partners = 'Germany, United States, Italy' where iso3 = 'AUT';
update country set exports_usd_bn = 290, imports_usd_bn = 260, top_export = 'Coal, palm oil, nickel', lpi_score = 3.0, trade_partners = 'China, United States, Japan' where iso3 = 'IDN';
update country set exports_usd_bn = 290, imports_usd_bn = 280, top_export = 'Machinery, motor vehicles, paper', lpi_score = 4.0, trade_partners = 'Germany, Norway, United States' where iso3 = 'SWE';
update country set exports_usd_bn = 250, imports_usd_bn = 235, top_export = 'Motor vehicles & machinery', lpi_score = 3.5, trade_partners = 'Germany, Slovakia, Poland' where iso3 = 'CZE';
update country set exports_usd_bn = 250, imports_usd_bn = 220, top_export = 'Pharmaceuticals & machinery', lpi_score = 4.1, trade_partners = 'Germany, Sweden, United States' where iso3 = 'DNK';
update country set exports_usd_bn = 190, imports_usd_bn = 140, top_export = 'Crude petroleum & natural gas', lpi_score = 3.9, trade_partners = 'United Kingdom, Germany, Netherlands' where iso3 = 'NOR';
update country set exports_usd_bn = 170, imports_usd_bn = 165, top_export = 'Motor vehicles & electronics', lpi_score = 3.4, trade_partners = 'Germany, Slovakia, Italy' where iso3 = 'HUN';
update country set exports_usd_bn = 160, imports_usd_bn = 140, top_export = 'Diamonds, electronics, pharmaceuticals', lpi_score = 3.4, trade_partners = 'United States, China, India' where iso3 = 'ISR';
update country set exports_usd_bn = 140, imports_usd_bn = 150, top_export = 'Machinery, textiles, tourism', lpi_score = 3.4, trade_partners = 'Spain, France, Germany' where iso3 = 'PRT';
update country set exports_usd_bn = 130, imports_usd_bn = 150, top_export = 'Electronics & business services', lpi_score = 3.3, trade_partners = 'United States, Japan, China' where iso3 = 'PHL';
update country set exports_usd_bn = 130, imports_usd_bn = 145, top_export = 'Motor vehicles & machinery', lpi_score = 3.2, trade_partners = 'Germany, Italy, France' where iso3 = 'ROU';
update country set exports_usd_bn = 130, imports_usd_bn = 55, top_export = 'Liquefied natural gas', lpi_score = 3.7, trade_partners = 'China, India, South Korea' where iso3 = 'QAT';
update country set exports_usd_bn = 130, imports_usd_bn = 125, top_export = 'Platinum, gold, motor vehicles', lpi_score = 3.7, trade_partners = 'China, United States, Germany' where iso3 = 'ZAF';
update country set exports_usd_bn = 110, imports_usd_bn = 105, top_export = 'Motor vehicles & electronics', lpi_score = 3.3, trade_partners = 'Germany, Czechia, Poland' where iso3 = 'SVK';
update country set exports_usd_bn = 110, imports_usd_bn = 110, top_export = 'Refined petroleum & tourism', lpi_score = 3.2, trade_partners = 'Italy, Germany, Cyprus' where iso3 = 'GRC';
update country set exports_usd_bn = 110, imports_usd_bn = 110, top_export = 'Paper, machinery, refined petroleum', lpi_score = 4.2, trade_partners = 'Germany, Sweden, United States' where iso3 = 'FIN';
update country set exports_usd_bn = 110, imports_usd_bn = 95, top_export = 'Copper', lpi_score = 3.3, trade_partners = 'China, United States, Japan' where iso3 = 'CHL';
update country set exports_usd_bn = 100, imports_usd_bn = 85, top_export = 'Soybeans, corn, beef', lpi_score = 2.9, trade_partners = 'Brazil, China, United States' where iso3 = 'ARG';
update country set exports_usd_bn = 85, imports_usd_bn = 45, top_export = 'Crude petroleum', lpi_score = 3.2, trade_partners = 'China, India, South Korea' where iso3 = 'KWT';
update country set exports_usd_bn = 75, imports_usd_bn = 65, top_export = 'Copper & gold', lpi_score = 2.9, trade_partners = 'China, United States, India' where iso3 = 'PER';
update country set exports_usd_bn = 65, imports_usd_bn = 80, top_export = 'Crude petroleum & coffee', lpi_score = 2.9, trade_partners = 'United States, China, Panama' where iso3 = 'COL';
update country set exports_usd_bn = 55, imports_usd_bn = 55, top_export = 'Dairy & meat', lpi_score = 3.5, trade_partners = 'China, Australia, United States' where iso3 = 'NZL';
update country set exports_usd_bn = 55, imports_usd_bn = 60, top_export = 'Crude petroleum', lpi_score = 2.6, trade_partners = 'India, Spain, Netherlands' where iso3 = 'NGA';
update country set exports_usd_bn = 55, imports_usd_bn = 75, top_export = 'Garments', lpi_score = 2.6, trade_partners = 'United States, Germany, United Kingdom' where iso3 = 'BGD';
update country set exports_usd_bn = 50, imports_usd_bn = 90, top_export = 'Refined petroleum, natural gas, fruit', lpi_score = 3.0, trade_partners = 'Turkey, Italy, United States' where iso3 = 'EGY';
update country set exports_usd_bn = 80, imports_usd_bn = 60, top_export = 'Crude petroleum & uranium', lpi_score = 2.7, trade_partners = 'China, Italy, Russia' where iso3 = 'KAZ';
update country set exports_usd_bn = 95, imports_usd_bn = 55, top_export = 'Crude petroleum', lpi_score = 2.4, trade_partners = 'China, India, South Korea' where iso3 = 'IRQ';
update country set exports_usd_bn = 40, imports_usd_bn = 60, top_export = 'Textiles & rice', lpi_score = 2.9, trade_partners = 'United States, China, United Kingdom' where iso3 = 'PAK';
update country set exports_usd_bn = 60, imports_usd_bn = 50, top_export = 'Crude petroleum & natural gas', lpi_score = 2.5, trade_partners = 'Italy, France, Spain' where iso3 = 'DZA';
update country set exports_usd_bn = 45, imports_usd_bn = 60, top_export = 'Grain & sunflower oil', lpi_score = 2.8, trade_partners = 'Poland, Turkey, Romania' where iso3 = 'UKR';
update country set exports_usd_bn = 50, imports_usd_bn = 70, top_export = 'Motor vehicles, phosphates, fertiliser', lpi_score = 2.8, trade_partners = 'Spain, France, Italy' where iso3 = 'MAR';
update country set exports_usd_bn = 55, imports_usd_bn = 60, top_export = 'Refined petroleum & copper', lpi_score = 3.0, trade_partners = 'Germany, Romania, Italy' where iso3 = 'BGR';
update country set exports_usd_bn = 40, imports_usd_bn = 45, top_export = 'Tourism, machinery, ships', lpi_score = 3.0, trade_partners = 'Italy, Germany, Slovenia' where iso3 = 'HRV';
update country set exports_usd_bn = 60, imports_usd_bn = 58, top_export = 'Motor vehicles & pharmaceuticals', lpi_score = 3.4, trade_partners = 'Germany, Italy, Croatia' where iso3 = 'SVN';
update country set exports_usd_bn = 55, imports_usd_bn = 55, top_export = 'Refined petroleum & furniture', lpi_score = 3.4, trade_partners = 'Germany, Poland, Latvia' where iso3 = 'LTU';
update country set exports_usd_bn = 28, imports_usd_bn = 30, top_export = 'Timber & food', lpi_score = 3.1, trade_partners = 'Lithuania, Estonia, Germany' where iso3 = 'LVA';
update country set exports_usd_bn = 28, imports_usd_bn = 30, top_export = 'Electronics & timber', lpi_score = 3.3, trade_partners = 'Finland, Sweden, Latvia' where iso3 = 'EST';
update country set exports_usd_bn = 160, imports_usd_bn = 150, top_export = 'Financial services & steel', lpi_score = 3.7, trade_partners = 'Germany, France, Belgium' where iso3 = 'LUX';
update country set exports_usd_bn = 45, imports_usd_bn = 45, top_export = 'Fertiliser & machinery', lpi_score = 2.6, trade_partners = 'Russia, Ukraine, China' where iso3 = 'BLR';
update country set exports_usd_bn = 25, imports_usd_bn = 35, top_export = 'Gold, natural gas, cotton', lpi_score = 2.6, trade_partners = 'China, Russia, Kazakhstan' where iso3 = 'UZB';
update country set exports_usd_bn = 30, imports_usd_bn = 20, top_export = 'Crude petroleum & natural gas', lpi_score = 2.7, trade_partners = 'Italy, Turkey, Israel' where iso3 = 'AZE';
update country set exports_usd_bn = 65, imports_usd_bn = 40, top_export = 'Crude petroleum & LNG', lpi_score = 3.2, trade_partners = 'China, India, South Korea' where iso3 = 'OMN';
update country set exports_usd_bn = 25, imports_usd_bn = 20, top_export = 'Refined petroleum & aluminium', lpi_score = 3.3, trade_partners = 'Saudi Arabia, UAE, United States' where iso3 = 'BHR';
update country set exports_usd_bn = 15, imports_usd_bn = 25, top_export = 'Fertiliser & textiles', lpi_score = 2.7, trade_partners = 'United States, Saudi Arabia, India' where iso3 = 'JOR';
update country set exports_usd_bn = 5, imports_usd_bn = 15, top_export = 'Jewellery & food', lpi_score = 2.5, trade_partners = 'UAE, Switzerland, Turkey' where iso3 = 'LBN';
update country set exports_usd_bn = 20, imports_usd_bn = 25, top_export = 'Textiles & electrical', lpi_score = 2.6, trade_partners = 'France, Italy, Germany' where iso3 = 'TUN';
update country set exports_usd_bn = 30, imports_usd_bn = 20, top_export = 'Crude petroleum', lpi_score = 2.2, trade_partners = 'Italy, Spain, Germany' where iso3 = 'LBY';
update country set exports_usd_bn = 10, imports_usd_bn = 20, top_export = 'Coffee & gold', lpi_score = 2.4, trade_partners = 'China, United States, Saudi Arabia' where iso3 = 'ETH';
update country set exports_usd_bn = 12, imports_usd_bn = 22, top_export = 'Tea, flowers, coffee', lpi_score = 3.0, trade_partners = 'Uganda, United States, Netherlands' where iso3 = 'KEN';
update country set exports_usd_bn = 14, imports_usd_bn = 16, top_export = 'Gold & cashews', lpi_score = 2.6, trade_partners = 'India, UAE, China' where iso3 = 'TZA';
update country set exports_usd_bn = 8, imports_usd_bn = 12, top_export = 'Coffee & gold', lpi_score = 2.6, trade_partners = 'UAE, Kenya, South Sudan' where iso3 = 'UGA';
update country set exports_usd_bn = 20, imports_usd_bn = 18, top_export = 'Gold, cocoa, crude petroleum', lpi_score = 2.6, trade_partners = 'Switzerland, India, China' where iso3 = 'GHA';
update country set exports_usd_bn = 18, imports_usd_bn = 16, top_export = 'Cocoa & cashews', lpi_score = 2.6, trade_partners = 'Netherlands, United States, Mali' where iso3 = 'CIV';
update country set exports_usd_bn = 8, imports_usd_bn = 12, top_export = 'Gold, refined petroleum, fish', lpi_score = 2.7, trade_partners = 'Mali, Switzerland, India' where iso3 = 'SEN';
update country set exports_usd_bn = 7, imports_usd_bn = 9, top_export = 'Crude petroleum & cocoa', lpi_score = 2.5, trade_partners = 'China, Netherlands, Italy' where iso3 = 'CMR';
update country set exports_usd_bn = 40, imports_usd_bn = 25, top_export = 'Crude petroleum', lpi_score = 2.3, trade_partners = 'China, India, UAE' where iso3 = 'AGO';
update country set exports_usd_bn = 12, imports_usd_bn = 10, top_export = 'Copper', lpi_score = 2.6, trade_partners = 'Switzerland, China, DR Congo' where iso3 = 'ZMB';
update country set exports_usd_bn = 25, imports_usd_bn = 20, top_export = 'Copper & cobalt', lpi_score = 2.2, trade_partners = 'China, UAE, Zambia' where iso3 = 'COD';
update country set exports_usd_bn = 7, imports_usd_bn = 8, top_export = 'Diamonds', lpi_score = 2.7, trade_partners = 'UAE, India, Belgium' where iso3 = 'BWA';
update country set exports_usd_bn = 6, imports_usd_bn = 8, top_export = 'Diamonds & uranium', lpi_score = 2.7, trade_partners = 'China, South Africa, Botswana' where iso3 = 'NAM';
update country set exports_usd_bn = 8, imports_usd_bn = 10, top_export = 'Aluminium & coal', lpi_score = 2.4, trade_partners = 'India, South Africa, China' where iso3 = 'MOZ';
update country set exports_usd_bn = 7, imports_usd_bn = 9, top_export = 'Gold & tobacco', lpi_score = 2.4, trade_partners = 'UAE, South Africa, China' where iso3 = 'ZWE';
update country set exports_usd_bn = 5, imports_usd_bn = 7, top_export = 'Textiles & sugar', lpi_score = 3.0, trade_partners = 'France, United States, South Africa' where iso3 = 'MUS';
update country set exports_usd_bn = 15, imports_usd_bn = 12, top_export = 'Copper & coal', lpi_score = 2.5, trade_partners = 'China, Switzerland, Singapore' where iso3 = 'MNG';
update country set exports_usd_bn = 16, imports_usd_bn = 20, top_export = 'Textiles & tea', lpi_score = 2.8, trade_partners = 'United States, United Kingdom, India' where iso3 = 'LKA';
update country set exports_usd_bn = 2, imports_usd_bn = 12, top_export = 'Textiles & carpets', lpi_score = 2.4, trade_partners = 'India, United States, Germany' where iso3 = 'NPL';
update country set exports_usd_bn = 18, imports_usd_bn = 17, top_export = 'Natural gas & garments', lpi_score = 2.4, trade_partners = 'China, Thailand, Japan' where iso3 = 'MMR';
update country set exports_usd_bn = 25, imports_usd_bn = 28, top_export = 'Garments & footwear', lpi_score = 2.7, trade_partners = 'United States, Vietnam, Japan' where iso3 = 'KHM';
update country set exports_usd_bn = 8, imports_usd_bn = 8, top_export = 'Electricity & copper', lpi_score = 2.4, trade_partners = 'Thailand, China, Vietnam' where iso3 = 'LAO';
update country set exports_usd_bn = 10, imports_usd_bn = 7, top_export = 'Crude petroleum & LNG', lpi_score = 2.7, trade_partners = 'Japan, Singapore, Australia' where iso3 = 'BRN';
update country set exports_usd_bn = 12, imports_usd_bn = 6, top_export = 'LNG, gold, copper', lpi_score = 2.4, trade_partners = 'China, Australia, Japan' where iso3 = 'PNG';
update country set exports_usd_bn = 2, imports_usd_bn = 3, top_export = 'Tourism, sugar, fish', lpi_score = 2.6, trade_partners = 'United States, Australia, New Zealand' where iso3 = 'FJI';
update country set exports_usd_bn = 15, imports_usd_bn = 13, top_export = 'Beef, soybeans, cellulose', lpi_score = 3.0, trade_partners = 'China, Brazil, United States' where iso3 = 'URY';
update country set exports_usd_bn = 15, imports_usd_bn = 14, top_export = 'Soybeans & beef', lpi_score = 2.6, trade_partners = 'Brazil, Argentina, Chile' where iso3 = 'PRY';
update country set exports_usd_bn = 12, imports_usd_bn = 11, top_export = 'Natural gas, zinc, gold', lpi_score = 2.5, trade_partners = 'Brazil, Argentina, India' where iso3 = 'BOL';
update country set exports_usd_bn = 35, imports_usd_bn = 30, top_export = 'Crude petroleum, bananas, shrimp', lpi_score = 2.6, trade_partners = 'United States, China, Panama' where iso3 = 'ECU';
update country set exports_usd_bn = 15, imports_usd_bn = 10, top_export = 'Crude petroleum', lpi_score = 2.2, trade_partners = 'China, India, Spain' where iso3 = 'VEN';
update country set exports_usd_bn = 25, imports_usd_bn = 22, top_export = 'Medical devices & bananas', lpi_score = 3.0, trade_partners = 'United States, Netherlands, Guatemala' where iso3 = 'CRI';
update country set exports_usd_bn = 30, imports_usd_bn = 28, top_export = 'Re-export & canal services', lpi_score = 3.2, trade_partners = 'United States, China, Ecuador' where iso3 = 'PAN';
update country set exports_usd_bn = 18, imports_usd_bn = 25, top_export = 'Coffee, sugar, bananas', lpi_score = 2.6, trade_partners = 'United States, El Salvador, Honduras' where iso3 = 'GTM';
update country set exports_usd_bn = 25, imports_usd_bn = 28, top_export = 'Medical devices, gold, cigars', lpi_score = 2.6, trade_partners = 'United States, Switzerland, Canada' where iso3 = 'DOM';
update country set exports_usd_bn = 5, imports_usd_bn = 8, top_export = 'Alumina & bauxite', lpi_score = 2.7, trade_partners = 'United States, Netherlands, Canada' where iso3 = 'JAM';
update country set exports_usd_bn = 12, imports_usd_bn = 8, top_export = 'LNG & petrochemicals', lpi_score = 2.8, trade_partners = 'United States, Guyana, Argentina' where iso3 = 'TTO';
update country set exports_usd_bn = 18, imports_usd_bn = 8, top_export = 'Crude petroleum & gold', lpi_score = 2.5, trade_partners = 'Panama, United States, Netherlands' where iso3 = 'GUY';
update country set exports_usd_bn = 15, imports_usd_bn = 13, top_export = 'Fish & aluminium', lpi_score = 3.2, trade_partners = 'Netherlands, United Kingdom, Spain' where iso3 = 'ISL';
update country set exports_usd_bn = 30, imports_usd_bn = 28, top_export = 'Shipping & tourism services', lpi_score = 3.0, trade_partners = 'Greece, United Kingdom, Israel' where iso3 = 'CYP';
update country set exports_usd_bn = 25, imports_usd_bn = 23, top_export = 'Electronics & gaming services', lpi_score = 3.0, trade_partners = 'Germany, France, Italy' where iso3 = 'MLT';
update country set exports_usd_bn = 35, imports_usd_bn = 38, top_export = 'Motor vehicles & machinery', lpi_score = 2.9, trade_partners = 'Germany, Italy, Bosnia' where iso3 = 'SRB';
update country set exports_usd_bn = 6, imports_usd_bn = 9, top_export = 'Textiles & minerals', lpi_score = 2.7, trade_partners = 'Italy, Spain, Germany' where iso3 = 'ALB';
update country set exports_usd_bn = 9, imports_usd_bn = 11, top_export = 'Catalysts & motor parts', lpi_score = 2.7, trade_partners = 'Germany, Serbia, Bulgaria' where iso3 = 'MKD';
update country set exports_usd_bn = 10, imports_usd_bn = 13, top_export = 'Metals & furniture', lpi_score = 2.7, trade_partners = 'Germany, Croatia, Serbia' where iso3 = 'BIH';
update country set exports_usd_bn = 8, imports_usd_bn = 13, top_export = 'Copper & motor vehicle re-export', lpi_score = 2.8, trade_partners = 'China, Bulgaria, Armenia' where iso3 = 'GEO';
update country set exports_usd_bn = 9, imports_usd_bn = 11, top_export = 'Gold, copper, brandy', lpi_score = 2.6, trade_partners = 'Russia, UAE, China' where iso3 = 'ARM';
update country set exports_usd_bn = 5, imports_usd_bn = 10, top_export = 'Sunflower & wine', lpi_score = 2.6, trade_partners = 'Romania, Ukraine, Italy' where iso3 = 'MDA';
update country set exports_usd_bn = 4, imports_usd_bn = 10, top_export = 'Gold', lpi_score = 2.5, trade_partners = 'Russia, Kazakhstan, Turkey' where iso3 = 'KGZ';
update country set exports_usd_bn = 3, imports_usd_bn = 6, top_export = 'Aluminium & cotton', lpi_score = 2.4, trade_partners = 'Kazakhstan, Turkey, Switzerland' where iso3 = 'TJK';
update country set exports_usd_bn = 12, imports_usd_bn = 5, top_export = 'Natural gas', lpi_score = 2.4, trade_partners = 'China, Turkey, Russia' where iso3 = 'TKM';
update country set exports_usd_bn = 2, imports_usd_bn = 7, top_export = 'Fruit & carpets', lpi_score = 1.9, trade_partners = 'Pakistan, India, UAE' where iso3 = 'AFG';
update country set exports_usd_bn = 80, imports_usd_bn = 60, top_export = 'Crude petroleum & petrochemicals', lpi_score = 2.5, trade_partners = 'China, UAE, Turkey' where iso3 = 'IRN';
update country set exports_usd_bn = 2, imports_usd_bn = 8, top_export = 'Crude petroleum & fish', lpi_score = 2.0, trade_partners = 'China, Thailand, UAE' where iso3 = 'YEM';
update country set exports_usd_bn = 5, imports_usd_bn = 8, top_export = 'Gold & livestock', lpi_score = 2.1, trade_partners = 'UAE, Saudi Arabia, Egypt' where iso3 = 'SDN';

-- indicator definitions
insert into indicator (code, name, unit, definition, perimeter, valuation, caveat, source, vintage) values
  ('CURRENT_ACCOUNT', 'Current account balance', 'pct_gdp', 'The broadest measure of transactions with the rest of the world - trade in goods and services, income and transfers - as a share of GDP.', 'whole_economy', NULL, 'A surplus is not automatically good nor a deficit bad. A deficit means a country absorbs more than it produces and finances the difference from abroad - sustainable for a reserve-currency issuer, dangerous for one dependent on volatile capital inflows. Read it alongside the exchange rate regime and reserves.', 'IMF World Economic Outlook', '2025 estimate'),
  ('INFLATION', 'Inflation (CPI)', 'pct', 'Annual average change in consumer prices.', NULL, NULL, 'The number that makes every other nominal figure on this site readable. Basket composition differs between countries, so cross-country comparison is indicative rather than exact.', 'IMF World Economic Outlook', '2025 estimate'),
  ('RESERVES', 'Foreign exchange reserves', 'usd_bn', 'Total official reserve assets including gold, held by the central bank.', 'central_bank', 'market', 'Adequacy depends on exposure, not the raw total - a large economy with a floating currency needs proportionally far less than a small one running a peg. Gold is valued at market prices, so totals move with the gold price alone.', 'IMF / World Bank', 'latest available'),
  ('RATING', 'Sovereign credit rating', 'grade', 'Long-term foreign-currency issuer rating from S&P, Moody''s and Fitch.', NULL, NULL, 'Opinions, not measurements - and the agencies disagree with each other regularly, which is itself informative. Ratings move on the agencies'' own schedules, so verify against the agency directly. SD or RD means selective or restricted default; absence means unrated, not creditworthy or otherwise.', 'S&P Global / Moody''s / Fitch', 'point-in-time, verify'),
  ('TRADE', 'Exports & imports', 'usd_bn', 'Goods and services crossing the border, in US dollars, for the latest full year.', 'whole_economy', NULL, 'Re-export hubs distort this badly. Hong Kong, Singapore, Netherlands and Luxembourg all record goods that arrive, get re-labelled and leave again - so their trade can exceed their entire GDP several times over without that reflecting domestic production. Compare trade openness against economic size before drawing conclusions.', 'IMF / World Bank / national statistics', 'latest full year'),
  ('TRADE_OPENNESS', 'Trade openness', 'pct_gdp', 'Exports plus imports as a share of GDP. Derived, not separately sourced.', NULL, NULL, 'Above 100% is normal for small open economies and re-export hubs, where the same goods cross the border more than once. A low figure usually means a large domestic market rather than isolation - the United States sits near 25% because most of what Americans buy is made in America.', 'Derived', 'latest full year'),
  ('TOP_EXPORT', 'Principal export', 'category', 'The dominant export category by value.', NULL, NULL, 'A broad classification, not a precise share. Concentration is the thing to notice: an economy whose single largest export is crude petroleum is exposed to one price in a way a diversified manufacturer is not, and that exposure shows up in the currency, the budget and the credit rating.', 'National statistics / UN Comtrade', 'latest full year'),
  ('LPI', 'Logistics Performance Index', 'score', 'World Bank composite score, 1 to 5, covering customs, infrastructure, shipment timeliness and tracking.', NULL, NULL, 'A survey-based perception index, not a physical measurement - it reflects what freight professionals report, so it captures reputation alongside reality. Published irregularly rather than annually, so a score may be several years old. Useful as a rough tier, not a precise ranking.', 'World Bank Logistics Performance Index', '2023 edition'),
  ('PARTNERS', 'Principal trading partners', 'list', 'The largest destinations and sources of trade by value.', NULL, NULL, 'Concentration matters more than the names. A country whose trade runs overwhelmingly through one neighbour has a different risk profile from one spread across three continents - and that dependency is invisible in any single number on this site.', 'National statistics / UN Comtrade', 'latest full year')
on conflict (code) do update set definition=excluded.definition, caveat=excluded.caveat, vintage=excluded.vintage;
